"""
PCG Scatter Placement Patterns.

Provides various scatter placement algorithms for procedural content generation:
- Random: Uniform random distribution
- Poisson Disk: Ensures minimum spacing between points (dart-throwing)
- Grid: Regular grid placement
- Jittered Grid: Grid with random offset
- Clustered: Points grouped in clusters
- Organic: Natural-looking distribution using noise modulation

All generators are deterministic given the same seed.
Uses Trinity Pattern with @seeded for deterministic generation.
"""

from __future__ import annotations

import math
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Callable, List, Optional, Tuple

from engine.world.pcg.noise import NoiseMap


class ScatterPattern(Enum):
    """Types of scatter placement patterns."""

    RANDOM = auto()
    POISSON_DISK = auto()
    GRID = auto()
    JITTERED_GRID = auto()
    CLUSTERED = auto()
    ORGANIC = auto()


@dataclass
class ScatterSettings:
    """Configuration for scatter placement."""

    pattern: ScatterPattern = ScatterPattern.POISSON_DISK
    density: float = 1.0
    min_spacing: float = 1.0
    seed: int = 0
    jitter: float = 0.0
    cluster_size: int = 5
    cluster_radius: float = 10.0

    def __post_init__(self) -> None:
        """Validate settings after initialization."""
        if self.density <= 0:
            raise ValueError(f"density must be > 0, got {self.density}")
        if self.min_spacing <= 0:
            raise ValueError(f"min_spacing must be > 0, got {self.min_spacing}")
        if self.jitter < 0:
            raise ValueError(f"jitter must be >= 0, got {self.jitter}")
        if self.cluster_size < 1:
            raise ValueError(f"cluster_size must be >= 1, got {self.cluster_size}")
        if self.cluster_radius <= 0:
            raise ValueError(f"cluster_radius must be > 0, got {self.cluster_radius}")


@dataclass
class ScatterPoint:
    """A point generated by scatter placement."""

    position: Tuple[float, float]
    weight: float = 1.0

    @property
    def x(self) -> float:
        """Get x coordinate."""
        return self.position[0]

    @property
    def y(self) -> float:
        """Get y coordinate."""
        return self.position[1]


@dataclass
class Bounds:
    """Rectangular bounds for scatter placement."""

    min_x: float = 0.0
    min_y: float = 0.0
    max_x: float = 100.0
    max_y: float = 100.0

    def __post_init__(self) -> None:
        """Validate bounds."""
        if self.min_x >= self.max_x:
            raise ValueError(f"min_x ({self.min_x}) must be < max_x ({self.max_x})")
        if self.min_y >= self.max_y:
            raise ValueError(f"min_y ({self.min_y}) must be < max_y ({self.max_y})")

    @property
    def width(self) -> float:
        """Get bounds width."""
        return self.max_x - self.min_x

    @property
    def height(self) -> float:
        """Get bounds height."""
        return self.max_y - self.min_y

    @property
    def area(self) -> float:
        """Get bounds area."""
        return self.width * self.height

    def contains(self, x: float, y: float) -> bool:
        """Check if a point is within bounds."""
        return self.min_x <= x <= self.max_x and self.min_y <= y <= self.max_y


class DeterministicRandom:
    """
    Deterministic random number generator for scatter algorithms.

    Uses a simple LCG (Linear Congruential Generator) that produces
    the same sequence for the same seed.
    """

    def __init__(self, seed: int = 0) -> None:
        """Initialize with seed."""
        self._seed = seed
        self._state = seed

    def reset(self, seed: Optional[int] = None) -> None:
        """Reset the generator state."""
        if seed is not None:
            self._seed = seed
        self._state = self._seed

    def _advance(self) -> int:
        """Advance the internal state and return the new value."""
        self._state = (self._state * 1103515245 + 12345) & 0x7FFFFFFF
        return self._state

    def next_int(self, min_val: int, max_val: int) -> int:
        """
        Generate a random integer in [min_val, max_val].

        Args:
            min_val: Minimum value (inclusive)
            max_val: Maximum value (inclusive)

        Returns:
            Random integer in range
        """
        if min_val > max_val:
            min_val, max_val = max_val, min_val
        if min_val == max_val:
            return min_val

        range_val = max_val - min_val + 1
        return min_val + (self._advance() % range_val)

    def next_float(self, min_val: float = 0.0, max_val: float = 1.0) -> float:
        """
        Generate a random float in [min_val, max_val].

        Args:
            min_val: Minimum value
            max_val: Maximum value

        Returns:
            Random float in range
        """
        normalized = self._advance() / 0x7FFFFFFF
        return min_val + normalized * (max_val - min_val)

    def next_point_in_bounds(self, bounds: Bounds) -> Tuple[float, float]:
        """
        Generate a random point within bounds.

        Args:
            bounds: The bounds to generate within

        Returns:
            Random (x, y) coordinate
        """
        x = self.next_float(bounds.min_x, bounds.max_x)
        y = self.next_float(bounds.min_y, bounds.max_y)
        return (x, y)

    def next_point_in_circle(self, radius: float) -> Tuple[float, float]:
        """
        Generate a random point in a circle centered at origin.

        Args:
            radius: Circle radius

        Returns:
            Random (x, y) coordinate within circle
        """
        # Rejection sampling for uniform distribution
        while True:
            x = self.next_float(-radius, radius)
            y = self.next_float(-radius, radius)
            if x * x + y * y <= radius * radius:
                return (x, y)

    def next_point_in_annulus(
        self, inner_radius: float, outer_radius: float
    ) -> Tuple[float, float]:
        """
        Generate a random point in an annulus (ring) centered at origin.

        Args:
            inner_radius: Inner radius of ring
            outer_radius: Outer radius of ring

        Returns:
            Random (x, y) coordinate within annulus
        """
        # Use sqrt for uniform area distribution
        angle = self.next_float(0, 2 * math.pi)
        r_sq = self.next_float(inner_radius * inner_radius, outer_radius * outer_radius)
        r = math.sqrt(r_sq)
        return (r * math.cos(angle), r * math.sin(angle))

    def shuffle(self, items: List) -> List:
        """
        Return a shuffled copy of the list.

        Args:
            items: List to shuffle

        Returns:
            New shuffled list
        """
        result = list(items)
        for i in range(len(result) - 1, 0, -1):
            j = self.next_int(0, i)
            result[i], result[j] = result[j], result[i]
        return result


class ScatterGenerator(ABC):
    """Abstract base class for scatter generators."""

    def __init__(self, settings: Optional[ScatterSettings] = None) -> None:
        """
        Initialize the scatter generator.

        Args:
            settings: Scatter configuration settings
        """
        self._settings = settings or ScatterSettings()
        self._random = DeterministicRandom(self._settings.seed)

    @property
    def settings(self) -> ScatterSettings:
        """Get the generator settings."""
        return self._settings

    @abstractmethod
    def generate(
        self, bounds: Bounds, count: Optional[int] = None
    ) -> List[ScatterPoint]:
        """
        Generate scatter points within bounds.

        Args:
            bounds: Rectangular bounds for placement
            count: Optional point count (interpretation varies by generator)

        Returns:
            List of scatter points
        """
        pass

    def _create_point(self, x: float, y: float, weight: float = 1.0) -> ScatterPoint:
        """Create a scatter point."""
        return ScatterPoint(position=(x, y), weight=weight)


class RandomScatter(ScatterGenerator):
    """
    Uniform random scatter generator.

    Points are placed completely randomly within bounds.
    May result in clumping and empty areas.
    """

    def generate(
        self, bounds: Bounds, count: Optional[int] = None
    ) -> List[ScatterPoint]:
        """
        Generate uniformly random scatter points.

        Args:
            bounds: Rectangular bounds for placement
            count: Number of points to generate (uses density if None)

        Returns:
            List of scatter points
        """
        self._random.reset()

        if count is None:
            count = int(bounds.area * self._settings.density)

        points: List[ScatterPoint] = []

        for _ in range(count):
            x, y = self._random.next_point_in_bounds(bounds)
            points.append(self._create_point(x, y))

        return points


class PoissonDiskScatter(ScatterGenerator):
    """
    Poisson disk scatter generator using dart-throwing algorithm.

    Ensures a minimum spacing between all points while filling space efficiently.
    Produces natural-looking distributions without clumping.
    """

    def __init__(
        self,
        settings: Optional[ScatterSettings] = None,
        max_attempts: int = 30,
    ) -> None:
        """
        Initialize Poisson disk scatter.

        Args:
            settings: Scatter settings (uses min_spacing for disk radius)
            max_attempts: Maximum attempts to place around each point
        """
        super().__init__(settings)
        self._max_attempts = max_attempts

    @property
    def max_attempts(self) -> int:
        """Get maximum placement attempts per point."""
        return self._max_attempts

    @property
    def min_distance(self) -> float:
        """Get minimum distance between points."""
        return self._settings.min_spacing

    def generate(
        self, bounds: Bounds, count: Optional[int] = None
    ) -> List[ScatterPoint]:
        """
        Generate Poisson disk sampled scatter points.

        Uses the dart-throwing algorithm with spatial grid acceleration.
        The count parameter is ignored; points are generated until space is filled.

        Args:
            bounds: Rectangular bounds for placement
            count: Ignored (points fill space based on min_spacing)

        Returns:
            List of scatter points with guaranteed minimum spacing
        """
        self._random.reset()

        min_dist = self._settings.min_spacing
        cell_size = min_dist / math.sqrt(2)

        # Grid for spatial lookup
        grid_width = int(math.ceil(bounds.width / cell_size))
        grid_height = int(math.ceil(bounds.height / cell_size))
        grid: List[List[Optional[int]]] = [
            [None] * grid_width for _ in range(grid_height)
        ]

        points: List[ScatterPoint] = []
        active_list: List[int] = []

        # Helper to get grid cell
        def grid_pos(x: float, y: float) -> Tuple[int, int]:
            gx = int((x - bounds.min_x) / cell_size)
            gy = int((y - bounds.min_y) / cell_size)
            return (
                max(0, min(gx, grid_width - 1)),
                max(0, min(gy, grid_height - 1)),
            )

        # Helper to check if point is valid
        def is_valid(x: float, y: float) -> bool:
            if not bounds.contains(x, y):
                return False

            gx, gy = grid_pos(x, y)

            # Check neighboring cells
            for dy in range(-2, 3):
                for dx in range(-2, 3):
                    nx, ny = gx + dx, gy + dy
                    if 0 <= nx < grid_width and 0 <= ny < grid_height:
                        idx = grid[ny][nx]
                        if idx is not None:
                            p = points[idx]
                            dist_sq = (x - p.x) ** 2 + (y - p.y) ** 2
                            if dist_sq < min_dist * min_dist:
                                return False
            return True

        # Add first point
        first_x, first_y = self._random.next_point_in_bounds(bounds)
        points.append(self._create_point(first_x, first_y))
        active_list.append(0)
        gx, gy = grid_pos(first_x, first_y)
        grid[gy][gx] = 0

        # Process active list
        while active_list:
            # Pick random active point
            idx = self._random.next_int(0, len(active_list) - 1)
            point_idx = active_list[idx]
            point = points[point_idx]

            found = False

            for _ in range(self._max_attempts):
                # Generate point in annulus
                offset_x, offset_y = self._random.next_point_in_annulus(
                    min_dist, 2 * min_dist
                )
                new_x = point.x + offset_x
                new_y = point.y + offset_y

                if is_valid(new_x, new_y):
                    new_idx = len(points)
                    points.append(self._create_point(new_x, new_y))
                    active_list.append(new_idx)
                    gx, gy = grid_pos(new_x, new_y)
                    grid[gy][gx] = new_idx
                    found = True
                    break

            if not found:
                # Remove from active list
                active_list[idx] = active_list[-1]
                active_list.pop()

        return points


class GridScatter(ScatterGenerator):
    """
    Regular grid scatter generator.

    Places points in a regular grid pattern.
    """

    def __init__(
        self,
        settings: Optional[ScatterSettings] = None,
        spacing: Optional[float] = None,
    ) -> None:
        """
        Initialize grid scatter.

        Args:
            settings: Scatter settings
            spacing: Grid cell spacing (uses min_spacing if None)
        """
        super().__init__(settings)
        self._spacing = spacing if spacing is not None else self._settings.min_spacing

    @property
    def spacing(self) -> float:
        """Get grid spacing."""
        return self._spacing

    def generate(
        self, bounds: Bounds, count: Optional[int] = None
    ) -> List[ScatterPoint]:
        """
        Generate grid scatter points.

        Args:
            bounds: Rectangular bounds for placement
            count: Ignored (determined by spacing)

        Returns:
            List of scatter points in grid pattern
        """
        self._random.reset()

        points: List[ScatterPoint] = []
        spacing = self._spacing

        x = bounds.min_x + spacing / 2
        while x < bounds.max_x:
            y = bounds.min_y + spacing / 2
            while y < bounds.max_y:
                points.append(self._create_point(x, y))
                y += spacing
            x += spacing

        return points


class JitteredGridScatter(ScatterGenerator):
    """
    Jittered grid scatter generator.

    Places points in a grid pattern with random offset (jitter).
    Provides a balance between regularity and randomness.
    """

    def __init__(
        self,
        settings: Optional[ScatterSettings] = None,
        spacing: Optional[float] = None,
        jitter: Optional[float] = None,
    ) -> None:
        """
        Initialize jittered grid scatter.

        Args:
            settings: Scatter settings
            spacing: Grid cell spacing (uses min_spacing if None)
            jitter: Maximum offset as fraction of spacing [0, 0.5] (uses settings if None)
        """
        super().__init__(settings)
        self._spacing = spacing if spacing is not None else self._settings.min_spacing
        self._jitter = jitter if jitter is not None else self._settings.jitter

        if self._jitter < 0 or self._jitter > 0.5:
            raise ValueError(f"jitter must be in [0, 0.5], got {self._jitter}")

    @property
    def spacing(self) -> float:
        """Get grid spacing."""
        return self._spacing

    @property
    def jitter(self) -> float:
        """Get jitter amount."""
        return self._jitter

    def generate(
        self, bounds: Bounds, count: Optional[int] = None
    ) -> List[ScatterPoint]:
        """
        Generate jittered grid scatter points.

        Args:
            bounds: Rectangular bounds for placement
            count: Ignored (determined by spacing)

        Returns:
            List of scatter points in jittered grid pattern
        """
        self._random.reset()

        points: List[ScatterPoint] = []
        spacing = self._spacing
        max_offset = spacing * self._jitter

        x = bounds.min_x + spacing / 2
        while x < bounds.max_x:
            y = bounds.min_y + spacing / 2
            while y < bounds.max_y:
                # Apply random jitter
                jx = x + self._random.next_float(-max_offset, max_offset)
                jy = y + self._random.next_float(-max_offset, max_offset)

                # Keep within bounds
                jx = max(bounds.min_x, min(jx, bounds.max_x))
                jy = max(bounds.min_y, min(jy, bounds.max_y))

                points.append(self._create_point(jx, jy))
                y += spacing
            x += spacing

        return points


class ClusteredScatter(ScatterGenerator):
    """
    Clustered scatter generator.

    Creates groups of points clustered around center points.
    Useful for natural formations like trees in groves.
    """

    def __init__(
        self,
        settings: Optional[ScatterSettings] = None,
        cluster_count: Optional[int] = None,
        points_per_cluster: Optional[int] = None,
        cluster_radius: Optional[float] = None,
    ) -> None:
        """
        Initialize clustered scatter.

        Args:
            settings: Scatter settings
            cluster_count: Number of clusters (computed from density if None)
            points_per_cluster: Points per cluster (uses cluster_size if None)
            cluster_radius: Radius of each cluster (uses settings if None)
        """
        super().__init__(settings)
        self._cluster_count = cluster_count
        self._points_per_cluster = (
            points_per_cluster
            if points_per_cluster is not None
            else self._settings.cluster_size
        )
        self._cluster_radius = (
            cluster_radius
            if cluster_radius is not None
            else self._settings.cluster_radius
        )

    @property
    def cluster_count(self) -> Optional[int]:
        """Get cluster count (may be None for auto-calculation)."""
        return self._cluster_count

    @property
    def points_per_cluster(self) -> int:
        """Get points per cluster."""
        return self._points_per_cluster

    @property
    def cluster_radius(self) -> float:
        """Get cluster radius."""
        return self._cluster_radius

    def generate(
        self, bounds: Bounds, count: Optional[int] = None
    ) -> List[ScatterPoint]:
        """
        Generate clustered scatter points.

        Args:
            bounds: Rectangular bounds for placement
            count: Total number of points (uses density if None)

        Returns:
            List of scatter points in cluster pattern
        """
        self._random.reset()

        # Determine number of clusters
        if count is not None:
            total_points = count
            num_clusters = max(1, total_points // self._points_per_cluster)
        elif self._cluster_count is not None:
            num_clusters = self._cluster_count
            total_points = num_clusters * self._points_per_cluster
        else:
            total_points = int(bounds.area * self._settings.density)
            num_clusters = max(1, total_points // self._points_per_cluster)

        points: List[ScatterPoint] = []
        points_remaining = total_points

        # Generate cluster centers
        cluster_centers: List[Tuple[float, float]] = []
        for _ in range(num_clusters):
            center = self._random.next_point_in_bounds(bounds)
            cluster_centers.append(center)

        # Generate points around each cluster
        for i, center in enumerate(cluster_centers):
            # Last cluster gets remaining points
            if i == num_clusters - 1:
                cluster_points = points_remaining
            else:
                cluster_points = self._points_per_cluster
                points_remaining -= cluster_points

            for _ in range(cluster_points):
                # Random point in cluster
                offset_x, offset_y = self._random.next_point_in_circle(
                    self._cluster_radius
                )
                x = center[0] + offset_x
                y = center[1] + offset_y

                # Keep within bounds
                x = max(bounds.min_x, min(x, bounds.max_x))
                y = max(bounds.min_y, min(y, bounds.max_y))

                # Weight decreases from center
                dist = math.sqrt(offset_x * offset_x + offset_y * offset_y)
                weight = 1.0 - (dist / self._cluster_radius) * 0.5

                points.append(self._create_point(x, y, weight))

        return points


class OrganicScatter(ScatterGenerator):
    """
    Organic scatter generator using Poisson disk with noise modulation.

    Produces natural-looking distributions influenced by noise.
    Points are more/less dense based on noise values.
    """

    def __init__(
        self,
        settings: Optional[ScatterSettings] = None,
        noise_map: Optional[NoiseMap] = None,
        noise_threshold: float = 0.0,
        density_from_noise: bool = True,
    ) -> None:
        """
        Initialize organic scatter.

        Args:
            settings: Scatter settings
            noise_map: Noise map for modulation (creates default if None)
            noise_threshold: Minimum noise value for placement
            density_from_noise: If True, varies spacing based on noise
        """
        super().__init__(settings)
        self._noise_map = noise_map
        self._noise_threshold = noise_threshold
        self._density_from_noise = density_from_noise
        self._poisson = PoissonDiskScatter(settings, max_attempts=30)

    @property
    def noise_threshold(self) -> float:
        """Get the noise threshold for placement."""
        return self._noise_threshold

    @property
    def density_from_noise(self) -> bool:
        """Check if density varies with noise."""
        return self._density_from_noise

    def generate(
        self,
        bounds: Bounds,
        count: Optional[int] = None,
        noise_map: Optional[NoiseMap] = None,
    ) -> List[ScatterPoint]:
        """
        Generate organic scatter points.

        Args:
            bounds: Rectangular bounds for placement
            count: Ignored
            noise_map: Override noise map for this generation

        Returns:
            List of scatter points with organic distribution
        """
        self._random.reset()

        # Use provided or stored noise map
        nmap = noise_map or self._noise_map

        # Generate base Poisson distribution
        base_points = self._poisson.generate(bounds)

        if nmap is None:
            # No noise - return base points
            return base_points

        # Filter and weight by noise
        points: List[ScatterPoint] = []

        for point in base_points:
            # Map point position to noise map coordinates
            nx = (point.x - bounds.min_x) / bounds.width * (nmap.width - 1)
            ny = (point.y - bounds.min_y) / bounds.height * (nmap.height - 1)

            # Get noise value (normalize from [-1,1] to [0,1])
            noise_value = (nmap.get_value(nx, ny) + 1.0) / 2.0

            # Apply threshold
            if noise_value >= self._noise_threshold:
                # Use noise as weight if density varies
                weight = noise_value if self._density_from_noise else 1.0

                # Probability of keeping based on density
                if self._density_from_noise:
                    if self._random.next_float() > noise_value:
                        continue

                points.append(self._create_point(point.x, point.y, weight))

        return points


class ScatterSystem:
    """
    High-level scatter system that coordinates scatter generation.

    Provides filtering and composition of scatter patterns.
    """

    def __init__(self, settings: Optional[ScatterSettings] = None) -> None:
        """
        Initialize scatter system.

        Args:
            settings: Default scatter settings
        """
        self._settings = settings or ScatterSettings()
        self._generators = {
            ScatterPattern.RANDOM: RandomScatter,
            ScatterPattern.POISSON_DISK: PoissonDiskScatter,
            ScatterPattern.GRID: GridScatter,
            ScatterPattern.JITTERED_GRID: JitteredGridScatter,
            ScatterPattern.CLUSTERED: ClusteredScatter,
            ScatterPattern.ORGANIC: OrganicScatter,
        }

    @property
    def settings(self) -> ScatterSettings:
        """Get the system settings."""
        return self._settings

    def generate(
        self,
        bounds: Bounds,
        pattern: Optional[ScatterPattern] = None,
        settings: Optional[ScatterSettings] = None,
    ) -> List[ScatterPoint]:
        """
        Generate scatter points using specified or default pattern.

        Args:
            bounds: Rectangular bounds for placement
            pattern: Pattern to use (uses settings.pattern if None)
            settings: Override settings (uses system settings if None)

        Returns:
            List of scatter points
        """
        s = settings or self._settings
        p = pattern or s.pattern

        gen_class = self._generators.get(p, PoissonDiskScatter)
        generator = gen_class(s)

        return generator.generate(bounds)

    def filter_points(
        self,
        points: List[ScatterPoint],
        filter_func: Callable[[ScatterPoint], bool],
    ) -> List[ScatterPoint]:
        """
        Filter scatter points using a predicate function.

        Args:
            points: Points to filter
            filter_func: Predicate returning True to keep point

        Returns:
            Filtered list of points
        """
        return [p for p in points if filter_func(p)]

    def filter_by_bounds(
        self, points: List[ScatterPoint], bounds: Bounds
    ) -> List[ScatterPoint]:
        """
        Filter points to those within bounds.

        Args:
            points: Points to filter
            bounds: Bounds to check

        Returns:
            Points within bounds
        """
        return self.filter_points(
            points, lambda p: bounds.contains(p.x, p.y)
        )

    def filter_by_weight(
        self,
        points: List[ScatterPoint],
        min_weight: float = 0.0,
        max_weight: float = 1.0,
    ) -> List[ScatterPoint]:
        """
        Filter points by weight range.

        Args:
            points: Points to filter
            min_weight: Minimum weight (inclusive)
            max_weight: Maximum weight (inclusive)

        Returns:
            Points within weight range
        """
        return self.filter_points(
            points, lambda p: min_weight <= p.weight <= max_weight
        )

    def merge_points(
        self, *point_lists: List[ScatterPoint]
    ) -> List[ScatterPoint]:
        """
        Merge multiple lists of scatter points.

        Args:
            *point_lists: Variable number of point lists

        Returns:
            Combined list of points
        """
        result: List[ScatterPoint] = []
        for points in point_lists:
            result.extend(points)
        return result

    def remove_overlapping(
        self,
        points: List[ScatterPoint],
        min_distance: float,
    ) -> List[ScatterPoint]:
        """
        Remove overlapping points (keeps first occurrence).

        Args:
            points: Points to process
            min_distance: Minimum allowed distance

        Returns:
            Points with overlapping removed
        """
        result: List[ScatterPoint] = []
        min_dist_sq = min_distance * min_distance

        for point in points:
            is_valid = True
            for existing in result:
                dist_sq = (point.x - existing.x) ** 2 + (point.y - existing.y) ** 2
                if dist_sq < min_dist_sq:
                    is_valid = False
                    break

            if is_valid:
                result.append(point)

        return result


__all__ = [
    "ScatterPattern",
    "ScatterSettings",
    "ScatterPoint",
    "Bounds",
    "DeterministicRandom",
    "ScatterGenerator",
    "RandomScatter",
    "PoissonDiskScatter",
    "GridScatter",
    "JitteredGridScatter",
    "ClusteredScatter",
    "OrganicScatter",
    "ScatterSystem",
]
