"""
Economy System.

Provides inventory, crafting, loot, equipment, and currency systems.

Foundation Integration (T-GP-8.13):
- @recipe decorator registers with Foundation Registry
- @crafting_station decorator registers stations
- @ingredient and @economy decorators for metadata
- Runtime discovery via Registry.query(tag="recipe")
"""

from .constants import (
    AttributeType,
    ContainerType,
    CraftingQuality,
    CURRENCY_DENOMINATIONS,
    DEFAULT_CONTAINER_SLOTS,
    DEFAULT_MAX_DURABILITY,
    DEFAULT_MAX_LEVEL,
    DEFAULT_MAX_VALUE,
    DEFAULT_MIN_LEVEL,
    DEFAULT_STACK_LIMITS,
    DEFAULT_WEIGHT_LIMITS,
    EconomyEvent,
    EquipmentSlot,
    EXCLUSIVE_SLOTS,
    ItemType,
    LUCK_BONUS_PER_POINT,
    MAX_GOLD,
    MAX_LUCK_BONUS,
    MAX_PREMIUM_CURRENCY,
    MAX_RESISTANCE_PERCENT,
    MAX_STACK_SIZE,
    PITY_INCREMENT,
    PITY_RESET_ON_SUCCESS,
    PITY_WEIGHT_BOOST,
    QUALITY_BASE_CHANCES,
    QUALITY_STAT_MULTIPLIERS,
    Rarity,
    RARITY_COLORS,
    RARITY_DROP_WEIGHTS,
    RARITY_NAMES,
    RARITY_PITY_THRESHOLDS,
    ResistanceType,
    SELLABLE_TYPES,
    SKILL_QUALITY_BONUS_PER_LEVEL,
    STACKABLE_TYPES,
    TRADE_MAX_DISTANCE,
    TRADE_TIMEOUT,
    TradeState,
    UPGRADE_BONUS_PER_LEVEL,
    WEIGHT_UNIT,
)

from .inventory import (
    ECONOMY_SCHEMA_VERSION,
    InventoryContainer,
    InventorySlot,
    ItemDefinition,
    ItemInstance,
)

from .crafting import (
    # Core classes
    CraftingContext,
    CraftingQueueEntry,
    CraftingRegistry,
    CraftingResult,
    CraftingResultType,
    CraftingStation,
    CraftingSystem,
    Ingredient,
    IngredientCategory,
    IngredientRequirement,
    Recipe,
    RecipeBuilder,
    RecipeOutput,
    SkillRequirement,
    # Foundation Registry decorators (T-GP-8.13)
    recipe,
    crafting_station,
    ingredient,
    economy,
    crafting,
    # Factory methods
    RecipeFactory,
    # Helper functions
    get_registered_recipes,
    get_registered_stations,
    get_recipes_for_station_from_registry,
    get_recipes_by_skill_from_registry,
    get_craftable_items,
    get_economy_classes,
    # Utilities
    ingredient_from_dict,
    serializable,
)

from .equipment import (
    EquipmentContainer,
    EquipmentDefinition,
    EquipmentInstance,
    EquipmentRegistry,
    EquipmentSet,
    EquipmentStats,
    ResistanceModifier,
    SetBonus,
    SpecialEffect,
    StatModifier,
)

from .loot import (
    CurrencyDrop,
    CurrencyEntry,
    LootDrop,
    LootEntry,
    LootResult,
    LootRoller,
    LootTable,
    LootTableBuilder,
    LootTableRegistry,
    NestedTableEntry,
    PityTracker,
)

__all__ = [
    # Constants
    "AttributeType",
    "ContainerType",
    "CraftingQuality",
    "CURRENCY_DENOMINATIONS",
    "DEFAULT_CONTAINER_SLOTS",
    "DEFAULT_MAX_DURABILITY",
    "DEFAULT_MAX_LEVEL",
    "DEFAULT_MAX_VALUE",
    "DEFAULT_MIN_LEVEL",
    "DEFAULT_STACK_LIMITS",
    "DEFAULT_WEIGHT_LIMITS",
    "EconomyEvent",
    "EquipmentSlot",
    "EXCLUSIVE_SLOTS",
    "ItemType",
    "LUCK_BONUS_PER_POINT",
    "MAX_GOLD",
    "MAX_LUCK_BONUS",
    "MAX_PREMIUM_CURRENCY",
    "MAX_RESISTANCE_PERCENT",
    "MAX_STACK_SIZE",
    "PITY_INCREMENT",
    "PITY_RESET_ON_SUCCESS",
    "PITY_WEIGHT_BOOST",
    "QUALITY_BASE_CHANCES",
    "QUALITY_STAT_MULTIPLIERS",
    "Rarity",
    "RARITY_COLORS",
    "RARITY_DROP_WEIGHTS",
    "RARITY_NAMES",
    "RARITY_PITY_THRESHOLDS",
    "ResistanceType",
    "SELLABLE_TYPES",
    "SKILL_QUALITY_BONUS_PER_LEVEL",
    "STACKABLE_TYPES",
    "TRADE_MAX_DISTANCE",
    "TRADE_TIMEOUT",
    "TradeState",
    "UPGRADE_BONUS_PER_LEVEL",
    "WEIGHT_UNIT",
    # Inventory
    "ECONOMY_SCHEMA_VERSION",
    "InventoryContainer",
    "InventorySlot",
    "ItemDefinition",
    "ItemInstance",
    # Crafting core
    "CraftingContext",
    "CraftingQueueEntry",
    "CraftingRegistry",
    "CraftingResult",
    "CraftingResultType",
    "CraftingStation",
    "CraftingSystem",
    "Ingredient",
    "IngredientCategory",
    "IngredientRequirement",
    "Recipe",
    "RecipeBuilder",
    "RecipeOutput",
    "SkillRequirement",
    # Foundation Registry decorators (T-GP-8.13)
    "recipe",
    "crafting_station",
    "ingredient",
    "economy",
    "crafting",
    # Factory methods
    "RecipeFactory",
    # Helper functions
    "get_registered_recipes",
    "get_registered_stations",
    "get_recipes_for_station_from_registry",
    "get_recipes_by_skill_from_registry",
    "get_craftable_items",
    "get_economy_classes",
    # Utilities
    "ingredient_from_dict",
    "serializable",
    # Equipment
    "EquipmentContainer",
    "EquipmentDefinition",
    "EquipmentInstance",
    "EquipmentRegistry",
    "EquipmentSet",
    "EquipmentStats",
    "ResistanceModifier",
    "SetBonus",
    "SpecialEffect",
    "StatModifier",
    # Loot
    "CurrencyDrop",
    "CurrencyEntry",
    "LootDrop",
    "LootEntry",
    "LootResult",
    "LootRoller",
    "LootTable",
    "LootTableBuilder",
    "LootTableRegistry",
    "NestedTableEntry",
    "PityTracker",
]
