"""Test fixture for integration testing.

This file contains Trinity ECS definitions that can be parsed
and re-generated by the FlowForge backend.
"""

from trinity_ecs import component, system, resource, event, Query


@component
class Position:
    """2D position component."""
    x: float = 0.0
    y: float = 0.0


@component
class Velocity:
    """2D velocity component."""
    dx: float = 0.0
    dy: float = 0.0


@component
class Health:
    """Health component for damageable entities."""
    current: int = 100
    maximum: int = 100


@resource
class GameConfig:
    """Global game configuration resource."""
    difficulty: int = 1
    debug_mode: bool = False


@event
class PlayerDied:
    """Event emitted when a player dies."""
    player_id: str
    cause: str


@system
class MovementSystem:
    """System that updates entity positions based on velocity."""

    def update(self, entities: Query[Position, Velocity]) -> None:
        """Update positions for all moving entities."""
        pass


@system
class DamageSystem:
    """System that processes damage and health."""

    def on_damage(self, entities: Query[Health]) -> None:
        """Process damage events."""
        pass
