// SPDX-License-Identifier: MIT
//
// noise_domain_warp.wgsl -- Domain warped FBM noise 2D/3D.
//
// T-DEMO-1.33: FBM-warped FBM with increased visual complexity.
// Acceptance: FBM noise domain warped by another FBM noise field for
// swirling, organic deformation patterns. Increased visual complexity
// through non-linear coordinate deformation.
//
// Domain warping transforms the input coordinates of an FBM evaluation
// using a displacement vector generated by another FBM evaluation. This
// creates a feedback-like effect where the noise distorts its own domain,
// producing organic swirling patterns that cannot be achieved by standard
// FBM alone.
//
// The warp displacement at point p is:
//   warp_vec = warp_strength * fbm_warp(p + seed_offset)
//
// where fbm_warp is an FBM noise evaluation with (optionally) its own
// spectral parameters (warp_octaves, warp_lacunarity, warp_gain). The
// seed offset ensures each component of the warp vector is decorrelated.
//
// The final noise value is:
//   result = fbm_base(p + warp_vec, base_octaves, base_lacunarity, base_gain)
//
// Properties:
//   - Deterministic: same input + parameters always produces same output
//   - Organic: warping creates non-linear, swirling deformation patterns
//   - Increased complexity: single FBM evaluation produces richer detail
//   - Configurable warp: separate spectral control for warp vs base FBM
//   - Range: output is approximately in [-1, 1] (inherited from FBM base)
//   - 2D/3D: works in 2D and 3D with value-noise-based FBM base
//   - Perlin variant: uses gradient-based Perlin FBM for smoother warp
//
// Dependencies:
//   - noise_hash.wgsl (hash11, hash21, hash31 from T-DEMO-1.28)
//   - noise_value.wgsl (value_noise_1d, value_noise_2d, value_noise_3d from T-DEMO-1.29)
//   - noise_perlin.wgsl (perlin_noise_3d from T-DEMO-1.30)
//   - noise_fbm.wgsl (fbm_1d, fbm_2d, fbm_3d, fbm_perlin_3d from T-DEMO-1.31)
//
// Reference: Inigo Quilez -- Domain Warping
// https://iquilezles.org/articles/warp/

// =============================================================================
// T-DEMO-1.33: Domain Warp 2D (Value Noise FBM Base)
// =============================================================================

/// 2D domain-warped FBM noise using value-noise-based FBM for both the
/// warp displacement and the base signal.
///
/// Generates a 2D warp vector from two decorrelated FBM evaluations, then
/// evaluates the base FBM at the warped position. The warp strength controls
/// the magnitude of the deformation; higher values produce more turbulent,
/// organic patterns.
///
///   p               -- 2D input coordinate
///   strength        -- warp displacement magnitude
///   warp_octaves    -- number of FBM octaves for the warp field
///   warp_lacunarity -- frequency multiplier for warp octaves
///   warp_gain       -- amplitude multiplier for warp octaves
///   base_octaves    -- number of FBM octaves for the base signal
///   base_lacunarity -- frequency multiplier for base octaves
///   base_gain       -- amplitude multiplier for base octaves
///   returns         -- domain-warped FBM noise, approximately in [-1, 1]
fn domain_warp_2d(
    p: vec2<f32>,
    strength: f32,
    warp_octaves: u32,
    warp_lacunarity: f32,
    warp_gain: f32,
    base_octaves: u32,
    base_lacunarity: f32,
    base_gain: f32
) -> f32 {
    // Generate warp displacement vector from two decorrelated FBM evaluations.
    // The 100.0 offset decorrelates the x and y warp components.
    let warp_x = fbm_2d(p, warp_octaves, warp_lacunarity, warp_gain);
    let warp_y = fbm_2d(
        p + vec2<f32>(100.0, 100.0),
        warp_octaves,
        warp_lacunarity,
        warp_gain
    );

    // Warp the input coordinate by the displacement vector
    let warped_p = p + strength * vec2<f32>(warp_x, warp_y);

    // Evaluate base FBM at the warped position
    return fbm_2d(warped_p, base_octaves, base_lacunarity, base_gain);
}

// =============================================================================
// T-DEMO-1.33: Domain Warp 3D (Value Noise FBM Base)
// =============================================================================

/// 3D domain-warped FBM noise using value-noise-based FBM for both the
/// warp displacement and the base signal.
///
/// Generates a 3D warp vector from three decorrelated FBM evaluations,
/// then evaluates the base FBM at the warped position. The additional
/// dimension enables volumetric swirling deformation for 3D scenes and
/// animated effects.
///
///   p               -- 3D input coordinate
///   strength        -- warp displacement magnitude
///   warp_octaves    -- number of FBM octaves for the warp field
///   warp_lacunarity -- frequency multiplier for warp octaves
///   warp_gain       -- amplitude multiplier for warp octaves
///   base_octaves    -- number of FBM octaves for the base signal
///   base_lacunarity -- frequency multiplier for base octaves
///   base_gain       -- amplitude multiplier for base octaves
///   returns         -- domain-warped FBM noise, approximately in [-1, 1]
fn domain_warp_3d(
    p: vec3<f32>,
    strength: f32,
    warp_octaves: u32,
    warp_lacunarity: f32,
    warp_gain: f32,
    base_octaves: u32,
    base_lacunarity: f32,
    base_gain: f32
) -> f32 {
    // Generate warp displacement vector from three decorrelated FBM evaluations.
    // Distinct offsets decorrelate the x, y, and z warp components.
    let warp_x = fbm_3d(p, warp_octaves, warp_lacunarity, warp_gain);
    let warp_y = fbm_3d(
        p + vec3<f32>(100.0, 100.0, 100.0),
        warp_octaves,
        warp_lacunarity,
        warp_gain
    );
    let warp_z = fbm_3d(
        p + vec3<f32>(200.0, 200.0, 200.0),
        warp_octaves,
        warp_lacunarity,
        warp_gain
    );

    // Warp the input coordinate by the displacement vector
    let warped_p = p + strength * vec3<f32>(warp_x, warp_y, warp_z);

    // Evaluate base FBM at the warped position
    return fbm_3d(warped_p, base_octaves, base_lacunarity, base_gain);
}

// =============================================================================
// T-DEMO-1.33: Domain Warp 3D (Perlin Noise FBM Base)
// =============================================================================

/// 3D domain-warped FBM noise using Perlin-noise-based FBM for both the
/// warp displacement and the base signal.
///
/// Uses Perlin-based FBM (gradient noise) for both the warp field and the
/// base evaluation. The gradient-based approach produces visually smoother
/// warp fields with fewer grid artifacts, creating more organic swirling
/// patterns suitable for volumetric and cinematic effects.
///
///   p               -- 3D input coordinate
///   strength        -- warp displacement magnitude
///   warp_octaves    -- number of FBM octaves for the warp field
///   warp_lacunarity -- frequency multiplier for warp octaves
///   warp_gain       -- amplitude multiplier for warp octaves
///   base_octaves    -- number of FBM octaves for the base signal
///   base_lacunarity -- frequency multiplier for base octaves
///   base_gain       -- amplitude multiplier for base octaves
///   returns         -- domain-warped Perlin FBM, approximately in [-1, 1]
fn domain_warp_perlin_3d(
    p: vec3<f32>,
    strength: f32,
    warp_octaves: u32,
    warp_lacunarity: f32,
    warp_gain: f32,
    base_octaves: u32,
    base_lacunarity: f32,
    base_gain: f32
) -> f32 {
    // Generate warp displacement vector from three decorrelated Perlin FBM
    // evaluations. Distinct offsets decorrelate the components.
    let warp_x = fbm_perlin_3d(p, warp_octaves, warp_lacunarity, warp_gain);
    let warp_y = fbm_perlin_3d(
        p + vec3<f32>(100.0, 100.0, 100.0),
        warp_octaves,
        warp_lacunarity,
        warp_gain
    );
    let warp_z = fbm_perlin_3d(
        p + vec3<f32>(200.0, 200.0, 200.0),
        warp_octaves,
        warp_lacunarity,
        warp_gain
    );

    // Warp the input coordinate by the displacement vector
    let warped_p = p + strength * vec3<f32>(warp_x, warp_y, warp_z);

    // Evaluate base Perlin FBM at the warped position
    return fbm_perlin_3d(warped_p, base_octaves, base_lacunarity, base_gain);
}
