"""Global illumination utilities for TRINITY renderer.

This package provides:
- Spherical harmonics math (sh_math)
- GI performance budget configuration (gi_config)
- Irradiance volume system (irradiance_volumes)
- Adaptive DDGI prototype (adaptive_ddgi) [T-GIR-P11.1]
- SSGI temporal accumulation (ssgi_temporal) [T-GIR-P3.2]
- Scene voxelization (voxelization) [T-GIR-P7.1]
- DDGI RT probe ray tracing (ddgi_rt_probes) [T-GIR-P2.2]
- Voxel mip chain and storage (voxel_mipchain) [T-GIR-P7.2]
- DDGI probe update system (ddgi_probe_update) [T-GIR-P2.4]
- Radiance cache system (radiance_cache) [T-GIR-P2.7]
- DDGI integration utilities
- Lumen-Lite feasibility study (lumen_lite_study) [T-GIR-P11.3]
"""

from engine.rendering.gi.sh_math import (
    SH_Y00,
    SH_Y1,
    SH_Y2_NEG2,
    SH_Y2_NEG1,
    SH_Y2_0,
    SH_Y2_POS1,
    SH_Y2_POS2,
    SH_A0,
    SH_A1,
    SH_A2,
    sh_basis_l2,
    sh_evaluate_l2,
    sh_project_l2,
    sh_convolve_irradiance,
    sh_rotate_l2,
    fibonacci_sphere_directions,
    SHCoefficientsL2,
)

from engine.rendering.gi.gi_config import (
    GIQualityTier,
    GIBudget,
    GIBudgetMonitor,
    GPUTimestamp,
    GITimingInstrument,
    LOW_BUDGET,
    MEDIUM_BUDGET,
    HIGH_BUDGET,
    ULTRA_BUDGET,
    CINEMATIC_BUDGET,
    BUDGETS_BY_TIER,
    get_budget,
    recommend_tier_for_target_fps,
    estimate_probe_update_cost,
)

from engine.rendering.gi.irradiance_volumes import (
    VolumeType,
    VolumeState,
    VolumeTransition,
    IrradianceVolume,
    IrradianceVolumeManager,
    VolumeGpuData,
    recommend_max_volumes,
    estimate_volume_memory,
    generate_volume_sampling_wgsl,
)

from engine.rendering.gi.adaptive_ddgi import (
    AdaptiveDDGIConfig,
    AdaptiveProbeState,
    AdaptiveProbe,
    AdaptiveProbeNode,
    AdaptiveProbeGrid,
    visualize_octree_bounds,
    visualize_variance_heatmap,
    visualize_probe_density,
    create_indoor_corridor_sampler,
    create_outdoor_terrain_sampler,
    create_mixed_scene_sampler,
)

from engine.rendering.gi.voxelization import (
    # Constants
    RESOLUTION_64,
    RESOLUTION_128,
    RESOLUTION_256,
    SUPPORTED_RESOLUTIONS,
    # Enums
    VoxelResolution,
    OpacityClass,
    VoxelAxis,
    # Data structures
    Triangle,
    Voxel,
    # Grid
    VoxelGrid,
    # Rasterizer
    ConservativeRasterizer,
    # Voxelizer
    VoxelizationStats,
    VoxelizationConfig,
    SceneVoxelizer,
    # Utilities
    create_test_triangles,
    estimate_voxelization_memory,
    recommend_resolution,
    generate_voxelize_compute_wgsl,
)

from engine.rendering.gi.ssgi_temporal import (
    # Constants
    DEFAULT_BLEND_FACTOR,
    DEFAULT_VELOCITY_THRESHOLD,
    DEFAULT_CLAMP_EXPAND,
    # Enums
    ClampMode,
    ResetCondition,
    # Config
    TemporalConfig,
    # Statistics
    NeighbourhoodStats,
    compute_neighbourhood_stats,
    # Clamping
    clamp_color,
    clip_color_to_aabb,
    # Reprojection
    reproject_uv,
    velocity_magnitude,
    is_valid_uv,
    # History
    TemporalHistory,
    TemporalUniforms,
    # Main class
    SSGITemporalAccumulator,
    # Blend computation
    compute_temporal_blend,
    compute_luminance,
    compute_luminance_weight,
    # Variance
    VarianceTracker,
    # Presets
    create_low_quality_config,
    create_medium_quality_config,
    create_high_quality_config,
)

from engine.rendering.gi.voxel_mipchain import (
    # Constants
    MIN_VOXEL_RESOLUTION,
    MAX_VOXEL_RESOLUTION,
    VOXEL_FORMAT_BYTES_PER_TEXEL,
    VARIANCE_START_MIP,
    MIN_VARIANCE_THRESHOLD,
    # Enums
    MipResolution,
    VoxelStorageFormat,
    # Data structures
    VoxelData,
    VoxelMipLevel,
    VoxelDownsampleConfig,
    VoxelMipChain,
    VoxelStorageConfig,
    VoxelStorage,
    # Functions
    downsample_voxels,
    compute_mip_resolution,
    compute_mip_count,
    estimate_voxel_memory,
    create_test_voxel_pattern,
    validate_mip_chain,
    generate_voxel_downsample_wgsl,
    generate_voxel_sample_wgsl,
)

from engine.rendering.gi.ddgi_rt_probes import (
    # Constants
    MIN_RAYS_PER_PROBE,
    MAX_RAYS_PER_PROBE,
    DEFAULT_RAYS_PER_PROBE,
    GOLDEN_RATIO,
    GOLDEN_ANGLE,
    RAY_FLAG_NONE,
    RAY_FLAG_CULL_BACK_FACING,
    RAY_FLAG_CULL_FRONT_FACING,
    RAY_FLAG_TERMINATE_ON_FIRST_HIT,
    RAY_FLAG_SKIP_CLOSEST_HIT,
    DEFAULT_HYSTERESIS,
    DEFAULT_MAX_RAY_DISTANCE,
    # Enums
    RayDistribution,
    # Config
    ProbeRayConfig,
    # Ray generator
    ProbeRayGenerator,
    # Hit result
    RayHitResult,
    # Accumulator
    AccumulatedRadiance,
    RadianceAccumulator,
    # TLAS interface
    TLASInterface,
    # Main updater
    DDGIRTUpdateConfig,
    ProbeUpdateResult,
    DDGIRTProbeUpdater,
    # WGSL generation
    generate_ddgi_probe_update_wgsl,
    # Utilities
    create_mock_tlas,
    estimate_memory_usage,
)

from engine.rendering.gi.ddgi_probe_update import (
    # Constants
    DEFAULT_IRRADIANCE_BLEND,
    DEFAULT_VISIBILITY_BLEND,
    DEFAULT_GAUSSIAN_SIGMA,
    DEFAULT_CONFIDENCE_THRESHOLD,
    IMPORTANCE_CRITICAL,
    IMPORTANCE_HIGH,
    IMPORTANCE_MEDIUM,
    IMPORTANCE_LOW,
    VISIBILITY_MAX_DISTANCE,
    VISIBILITY_MISS_DISTANCE,
    # Data structures
    ProbeRayHit,
    DistanceWeightConfig,
    ProbeData,
    ProbeUpdateState,
    # Configs
    IrradianceAccumulatorConfig,
    VisibilityStorageConfig,
    TemporalAccumulatorConfig,
    ImportanceSchedulerConfig,
    DDGIProbeUpdaterConfig,
    # Enums
    ProbeImportance,
    # Core classes
    IrradianceAccumulator,
    VisibilityStorage,
    TemporalAccumulator,
    ImportanceScheduler,
    DDGIProbeUpdater,
    # Utilities
    compute_distance_statistics,
    create_test_ray_hits,
    estimate_update_cost,
)

from engine.rendering.gi.radiance_cache import (
    # Constants
    DEFAULT_GRID_WIDTH,
    DEFAULT_GRID_HEIGHT,
    DEFAULT_GRID_DEPTH,
    DEFAULT_HYSTERESIS_FRAMES,
    DEFAULT_VARIANCE_THRESHOLD,
    SH_L1_COEFFICIENTS,
    GPU_ALIGNMENT,
    # Enums
    CacheUpdateMode,
    CacheQuality,
    CellState,
    # Config
    RadianceCacheConfig,
    # Data structures
    CacheCell,
    CacheGrid,
    # Main class
    RadianceCache,
    RadianceCacheUpdater,
    # Utilities
    estimate_cache_memory,
    recommend_cache_quality,
    create_constant_probe_sampler,
    create_gradient_probe_sampler,
    generate_radiance_cache_sampling_wgsl,
)

from engine.rendering.gi.voxel_cone_trace import (
    # Constants
    DIFFUSE_APERTURE_MIN,
    DIFFUSE_APERTURE_MAX,
    DIFFUSE_APERTURE_DEFAULT,
    SPECULAR_APERTURE_MIN,
    SPECULAR_APERTURE_MAX,
    MIN_DIFFUSE_CONES,
    MAX_DIFFUSE_CONES,
    DEFAULT_DIFFUSE_CONES,
    MIN_SPECULAR_CONES,
    MAX_SPECULAR_CONES,
    DEFAULT_SPECULAR_CONES,
    DEFAULT_START_OFFSET,
    DEFAULT_MAX_DISTANCE,
    DEFAULT_STEP_MULTIPLIER,
    DEFAULT_OPACITY_THRESHOLD,
    # Config classes
    ConeConfig,
    ConeTracerConfig,
    VoxelGIConfig,
    # Distributions
    DiffuseConeDistribution,
    SpecularConeDistribution,
    # Results
    ConeTraceResult,
    VoxelGIResult,
    # Core classes
    VoxelConeTracer,
    VoxelGIPass,
    # Utilities
    estimate_trace_time_ms,
    create_test_gi_scene,
    generate_voxel_cone_trace_wgsl,
    generate_voxel_cone_trace_compute_wgsl,
)

from engine.rendering.gi.lumen_lite_study import (
    # Enums
    FeasibilityLevel,
    ComponentType,
    DecisionOutcome,
    # Config classes
    MeshCardEvaluatorConfig,
    ScreenProbeEvaluatorConfig,
    SDFEvaluatorConfig,
    # Data structures
    MeshCardCostEstimate,
    ScreenProbeAnalysis,
    SDFEvaluationResult,
    RadianceCacheComparisonResult,
    QualityMetricResult,
    CostBudgetResult,
    ComponentAssessment,
    FeasibilityReport,
    # Core evaluators
    MeshCardEvaluator,
    ScreenProbeEvaluator,
    SDFEvaluator,
    RadianceCacheComparison,
    QualityMetrics,
    CostBudgetAnalyzer,
    FeasibilityAssessment,
    # Convenience functions
    run_feasibility_study,
    quick_assessment,
    # Constants
    PSNR_EXCELLENT,
    PSNR_GOOD,
    PSNR_ACCEPTABLE,
    PSNR_POOR,
)

from engine.rendering.gi.sparse_voxel_octree import (
    # Constants
    OCTREE_CHILDREN,
    MIN_SVO_RESOLUTION,
    DEFAULT_SIMILARITY_THRESHOLD,
    DEFAULT_OPACITY_THRESHOLD as SVO_OPACITY_THRESHOLD,
    DENSE_VOXEL_BYTES,
    GPU_NODE_SIZE,
    # Enums
    NodeType,
    TraversalMode,
    # Data structures
    SVOVoxelData,
    SVONode,
    RayHit,
    ConeTraceResult as SVOConeTraceResult,
    # Configs
    SVOBuildConfig,
    SVOBuildStats,
    SVOCompressionConfig,
    SVOCompressionStats,
    SVOMipConfig,
    SerializedSVO,
    MemoryProfile,
    SceneProfile,
    # Classes
    SVOBuilder,
    SVOCompressor,
    SVOMipGenerator,
    SVOTraversal,
    SVOSerializer,
    MemoryProfiler,
    # Scene generators
    create_empty_room_scene,
    create_furnished_room_scene,
    create_forest_scene,
    # Utilities
    build_svo_from_grid,
    evaluate_svo_compression,
    # WGSL
    generate_svo_traversal_wgsl,
    generate_svo_cone_trace_wgsl,
)

from engine.rendering.gi.gi_debug_visualization import (
    # Debug mode control
    set_debug_mode,
    is_debug_enabled,
    debug,
    register_debug_pass,
    get_registered_debug_passes,
    clear_debug_passes,
    # Constants
    DEFAULT_OVERLAY_OPACITY,
    DEFAULT_DIFFERENCE_THRESHOLD,
    DEFAULT_CONFIDENCE_LOW,
    DEFAULT_CONFIDENCE_HIGH,
    DEFAULT_PROBE_SPHERE_RADIUS,
    DEFAULT_WIREFRAME_LINE_WIDTH,
    DEBUG_WORKGROUP_SIZE,
    PSNR_EXCELLENT as DEBUG_PSNR_EXCELLENT,
    PSNR_GOOD as DEBUG_PSNR_GOOD,
    PSNR_ACCEPTABLE as DEBUG_PSNR_ACCEPTABLE,
    PSNR_POOR as DEBUG_PSNR_POOR,
    # Color utilities
    Color,
    COLOR_RED,
    COLOR_GREEN,
    COLOR_BLUE,
    COLOR_YELLOW,
    COLOR_CYAN,
    COLOR_MAGENTA,
    COLOR_WHITE,
    COLOR_BLACK,
    COLOR_GRAY,
    COLOR_ORANGE,
    create_heatmap_gradient,
    sample_gradient,
    # Enums
    ProbeColorMode,
    ProbeState as DebugProbeState,
    ReflectionTechnique,
    VoxelSliceAxis,
    HeatmapColorScale,
    # Config
    GIDebugConfig,
    # Data structures
    ProbeVisualizationData,
    VoxelData as DebugVoxelData,
    ConfidencePixel,
    DifferencePixel,
    ComparisonStats,
    ReflectionPixel,
    # Visualization classes
    ProbeGridVisualization,
    VoxelOccupancyVisualization,
    SSGIConfidenceHeatmap,
    PathTracerComparisonHeatmap,
    ReflectionTechniqueMask,
    GIDebugOverlay,
    # WGSL generation
    generate_debug_overlay_wgsl,
    generate_probe_billboard_wgsl,
    generate_voxel_wireframe_wgsl,
    # Utilities
    estimate_debug_memory,
    create_test_probes,
    create_test_voxels as create_debug_test_voxels,
)

__all__ = [
    # SH Math
    "SH_Y00",
    "SH_Y1",
    "SH_Y2_NEG2",
    "SH_Y2_NEG1",
    "SH_Y2_0",
    "SH_Y2_POS1",
    "SH_Y2_POS2",
    "SH_A0",
    "SH_A1",
    "SH_A2",
    "sh_basis_l2",
    "sh_evaluate_l2",
    "sh_project_l2",
    "sh_convolve_irradiance",
    "sh_rotate_l2",
    "fibonacci_sphere_directions",
    "SHCoefficientsL2",
    # GI Config
    "GIQualityTier",
    "GIBudget",
    "GIBudgetMonitor",
    "GPUTimestamp",
    "GITimingInstrument",
    "LOW_BUDGET",
    "MEDIUM_BUDGET",
    "HIGH_BUDGET",
    "ULTRA_BUDGET",
    "CINEMATIC_BUDGET",
    "BUDGETS_BY_TIER",
    "get_budget",
    "recommend_tier_for_target_fps",
    "estimate_probe_update_cost",
    # Irradiance Volumes
    "VolumeType",
    "VolumeState",
    "VolumeTransition",
    "IrradianceVolume",
    "IrradianceVolumeManager",
    "VolumeGpuData",
    "recommend_max_volumes",
    "estimate_volume_memory",
    "generate_volume_sampling_wgsl",
    # Adaptive DDGI (T-GIR-P11.1)
    "AdaptiveDDGIConfig",
    "AdaptiveProbeState",
    "AdaptiveProbe",
    "AdaptiveProbeNode",
    "AdaptiveProbeGrid",
    "visualize_octree_bounds",
    "visualize_variance_heatmap",
    "visualize_probe_density",
    "create_indoor_corridor_sampler",
    "create_outdoor_terrain_sampler",
    "create_mixed_scene_sampler",
    # SSGI Temporal (T-GIR-P3.2)
    "DEFAULT_BLEND_FACTOR",
    "DEFAULT_VELOCITY_THRESHOLD",
    "DEFAULT_CLAMP_EXPAND",
    "ClampMode",
    "ResetCondition",
    "TemporalConfig",
    "NeighbourhoodStats",
    "compute_neighbourhood_stats",
    "clamp_color",
    "clip_color_to_aabb",
    "reproject_uv",
    "velocity_magnitude",
    "is_valid_uv",
    "TemporalHistory",
    "TemporalUniforms",
    "SSGITemporalAccumulator",
    "compute_temporal_blend",
    "compute_luminance",
    "compute_luminance_weight",
    "VarianceTracker",
    "create_low_quality_config",
    "create_medium_quality_config",
    "create_high_quality_config",
    # Voxelization (T-GIR-P7.1)
    "RESOLUTION_64",
    "RESOLUTION_128",
    "RESOLUTION_256",
    "SUPPORTED_RESOLUTIONS",
    "VoxelResolution",
    "OpacityClass",
    "VoxelAxis",
    "Triangle",
    "Voxel",
    "VoxelGrid",
    "ConservativeRasterizer",
    "VoxelizationStats",
    "VoxelizationConfig",
    "SceneVoxelizer",
    "create_test_triangles",
    "estimate_voxelization_memory",
    "recommend_resolution",
    "generate_voxelize_compute_wgsl",
    # Voxel Mip Chain (T-GIR-P7.2)
    "MIN_VOXEL_RESOLUTION",
    "MAX_VOXEL_RESOLUTION",
    "VOXEL_FORMAT_BYTES_PER_TEXEL",
    "VARIANCE_START_MIP",
    "MIN_VARIANCE_THRESHOLD",
    "MipResolution",
    "VoxelStorageFormat",
    "VoxelData",
    "VoxelMipLevel",
    "VoxelDownsampleConfig",
    "VoxelMipChain",
    "VoxelStorageConfig",
    "VoxelStorage",
    "downsample_voxels",
    "compute_mip_resolution",
    "compute_mip_count",
    "estimate_voxel_memory",
    "create_test_voxel_pattern",
    "validate_mip_chain",
    "generate_voxel_downsample_wgsl",
    "generate_voxel_sample_wgsl",
    # DDGI RT Probes (T-GIR-P2.2)
    "MIN_RAYS_PER_PROBE",
    "MAX_RAYS_PER_PROBE",
    "DEFAULT_RAYS_PER_PROBE",
    "GOLDEN_RATIO",
    "GOLDEN_ANGLE",
    "RAY_FLAG_NONE",
    "RAY_FLAG_CULL_BACK_FACING",
    "RAY_FLAG_CULL_FRONT_FACING",
    "RAY_FLAG_TERMINATE_ON_FIRST_HIT",
    "RAY_FLAG_SKIP_CLOSEST_HIT",
    "DEFAULT_HYSTERESIS",
    "DEFAULT_MAX_RAY_DISTANCE",
    "RayDistribution",
    "ProbeRayConfig",
    "ProbeRayGenerator",
    "RayHitResult",
    "AccumulatedRadiance",
    "RadianceAccumulator",
    "TLASInterface",
    "DDGIRTUpdateConfig",
    "ProbeUpdateResult",
    "DDGIRTProbeUpdater",
    "generate_ddgi_probe_update_wgsl",
    "create_mock_tlas",
    "estimate_memory_usage",
    # DDGI Probe Update (T-GIR-P2.4)
    "DEFAULT_IRRADIANCE_BLEND",
    "DEFAULT_VISIBILITY_BLEND",
    "DEFAULT_GAUSSIAN_SIGMA",
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "IMPORTANCE_CRITICAL",
    "IMPORTANCE_HIGH",
    "IMPORTANCE_MEDIUM",
    "IMPORTANCE_LOW",
    "VISIBILITY_MAX_DISTANCE",
    "VISIBILITY_MISS_DISTANCE",
    "ProbeRayHit",
    "DistanceWeightConfig",
    "ProbeData",
    "ProbeUpdateState",
    "IrradianceAccumulatorConfig",
    "VisibilityStorageConfig",
    "TemporalAccumulatorConfig",
    "ImportanceSchedulerConfig",
    "DDGIProbeUpdaterConfig",
    "ProbeImportance",
    "IrradianceAccumulator",
    "VisibilityStorage",
    "TemporalAccumulator",
    "ImportanceScheduler",
    "DDGIProbeUpdater",
    "compute_distance_statistics",
    "create_test_ray_hits",
    "estimate_update_cost",
    # Radiance Cache (T-GIR-P2.7)
    "DEFAULT_GRID_WIDTH",
    "DEFAULT_GRID_HEIGHT",
    "DEFAULT_GRID_DEPTH",
    "DEFAULT_HYSTERESIS_FRAMES",
    "DEFAULT_VARIANCE_THRESHOLD",
    "SH_L1_COEFFICIENTS",
    "GPU_ALIGNMENT",
    "CacheUpdateMode",
    "CacheQuality",
    "CellState",
    "RadianceCacheConfig",
    "CacheCell",
    "CacheGrid",
    "RadianceCache",
    "RadianceCacheUpdater",
    "estimate_cache_memory",
    "recommend_cache_quality",
    "create_constant_probe_sampler",
    "create_gradient_probe_sampler",
    "generate_radiance_cache_sampling_wgsl",
    # Voxel Cone Tracing (T-GIR-P7.3)
    "DIFFUSE_APERTURE_MIN",
    "DIFFUSE_APERTURE_MAX",
    "DIFFUSE_APERTURE_DEFAULT",
    "SPECULAR_APERTURE_MIN",
    "SPECULAR_APERTURE_MAX",
    "MIN_DIFFUSE_CONES",
    "MAX_DIFFUSE_CONES",
    "DEFAULT_DIFFUSE_CONES",
    "MIN_SPECULAR_CONES",
    "MAX_SPECULAR_CONES",
    "DEFAULT_SPECULAR_CONES",
    "DEFAULT_START_OFFSET",
    "DEFAULT_MAX_DISTANCE",
    "DEFAULT_STEP_MULTIPLIER",
    "DEFAULT_OPACITY_THRESHOLD",
    "ConeConfig",
    "ConeTracerConfig",
    "VoxelGIConfig",
    "DiffuseConeDistribution",
    "SpecularConeDistribution",
    "ConeTraceResult",
    "VoxelGIResult",
    "VoxelConeTracer",
    "VoxelGIPass",
    "estimate_trace_time_ms",
    "create_test_gi_scene",
    "generate_voxel_cone_trace_wgsl",
    "generate_voxel_cone_trace_compute_wgsl",
    # Sparse Voxel Octree (T-GIR-P11.2)
    "OCTREE_CHILDREN",
    "MIN_SVO_RESOLUTION",
    "DEFAULT_SIMILARITY_THRESHOLD",
    "SVO_OPACITY_THRESHOLD",
    "DENSE_VOXEL_BYTES",
    "GPU_NODE_SIZE",
    "NodeType",
    "TraversalMode",
    "SVOVoxelData",
    "SVONode",
    "RayHit",
    "SVOConeTraceResult",
    "SVOBuildConfig",
    "SVOBuildStats",
    "SVOCompressionConfig",
    "SVOCompressionStats",
    "SVOMipConfig",
    "SerializedSVO",
    "MemoryProfile",
    "SceneProfile",
    "SVOBuilder",
    "SVOCompressor",
    "SVOMipGenerator",
    "SVOTraversal",
    "SVOSerializer",
    "MemoryProfiler",
    "create_empty_room_scene",
    "create_furnished_room_scene",
    "create_forest_scene",
    "build_svo_from_grid",
    "evaluate_svo_compression",
    "generate_svo_traversal_wgsl",
    "generate_svo_cone_trace_wgsl",
    # Lumen-Lite Feasibility Study (T-GIR-P11.3)
    "FeasibilityLevel",
    "ComponentType",
    "DecisionOutcome",
    "MeshCardEvaluatorConfig",
    "ScreenProbeEvaluatorConfig",
    "SDFEvaluatorConfig",
    "MeshCardCostEstimate",
    "ScreenProbeAnalysis",
    "SDFEvaluationResult",
    "RadianceCacheComparisonResult",
    "QualityMetricResult",
    "CostBudgetResult",
    "ComponentAssessment",
    "FeasibilityReport",
    "MeshCardEvaluator",
    "ScreenProbeEvaluator",
    "SDFEvaluator",
    "RadianceCacheComparison",
    "QualityMetrics",
    "CostBudgetAnalyzer",
    "FeasibilityAssessment",
    "run_feasibility_study",
    "quick_assessment",
    "PSNR_EXCELLENT",
    "PSNR_GOOD",
    "PSNR_ACCEPTABLE",
    "PSNR_POOR",
    # GI Debug Visualization (T-GIR-P10.1)
    "set_debug_mode",
    "is_debug_enabled",
    "debug",
    "register_debug_pass",
    "get_registered_debug_passes",
    "clear_debug_passes",
    "DEFAULT_OVERLAY_OPACITY",
    "DEFAULT_DIFFERENCE_THRESHOLD",
    "DEFAULT_CONFIDENCE_LOW",
    "DEFAULT_CONFIDENCE_HIGH",
    "DEFAULT_PROBE_SPHERE_RADIUS",
    "DEFAULT_WIREFRAME_LINE_WIDTH",
    "DEBUG_WORKGROUP_SIZE",
    "DEBUG_PSNR_EXCELLENT",
    "DEBUG_PSNR_GOOD",
    "DEBUG_PSNR_ACCEPTABLE",
    "DEBUG_PSNR_POOR",
    "Color",
    "COLOR_RED",
    "COLOR_GREEN",
    "COLOR_BLUE",
    "COLOR_YELLOW",
    "COLOR_CYAN",
    "COLOR_MAGENTA",
    "COLOR_WHITE",
    "COLOR_BLACK",
    "COLOR_GRAY",
    "COLOR_ORANGE",
    "create_heatmap_gradient",
    "sample_gradient",
    "ProbeColorMode",
    "DebugProbeState",
    "ReflectionTechnique",
    "VoxelSliceAxis",
    "HeatmapColorScale",
    "GIDebugConfig",
    "ProbeVisualizationData",
    "DebugVoxelData",
    "ConfidencePixel",
    "DifferencePixel",
    "ComparisonStats",
    "ReflectionPixel",
    "ProbeGridVisualization",
    "VoxelOccupancyVisualization",
    "SSGIConfidenceHeatmap",
    "PathTracerComparisonHeatmap",
    "ReflectionTechniqueMask",
    "GIDebugOverlay",
    "generate_debug_overlay_wgsl",
    "generate_probe_billboard_wgsl",
    "generate_voxel_wireframe_wgsl",
    "estimate_debug_memory",
    "create_test_probes",
    "create_debug_test_voxels",
]
