#!/usr/bin/env bash
# ============================================================================
# install-hooks.sh — Install git hooks for local CI/CD
# ============================================================================
# Usage:
#   ./install-hooks.sh              # Install hooks in current git repo
#   ./install-hooks.sh /path/to/repo  # Install hooks in specified repo
#
# Installs:
#   .git/hooks/pre-commit  → runs `quick` (fmt + lint)
#   .git/hooks/pre-push    → runs `gate` (fmt + lint + test + build)
#
# Auto-detects Rust (Cargo.toml) and Python (pyproject.toml/setup.py)
# and runs the appropriate pipeline. Supports polyglot repos (runs both).
#
# Skip hooks when needed:
#   git commit --no-verify
#   git push --no-verify
# ============================================================================

set -euo pipefail

REPO="${1:-$(pwd)}"
HOOK_DIR="${REPO}/.git/hooks"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -d "${REPO}/.git" ]; then
    echo "Error: ${REPO} is not a git repository"
    exit 1
fi

# --- Determine where CI scripts live relative to repo -------------------------
# Priority: workflows/ (SDLC_WORKFLOW convention) > ci/ (legacy) > absolute script dir
# Using $(git rev-parse --show-toplevel) keeps hooks portable across repo moves.
if [ -f "${REPO}/workflows/ci-rust.sh" ] || [ -f "${REPO}/workflows/ci-python.sh" ]; then
    CI_DIR='$(git rev-parse --show-toplevel)/workflows'
elif [ -f "${REPO}/ci/ci-rust.sh" ] || [ -f "${REPO}/ci/ci-python.sh" ]; then
    CI_DIR='$(git rev-parse --show-toplevel)/ci'
else
    CI_DIR="${SCRIPT_DIR}"
fi

echo "Installing git hooks to: ${HOOK_DIR}"
echo "CI scripts resolved at:  ${CI_DIR}"
echo ""

# --- pre-commit hook ----------------------------------------------------------
cat > "${HOOK_DIR}/pre-commit" <<'HOOKEOF'
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh — local CI/CD pre-commit hook
# Runs: fmt + lint (quick check)
# Skip with: git commit --no-verify
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKEOF

cat >> "${HOOK_DIR}/pre-commit" <<HOOKEOF
CI_DIR="${CI_DIR}"
HOOKEOF

cat >> "${HOOK_DIR}/pre-commit" <<'HOOKEOF'
FAILED=0

# Only check staged files' languages
if [ -f "${REPO_ROOT}/Cargo.toml" ]; then
    if git diff --cached --name-only | grep -qE '\.(rs|toml)$'; then
        echo "╶╶╶ pre-commit: Rust quick check ╶╶╶"
        if ! bash "${CI_DIR}/ci-rust.sh" quick; then
            FAILED=1
        fi
    fi
fi

if [ -f "${REPO_ROOT}/pyproject.toml" ] || [ -f "${REPO_ROOT}/setup.py" ]; then
    if git diff --cached --name-only | grep -qE '\.py$'; then
        echo "╶╶╶ pre-commit: Python quick check ╶╶╶"
        if ! bash "${CI_DIR}/ci-python.sh" quick; then
            FAILED=1
        fi
    fi
fi

if [ $FAILED -ne 0 ]; then
    echo ""
    echo "Pre-commit checks failed. Fix issues or commit with --no-verify"
    exit 1
fi
HOOKEOF

chmod +x "${HOOK_DIR}/pre-commit"
echo "✓ Installed pre-commit hook (fmt + lint on staged files)"

# --- pre-push hook ------------------------------------------------------------
cat > "${HOOK_DIR}/pre-push" <<'HOOKEOF'
#!/usr/bin/env bash
# Auto-generated by install-hooks.sh — local CI/CD pre-push hook
# Runs: fmt + lint + test + build (full gate)
# Skip with: git push --no-verify
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKEOF

cat >> "${HOOK_DIR}/pre-push" <<HOOKEOF
CI_DIR="${CI_DIR}"
HOOKEOF

cat >> "${HOOK_DIR}/pre-push" <<'HOOKEOF'
FAILED=0

if [ -f "${REPO_ROOT}/Cargo.toml" ]; then
    echo "╶╶╶ pre-push: Rust gate ╶╶╶"
    if ! bash "${CI_DIR}/ci-rust.sh" gate; then
        FAILED=1
    fi
fi

if [ -f "${REPO_ROOT}/pyproject.toml" ] || [ -f "${REPO_ROOT}/setup.py" ]; then
    echo "╶╶╶ pre-push: Python gate ╶╶╶"
    if ! bash "${CI_DIR}/ci-python.sh" gate; then
        FAILED=1
    fi
fi

if [ $FAILED -ne 0 ]; then
    echo ""
    echo "Pre-push gate failed. Fix issues or push with --no-verify"
    exit 1
fi
HOOKEOF

chmod +x "${HOOK_DIR}/pre-push"
echo "✓ Installed pre-push hook (full gate: fmt + lint + test + build)"

echo ""
echo "Done. Hooks installed."
echo ""
echo "  pre-commit → quick (fmt + lint on staged file types)"
echo "  pre-push   → gate  (full pipeline minus release artifact)"
echo ""
echo "  Skip anytime with --no-verify"
echo "  Run manually:  ./ci/ci-rust.sh full"
echo "                 ./ci/ci-python.sh full"
