"""Python source code emitter for code generation.

This module converts Python AST to source code with optional formatting.
It handles the final step of code generation: turning the AST back into
readable, properly formatted Python source code.
"""

from __future__ import annotations

import ast
import sys
from typing import Optional

# Check Python version for ast.unparse availability (3.9+)
_HAS_AST_UNPARSE = hasattr(ast, "unparse")


def _add_blank_lines(source: str) -> str:
    """Add blank lines between class definitions for readability.

    Ensures PEP 8 compliant spacing: two blank lines before each
    top-level class/function definition.

    Args:
        source: The Python source code.

    Returns:
        Source code with proper blank line spacing.
    """
    lines = source.split("\n")
    result: list[str] = []
    prev_was_decorator = False

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Check if this is a decorator
        is_decorator = stripped.startswith("@") and not stripped.startswith("@=")

        # Check if this is a class definition
        is_class = stripped.startswith("class ")

        # Add two blank lines before decorator/class (if not at start and not following a decorator)
        if (is_decorator or is_class) and result and not prev_was_decorator:
            # Remove existing blank lines
            while result and not result[-1].strip():
                result.pop()
            # Add exactly two blank lines (if we have content before)
            if result:
                result.append("")
                result.append("")

        result.append(line)
        prev_was_decorator = is_decorator

    return "\n".join(result)


def _format_with_black(source: str, line_length: int = 88) -> str:
    """Format source code with black if available.

    Args:
        source: The Python source code to format.
        line_length: Maximum line length (default: 88).

    Returns:
        Formatted source code, or original if black is not available.
    """
    try:
        import black
        from black import Mode, format_str

        mode = Mode(
            line_length=line_length,
            string_normalization=True,
            is_pyi=False,
        )
        return format_str(source, mode=mode)
    except ImportError:
        # Black not available, return original
        return source
    except Exception:
        # Black formatting failed, return original
        return source


def emit_python(
    module: ast.Module,
    format_with_black: bool = True,
    line_length: int = 88,
    add_header: bool = True,
    original_source: Optional[str] = None,
) -> str:
    """Convert AST to Python source code.

    This function takes a Python AST Module and converts it to
    properly formatted source code. When *original_source* is provided,
    comments and blank-line structure from the original are preserved in
    the generated output.

    Args:
        module: The AST Module to convert.
        format_with_black: Whether to format with black (default: True).
        line_length: Maximum line length for formatting (default: 88).
        add_header: Whether to add a generated code header (default: True).
        original_source: Optional original source code. When provided,
            comments and blank line structure are re-inserted into the
            generated output.

    Returns:
        Python source code as a string.

    Raises:
        ValueError: If AST cannot be converted to source.

    Example:
        >>> import ast
        >>> module = ast.parse("x: int = 1")
        >>> source = emit_python(module)
        >>> print(source)
        # Generated by FlowForge
        x: int = 1
    """
    if not _HAS_AST_UNPARSE:
        raise ValueError(
            f"ast.unparse requires Python 3.9+, current version is "
            f"{sys.version_info.major}.{sys.version_info.minor}"
        )

    # Ensure line numbers are set
    ast.fix_missing_locations(module)

    # Convert AST to source
    try:
        source = ast.unparse(module)
    except Exception as e:
        raise ValueError(f"Failed to unparse AST: {e}") from e

    # Add blank lines between classes for readability
    source = _add_blank_lines(source)

    # Format with black if requested
    if format_with_black:
        source = _format_with_black(source, line_length=line_length)

    # Preserve formatting from original source if provided
    if original_source is not None:
        from .formatter import preserve_comments, preserve_blank_lines

        source = preserve_comments(original_source, source)
        source = preserve_blank_lines(original_source, source)

    # Add header comment
    if add_header:
        header = '"""Generated by FlowForge - do not edit manually."""\n\n'
        source = header + source

    # Ensure trailing newline
    if not source.endswith("\n"):
        source += "\n"

    return source


def emit_python_minimal(module: ast.Module) -> str:
    """Convert AST to minimal Python source code without formatting.

    This is a simpler version of emit_python that skips formatting
    and header generation. Useful for quick conversions or testing.

    Args:
        module: The AST Module to convert.

    Returns:
        Python source code as a string.

    Raises:
        ValueError: If AST cannot be converted to source.
    """
    return emit_python(
        module,
        format_with_black=False,
        add_header=False,
    )


def emit_class(class_def: ast.ClassDef, include_imports: bool = False) -> str:
    """Convert a single class definition to Python source code.

    Useful for emitting individual classes rather than entire modules.

    Args:
        class_def: The AST ClassDef to convert.
        include_imports: Whether to include common imports (default: False).

    Returns:
        Python source code for the class.
    """
    module = ast.Module(body=[class_def], type_ignores=[])
    ast.fix_missing_locations(module)

    if not _HAS_AST_UNPARSE:
        raise ValueError(
            f"ast.unparse requires Python 3.9+, current version is "
            f"{sys.version_info.major}.{sys.version_info.minor}"
        )

    source = ast.unparse(module)

    if include_imports:
        imports = "from __future__ import annotations\n\nfrom trinity import component, system, resource, event\n\n"
        source = imports + source

    return source


def validate_syntax(source: str) -> tuple[bool, Optional[str]]:
    """Validate that Python source code is syntactically correct.

    This is a simple helper for quick syntax validation.
    For more detailed validation, use codegen.validator.validate_python().

    Args:
        source: The Python source code to validate.

    Returns:
        Tuple of (is_valid, error_message).
        If valid, error_message is None.

    Example:
        >>> valid, error = validate_syntax("x: int = 1")
        >>> print(valid)
        True
        >>> valid, error = validate_syntax("x = ")
        >>> print(valid, error)
        False unexpected EOF while parsing (<string>, line 1)
    """
    try:
        ast.parse(source)
        return True, None
    except SyntaxError as e:
        return False, str(e)


def roundtrip_ast(module: ast.Module) -> ast.Module:
    """Convert AST to source and back to verify correctness.

    This is useful for testing that the emitter produces valid Python
    that can be parsed back to equivalent AST.

    Args:
        module: The AST Module to roundtrip.

    Returns:
        A new AST Module parsed from the emitted source.

    Raises:
        ValueError: If roundtrip fails.
    """
    source = emit_python(module, format_with_black=False, add_header=False)
    try:
        return ast.parse(source)
    except SyntaxError as e:
        raise ValueError(f"Roundtrip failed - generated invalid Python: {e}") from e
