"""
WGSL code generation for complete ray marching scenes (T-DEMO-2.7).

Generates complete compute shaders for SDF ray marching:
  - Camera setup (position, target, FOV, aspect ratio)
  - Light definitions (point, directional, area)
  - Render settings (max steps, epsilon, max distance)
  - Main compute shader with ray generation, marching, and shading
  - Integration with scene_sdf() and scene_material()

The generated shader is a complete WGSL module ready for wgpu compilation.

Usage:
    >>> from engine.rendering.demoscene.scene_codegen import generate_compute_shader
    >>> from engine.rendering.demoscene.ast_nodes import (
    ...     SceneGraph, SphereNode, PositionNode, FloatNode, FullSceneNode
    ... )
    >>> graph = SceneGraph(primitives=(SphereNode(PositionNode(), FloatNode(1.0)),))
    >>> scene = FullSceneNode(scene_graph=graph, name="demo")
    >>> wgsl = generate_compute_shader(scene)
"""

from __future__ import annotations

from typing import Optional, Sequence

from .ast_nodes import (
    Axis, BendNode, BoxNode, BoxFrameNode, CameraNode, CapsuleNode, CellIdNode,
    ConeNode, CylinderNode, DomainOpNode, EllipsoidNode, FloatNode, FullSceneNode,
    KifsNode, LightNode, LightType, MaterialNode, MirrorNode, OctahedronNode,
    PlaneNode, PositionNode, PyramidNode, RenderSettingsNode, RepeatNode,
    RoundedBoxNode, SceneGraph, SdfPrimitiveNode, SphereNode, StretchNode,
    TorusNode, TwistNode, Vec3Node,
)
from .material_codegen import MaterialCodegen, MATERIAL_STRUCT
from .wgsl_codegen import WgslCodeGen


# =============================================================================
# SHADER HEADER
# =============================================================================

COMPUTE_SHADER_HEADER = """\
// SPDX-License-Identifier: MIT
//
// Auto-generated by SceneCodegen (T-DEMO-2.7).
// Complete ray marching compute shader for SDF rendering.
//
// This shader performs:
//   1. Ray generation from camera parameters
//   2. Sphere tracing (ray marching) through the SDF
//   3. Normal estimation via central differences
//   4. PBR lighting with multiple light sources
//   5. Output to storage texture
//
// Convention: Inigo Quilez SDF primitives and ray marching techniques.
"""


# =============================================================================
# BIND GROUP DEFINITIONS
# =============================================================================

BIND_GROUP_0 = """\
// Bind group 0: Output texture
@group(0) @binding(0)
var output_texture: texture_storage_2d<rgba8unorm, write>;
"""

BIND_GROUP_1_UNIFORMS = """\
// Bind group 1: Uniforms
struct Uniforms {
    camera_origin: vec3<f32>,
    camera_fov: f32,
    camera_target: vec3<f32>,
    camera_aspect: f32,
    camera_up: vec3<f32>,
    time: f32,
    resolution: vec2<f32>,
    max_steps: u32,
    max_distance: f32,
    epsilon: f32,
    _padding: vec3<f32>,
}

@group(1) @binding(0)
var<uniform> uniforms: Uniforms;
"""


# =============================================================================
# RAY GENERATION
# =============================================================================

RAY_GENERATION = """\
/// Generates a ray direction from screen coordinates.
///   uv         -- normalized screen coordinates [-1, 1]
///   origin     -- camera position
///   target     -- look-at point
///   up         -- up vector
///   fov        -- field of view in degrees
///   aspect     -- aspect ratio (width / height)
///   returns    -- normalized ray direction
fn generate_ray(
    uv: vec2<f32>,
    origin: vec3<f32>,
    target: vec3<f32>,
    up: vec3<f32>,
    fov: f32,
    aspect: f32,
) -> vec3<f32> {
    let forward = normalize(target - origin);
    let right = normalize(cross(forward, up));
    let up_corrected = cross(right, forward);

    let fov_rad = fov * 3.14159265359 / 180.0;
    let half_height = tan(fov_rad * 0.5);
    let half_width = half_height * aspect;

    let rd = normalize(
        forward +
        right * uv.x * half_width +
        up_corrected * uv.y * half_height
    );

    return rd;
}
"""


# =============================================================================
# RAY MARCHING
# =============================================================================

RAY_MARCHING = """\
/// Result of ray marching.
struct RayHit {
    hit: bool,
    position: vec3<f32>,
    distance: f32,
    material_id: u32,
    steps: u32,
}

/// Marches a ray through the scene using sphere tracing.
///   ro         -- ray origin
///   rd         -- ray direction (normalized)
///   max_steps  -- maximum number of marching steps
///   max_dist   -- maximum ray distance
///   epsilon    -- surface hit threshold
///   returns    -- RayHit with hit info
fn ray_march(
    ro: vec3<f32>,
    rd: vec3<f32>,
    max_steps: u32,
    max_dist: f32,
    epsilon: f32,
) -> RayHit {
    var t: f32 = 0.0;
    var hit = RayHit(false, vec3<f32>(0.0), 0.0, 0u, 0u);

    for (var i = 0u; i < max_steps; i = i + 1u) {
        let p = ro + rd * t;
        let result = scene_sdf(p);
        let d = result.x;
        let mat_id = u32(result.y);

        if (d < epsilon) {
            hit.hit = true;
            hit.position = p;
            hit.distance = t;
            hit.material_id = mat_id;
            hit.steps = i;
            return hit;
        }

        t = t + d;

        if (t > max_dist) {
            hit.steps = i;
            return hit;
        }
    }

    hit.steps = max_steps;
    return hit;
}
"""


# =============================================================================
# NORMAL ESTIMATION
# =============================================================================

NORMAL_ESTIMATION = """\
/// Estimates the surface normal using central differences.
///   p          -- surface position
///   epsilon    -- sampling offset
///   returns    -- normalized surface normal
fn estimate_normal(p: vec3<f32>, epsilon: f32) -> vec3<f32> {
    let e = vec2<f32>(epsilon, 0.0);
    let n = vec3<f32>(
        scene_sdf(p + e.xyy).x - scene_sdf(p - e.xyy).x,
        scene_sdf(p + e.yxy).x - scene_sdf(p - e.yxy).x,
        scene_sdf(p + e.yyx).x - scene_sdf(p - e.yyx).x,
    );
    return normalize(n);
}
"""


# =============================================================================
# PBR LIGHTING
# =============================================================================

PBR_LIGHTING = """\
/// Fresnel-Schlick approximation.
fn fresnel_schlick(cos_theta: f32, f0: vec3<f32>) -> vec3<f32> {
    return f0 + (1.0 - f0) * pow(clamp(1.0 - cos_theta, 0.0, 1.0), 5.0);
}

/// GGX/Trowbridge-Reitz normal distribution.
fn distribution_ggx(n: vec3<f32>, h: vec3<f32>, roughness: f32) -> f32 {
    let a = roughness * roughness;
    let a2 = a * a;
    let n_dot_h = max(dot(n, h), 0.0);
    let n_dot_h2 = n_dot_h * n_dot_h;

    let num = a2;
    let denom = n_dot_h2 * (a2 - 1.0) + 1.0;
    let denom2 = 3.14159265359 * denom * denom;

    return num / max(denom2, 0.0001);
}

/// Schlick-GGX geometry function.
fn geometry_schlick_ggx(n_dot_v: f32, roughness: f32) -> f32 {
    let r = roughness + 1.0;
    let k = (r * r) / 8.0;
    return n_dot_v / (n_dot_v * (1.0 - k) + k);
}

/// Smith's geometry function.
fn geometry_smith(n: vec3<f32>, v: vec3<f32>, l: vec3<f32>, roughness: f32) -> f32 {
    let n_dot_v = max(dot(n, v), 0.0);
    let n_dot_l = max(dot(n, l), 0.0);
    let ggx1 = geometry_schlick_ggx(n_dot_v, roughness);
    let ggx2 = geometry_schlick_ggx(n_dot_l, roughness);
    return ggx1 * ggx2;
}

/// Calculates PBR lighting for a surface point.
///   p          -- surface position
///   n          -- surface normal
///   v          -- view direction (towards camera)
///   mat        -- material properties
///   returns    -- final color
fn calculate_lighting(
    p: vec3<f32>,
    n: vec3<f32>,
    v: vec3<f32>,
    mat: Material,
) -> vec3<f32> {
    // Dielectric F0 = 0.04, metallic uses albedo
    let f0 = mix(vec3<f32>(0.04), mat.albedo, mat.metallic);

    var lo = vec3<f32>(0.0);

    // Process each light (inline for now, generated per-scene)
    lo = lo + calculate_light_contribution(p, n, v, mat, f0);

    // Ambient term
    let ambient = vec3<f32>(0.03) * mat.albedo * mat.ambient_occlusion;

    // Emission
    let emission = mat.emission;

    return ambient + lo + emission;
}
"""


# =============================================================================
# TONE MAPPING
# =============================================================================

TONE_MAPPING = """\
/// ACES filmic tone mapping.
fn tone_map_aces(color: vec3<f32>) -> vec3<f32> {
    let a = 2.51;
    let b = 0.03;
    let c = 2.43;
    let d = 0.59;
    let e = 0.14;
    return clamp((color * (a * color + b)) / (color * (c * color + d) + e), vec3<f32>(0.0), vec3<f32>(1.0));
}

/// Linear to sRGB conversion.
fn linear_to_srgb(color: vec3<f32>) -> vec3<f32> {
    let cutoff = step(color, vec3<f32>(0.0031308));
    let low = color * 12.92;
    let high = 1.055 * pow(color, vec3<f32>(1.0 / 2.4)) - 0.055;
    return mix(high, low, cutoff);
}
"""


# =============================================================================
# SCENE CODEGEN CLASS
# =============================================================================


class SceneCodegen:
    """Generates complete WGSL compute shaders for ray marching scenes.

    This class orchestrates the generation of:
      - SDF scene function (via WgslCodeGen)
      - Material lookup function (via MaterialCodegen)
      - Light contribution functions
      - Main compute shader entry point

    Usage::

        gen = SceneCodegen()
        wgsl = gen.generate(full_scene)
    """

    def __init__(self) -> None:
        self._sdf_codegen = WgslCodeGen()
        self._material_codegen = MaterialCodegen()
        self._emitted_functions: set[str] = set()

    def generate(
        self,
        scene: FullSceneNode,
        *,
        include_uniforms: bool = True,
        include_bindings: bool = True,
    ) -> str:
        """Generate a complete compute shader for the scene.

        Args:
            scene: FullSceneNode containing all scene components.
            include_uniforms: Whether to include uniform buffer definitions.
            include_bindings: Whether to include bind group definitions.

        Returns:
            Complete WGSL compute shader as a string.
        """
        self._emitted_functions.clear()
        lines: list[str] = []

        # Header
        lines.append(COMPUTE_SHADER_HEADER)
        if scene.name:
            lines.append(f"// Scene: {scene.name}")
        lines.append("")

        # Bind groups
        if include_bindings:
            lines.append(BIND_GROUP_0)
        if include_uniforms:
            lines.append(BIND_GROUP_1_UNIFORMS)

        # Material struct
        lines.append(MATERIAL_STRUCT)

        # Scene SDF function (includes primitives, domain ops, combinators)
        sdf_code = self._generate_scene_sdf(scene.scene_graph)
        lines.append(sdf_code)

        # Material lookup function
        material_code = self._generate_scene_material(scene.materials)
        lines.append(material_code)

        # Light contribution function
        light_code = self._generate_light_contributions(scene.lights)
        lines.append(light_code)

        # Ray generation
        lines.append(RAY_GENERATION)

        # Ray marching
        lines.append(RAY_MARCHING)

        # Normal estimation
        lines.append(NORMAL_ESTIMATION)

        # PBR lighting
        lines.append(PBR_LIGHTING)

        # Tone mapping
        lines.append(TONE_MAPPING)

        # Main compute shader
        main_shader = self._generate_main_shader(scene.settings)
        lines.append(main_shader)

        return "\n".join(lines)

    def _generate_scene_sdf(self, graph: SceneGraph) -> str:
        """Generate the scene_sdf function.

        This uses WgslCodeGen but modifies the output to return
        vec2<f32>(distance, material_id) instead of just distance.

        Args:
            graph: SceneGraph with primitives and domain operations.

        Returns:
            WGSL code for scene_sdf function.
        """
        lines: list[str] = []

        # Emit SDF primitive functions
        for prim in graph.primitives:
            self._emit_sdf_primitive_function(lines, prim)

        # Emit domain operation imports/declarations if needed
        if graph.pipeline:
            lines.append(self._get_domain_op_imports())

        # Emit compensation functions if needed
        for op in graph.pipeline:
            if isinstance(op, KifsNode):
                if "domain_kifs_compensation" not in self._emitted_functions:
                    self._emitted_functions.add("domain_kifs_compensation")
                    lines.append(self._build_kifs_compensation())
            elif isinstance(op, StretchNode):
                if "domain_stretch_compensation" not in self._emitted_functions:
                    self._emitted_functions.add("domain_stretch_compensation")
                    lines.append(self._build_stretch_compensation())

        # Generate scene_sdf function
        lines.append(self._build_scene_sdf_function(graph))

        return "\n".join(lines)

    def _emit_sdf_primitive_function(
        self,
        lines: list[str],
        prim: SdfPrimitiveNode,
    ) -> None:
        """Emit SDF primitive function if not already emitted."""
        fn_name = self._get_sdf_fn_name(prim)
        if fn_name in self._emitted_functions:
            return
        self._emitted_functions.add(fn_name)
        lines.append(self._get_sdf_primitive_code(prim))

    def _get_sdf_fn_name(self, prim: SdfPrimitiveNode) -> str:
        """Get the WGSL function name for an SDF primitive."""
        type_map = {
            SphereNode: "sdf_sphere",
            BoxNode: "sdf_box",
            TorusNode: "sdf_torus",
            CylinderNode: "sdf_cylinder",
            ConeNode: "sdf_cone",
            PlaneNode: "sdf_plane",
            CapsuleNode: "sdf_capsule",
            EllipsoidNode: "sdf_ellipsoid",
            BoxFrameNode: "sdf_box_frame",
            RoundedBoxNode: "sdf_rounded_box",
            OctahedronNode: "sdf_octahedron",
            PyramidNode: "sdf_pyramid",
        }
        return type_map.get(type(prim), "sdf_unknown")

    def _get_sdf_primitive_code(self, prim: SdfPrimitiveNode) -> str:
        """Get WGSL code for an SDF primitive function."""
        if isinstance(prim, SphereNode):
            return """\
fn sdf_sphere(p: vec3<f32>, r: f32) -> f32 {
    return length(p) - r;
}
"""
        elif isinstance(prim, BoxNode):
            return """\
fn sdf_box(p: vec3<f32>, b: vec3<f32>) -> f32 {
    let q = abs(p) - b;
    return length(max(q, vec3<f32>(0.0))) + min(max(q.x, max(q.y, q.z)), 0.0);
}
"""
        elif isinstance(prim, TorusNode):
            return """\
fn sdf_torus(p: vec3<f32>, t: vec2<f32>) -> f32 {
    let q = vec2<f32>(length(p.xz) - t.x, p.y);
    return length(q) - t.y;
}
"""
        elif isinstance(prim, CylinderNode):
            return """\
fn sdf_cylinder(p: vec3<f32>, h: f32, r: f32) -> f32 {
    let d = abs(vec2<f32>(length(p.xz), p.y)) - vec2<f32>(r, h * 0.5);
    return min(max(d.x, d.y), 0.0) + length(max(d, vec2<f32>(0.0)));
}
"""
        elif isinstance(prim, ConeNode):
            return """\
fn sdf_cone(p: vec3<f32>, h: f32, r1: f32, r2: f32) -> f32 {
    let half_h = h * 0.5;
    let q = vec2<f32>(length(p.xz), p.y);
    let k1 = vec2<f32>(r2, h);
    let k2 = vec2<f32>(r2 - r1, 2.0 * h);
    let ca = vec2<f32>(q.x - min(q.x, select(r2, r1, q.y < 0.0)), abs(q.y) - half_h);
    let cb = q - k1 + k2 * clamp(dot(k1 - q, k2) / dot(k2, k2), 0.0, 1.0);
    let s = select(1.0, -1.0, cb.x < 0.0 && ca.y < 0.0);
    return s * sqrt(min(dot(ca, ca), dot(cb, cb)));
}
"""
        elif isinstance(prim, PlaneNode):
            return """\
fn sdf_plane(p: vec3<f32>, n: vec3<f32>, d: f32) -> f32 {
    return dot(p, normalize(n)) + d;
}
"""
        elif isinstance(prim, CapsuleNode):
            return """\
fn sdf_capsule(p: vec3<f32>, a: vec3<f32>, b: vec3<f32>, r: f32) -> f32 {
    let pa = p - a;
    let ba = b - a;
    let h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
    return length(pa - ba * h) - r;
}
"""
        elif isinstance(prim, EllipsoidNode):
            return """\
fn sdf_ellipsoid(p: vec3<f32>, r: vec3<f32>) -> f32 {
    let k0 = length(p / r);
    let k1 = length(p / (r * r));
    return k0 * (k0 - 1.0) / k1;
}
"""
        elif isinstance(prim, BoxFrameNode):
            return """\
fn sdf_box_frame(p: vec3<f32>, b: vec3<f32>, e: f32) -> f32 {
    let q = abs(p) - b;
    let w = abs(q + e) - e;
    return min(min(
        length(max(vec3<f32>(q.x, w.y, w.z), vec3<f32>(0.0))) + min(max(q.x, max(w.y, w.z)), 0.0),
        length(max(vec3<f32>(w.x, q.y, w.z), vec3<f32>(0.0))) + min(max(w.x, max(q.y, w.z)), 0.0)
    ),
        length(max(vec3<f32>(w.x, w.y, q.z), vec3<f32>(0.0))) + min(max(w.x, max(w.y, q.z)), 0.0)
    );
}
"""
        elif isinstance(prim, RoundedBoxNode):
            return """\
fn sdf_rounded_box(p: vec3<f32>, b: vec3<f32>, r: f32) -> f32 {
    let q = abs(p) - b;
    return length(max(q, vec3<f32>(0.0))) + min(max(q.x, max(q.y, q.z)), 0.0) - r;
}
"""
        elif isinstance(prim, OctahedronNode):
            return """\
fn sdf_octahedron(p: vec3<f32>, s: f32) -> f32 {
    let q = abs(p);
    let m = q.x + q.y + q.z - s;
    var k: vec3<f32>;
    if (3.0 * q.x < m) {
        k = q.xyz;
    } else if (3.0 * q.y < m) {
        k = q.yzx;
    } else if (3.0 * q.z < m) {
        k = q.zxy;
    } else {
        return m * 0.57735027;
    }
    let o = clamp(0.5 * (k.z - k.y + s), 0.0, s);
    return length(vec3<f32>(k.x, k.y - s + o, k.z - o));
}
"""
        elif isinstance(prim, PyramidNode):
            return """\
fn sdf_pyramid(p: vec3<f32>, h: f32) -> f32 {
    let m2 = h * h + 0.25;
    var q = vec3<f32>(abs(p.x), p.y, abs(p.z));
    if (q.z > q.x) {
        q = vec3<f32>(q.z, q.y, q.x);
    }
    q = vec3<f32>(q.x - 0.5, q.y, q.z - 0.5);
    let a = vec3<f32>(q.z, h * q.y - 0.5 * q.x, h * q.x + 0.5 * q.y);
    let s = max(-a.x, 0.0);
    let t = clamp((a.y - 0.5 * a.z) / (m2 + 0.25), 0.0, 1.0);
    let k1 = vec2<f32>(s, h * s - q.y);
    let k2 = vec2<f32>(t * 0.5, h * t) - vec2<f32>(q.x, q.y);
    let d = sqrt(min(dot(k1, k1), dot(k2, k2)));
    let inside = max(a.y, -q.y - h);
    return select(d, -d, inside < 0.0);
}
"""
        return "// Unknown primitive\n"

    def _get_domain_op_imports(self) -> str:
        """Get domain operation function imports/declarations."""
        return """\
// Domain operation functions (from sdf_domain.wgsl)

fn domain_repeat(p: vec3<f32>, c: vec3<f32>) -> vec3<f32> {
    return (p - c * floor(p / c)) - 0.5 * c;
}

fn domain_cell_id(p: vec3<f32>, c: vec3<f32>) -> vec3<f32> {
    return floor(p / c + 0.5);
}

fn domain_mirror_x(p: vec3<f32>) -> vec3<f32> {
    return vec3<f32>(abs(p.x), p.y, p.z);
}

fn domain_mirror_y(p: vec3<f32>) -> vec3<f32> {
    return vec3<f32>(p.x, abs(p.y), p.z);
}

fn domain_mirror_z(p: vec3<f32>) -> vec3<f32> {
    return vec3<f32>(p.x, p.y, abs(p.z));
}

fn domain_kifs(p: vec3<f32>, folds: f32) -> vec3<f32> {
    let safe_folds = max(abs(folds), 1.0);
    let angle = 6.283185307179586 / safe_folds;
    var q = p;
    for (var i = 0u; i < u32(safe_folds); i = i + 1u) {
        q = vec3<f32>(abs(q.x), abs(q.y), q.z);
        let ca = cos(angle);
        let sa = sin(angle);
        let rx = ca * q.x - sa * q.y;
        let ry = sa * q.x + ca * q.y;
        q = vec3<f32>(rx, ry, q.z);
    }
    return q;
}

fn domain_twist(p: vec3<f32>, k: f32) -> vec3<f32> {
    let c = cos(k * p.y);
    let s = sin(k * p.y);
    return vec3<f32>(c * p.x - s * p.z, p.y, s * p.x + c * p.z);
}

fn domain_bend(p: vec3<f32>, r: f32) -> vec3<f32> {
    let safe_r = max(abs(r), 1e-8);
    let theta = p.x / safe_r;
    let c = cos(theta);
    let s = sin(theta);
    let bent = vec3<f32>(-safe_r + (safe_r + p.z) * c, p.y, (safe_r + p.z) * s);
    return select(bent, p, abs(r) < 1e-8);
}

fn domain_stretch_x(p: vec3<f32>, s: f32) -> vec3<f32> {
    return vec3<f32>(p.x * s, p.y / s, p.z / s);
}

fn domain_stretch_y(p: vec3<f32>, s: f32) -> vec3<f32> {
    return vec3<f32>(p.x / s, p.y * s, p.z / s);
}

fn domain_stretch_z(p: vec3<f32>, s: f32) -> vec3<f32> {
    return vec3<f32>(p.x / s, p.y / s, p.z * s);
}
"""

    def _build_kifs_compensation(self) -> str:
        """Build KIFS compensation function."""
        return """\
fn domain_kifs_compensation(folds: f32) -> f32 {
    let safe_folds = max(abs(folds), 1.0);
    let angle = 6.283185307179586 / safe_folds;
    let half_angle = angle * 0.5;
    let per_fold = cos(half_angle);
    var comp: f32 = 1.0;
    for (var i = 0u; i < u32(safe_folds); i = i + 1u) {
        comp *= per_fold;
    }
    return max(comp, 1e-8);
}
"""

    def _build_stretch_compensation(self) -> str:
        """Build stretch compensation function."""
        return """\
fn domain_stretch_compensation(s: f32) -> f32 {
    let safe_s = select(s, 1e-8, abs(s) < 1e-8);
    return min(abs(safe_s), 1.0 / abs(safe_s));
}
"""

    def _build_scene_sdf_function(self, graph: SceneGraph) -> str:
        """Build the scene_sdf function.

        Returns vec2<f32>(distance, material_id).
        """
        lines: list[str] = []

        scene_name = graph.name.replace(" ", "_").replace("-", "_") or "scene"
        fn_name = f"scene_sdf"

        lines.append("/// Signed distance function for the complete scene.")
        lines.append("///   p        -- query position in world space")
        lines.append("///   returns  -- vec2<f32>(distance, material_id)")
        lines.append(f"fn {fn_name}(p: vec3<f32>) -> vec2<f32> {{")

        # Domain transformation
        if graph.pipeline:
            domain_expr = self._build_pipeline_expr(graph.pipeline)
            lines.append("    // Apply domain transformations")
            lines.append(f"    let p_d = {domain_expr};")
            pos_var = "p_d"
        else:
            pos_var = "p"

        # Compensation factor
        comp_expr = self._build_compensation_expr(graph.pipeline)
        lines.append(f"    let comp = {comp_expr};")

        # Evaluate each primitive
        lines.append("    // Evaluate SDF primitives")
        if len(graph.primitives) == 0:
            lines.append("    let result = vec2<f32>(1e10, 0.0);")
        elif len(graph.primitives) == 1:
            call = self._sdf_call(graph.primitives[0], pos_var, 0)
            lines.append(f"    let result = {call};")
        else:
            for i, prim in enumerate(graph.primitives):
                call = self._sdf_call(prim, pos_var, i)
                lines.append(f"    let d{i} = {call};")

            # Build min chain with select for material ID propagation
            lines.append(f"    var result = d0;")
            for i in range(1, len(graph.primitives)):
                lines.append(f"    result = select(d{i}, result, result.x < d{i}.x);")

        lines.append("")
        lines.append("    return vec2<f32>(result.x / comp, result.y);")
        lines.append("}")

        return "\n".join(lines)

    def _build_pipeline_expr(self, pipeline: tuple) -> str:
        """Build nested domain transformation expression."""
        if not pipeline:
            return "p"

        expr = "p"
        for op in reversed(pipeline):
            if isinstance(op, RepeatNode):
                expr = f"domain_repeat({expr}, {_fmt_vec3(op.cell_size)})"
            elif isinstance(op, CellIdNode):
                expr = f"domain_cell_id({expr}, {_fmt_vec3(op.cell_size)})"
            elif isinstance(op, MirrorNode):
                expr = f"domain_mirror_{op.axis.value}({expr})"
            elif isinstance(op, KifsNode):
                expr = f"domain_kifs({expr}, {_fmt_float(op.folds.value)})"
            elif isinstance(op, TwistNode):
                expr = f"domain_twist({expr}, {_fmt_float(op.rate.value)})"
            elif isinstance(op, BendNode):
                expr = f"domain_bend({expr}, {_fmt_float(op.radius.value)})"
            elif isinstance(op, StretchNode):
                expr = f"domain_stretch_{op.axis.value}({expr}, {_fmt_float(op.stretch.value)})"
        return expr

    def _build_compensation_expr(self, pipeline: tuple) -> str:
        """Build compensation factor expression."""
        factors: list[str] = []
        for op in pipeline:
            if isinstance(op, KifsNode):
                factors.append(f"domain_kifs_compensation({_fmt_float(op.folds.value)})")
            elif isinstance(op, StretchNode):
                factors.append(f"domain_stretch_compensation({_fmt_float(op.stretch.value)})")
        if not factors:
            return "1.0"
        return " * ".join(factors)

    def _sdf_call(
        self,
        prim: SdfPrimitiveNode,
        pos_var: str,
        material_id: int,
    ) -> str:
        """Generate SDF call returning vec2<f32>(distance, material_id)."""
        mat_id = f"{material_id}.0"

        if isinstance(prim, SphereNode):
            return f"vec2<f32>(sdf_sphere({pos_var}, {_fmt_float(prim.radius.value)}), {mat_id})"
        elif isinstance(prim, BoxNode):
            return f"vec2<f32>(sdf_box({pos_var}, {_fmt_vec3(prim.size)}), {mat_id})"
        elif isinstance(prim, TorusNode):
            return f"vec2<f32>(sdf_torus({pos_var}, vec2<f32>({_fmt_float(prim.major_radius.value)}, {_fmt_float(prim.minor_radius.value)})), {mat_id})"
        elif isinstance(prim, CylinderNode):
            return f"vec2<f32>(sdf_cylinder({pos_var}, {_fmt_float(prim.height.value)}, {_fmt_float(prim.radius.value)}), {mat_id})"
        elif isinstance(prim, ConeNode):
            return f"vec2<f32>(sdf_cone({pos_var}, {_fmt_float(prim.height.value)}, {_fmt_float(prim.radius_top.value)}, {_fmt_float(prim.radius_bottom.value)}), {mat_id})"
        elif isinstance(prim, PlaneNode):
            return f"vec2<f32>(sdf_plane({pos_var}, {_fmt_vec3(prim.normal)}, {_fmt_float(prim.distance.value)}), {mat_id})"
        elif isinstance(prim, CapsuleNode):
            return f"vec2<f32>(sdf_capsule({pos_var}, {_fmt_vec3(prim.endpoint_a)}, {_fmt_vec3(prim.endpoint_b)}, {_fmt_float(prim.radius.value)}), {mat_id})"
        elif isinstance(prim, EllipsoidNode):
            return f"vec2<f32>(sdf_ellipsoid({pos_var}, {_fmt_vec3(prim.radii)}), {mat_id})"
        elif isinstance(prim, BoxFrameNode):
            return f"vec2<f32>(sdf_box_frame({pos_var}, {_fmt_vec3(prim.half_extents)}, {_fmt_float(prim.edge_thickness.value)}), {mat_id})"
        elif isinstance(prim, RoundedBoxNode):
            return f"vec2<f32>(sdf_rounded_box({pos_var}, {_fmt_vec3(prim.half_extents)}, {_fmt_float(prim.corner_radius.value)}), {mat_id})"
        elif isinstance(prim, OctahedronNode):
            return f"vec2<f32>(sdf_octahedron({pos_var}, {_fmt_float(prim.scale.value)}), {mat_id})"
        elif isinstance(prim, PyramidNode):
            return f"vec2<f32>(sdf_pyramid({pos_var}, {_fmt_float(prim.height.value)}), {mat_id})"

        return f"vec2<f32>(1e10, {mat_id})"

    def _generate_scene_material(self, materials: tuple) -> str:
        """Generate scene_material function."""
        return self._material_codegen.generate(
            list(materials),
            include_struct=False,  # Already included
            name="",
        )

    def _generate_light_contributions(self, lights: tuple) -> str:
        """Generate light contribution calculation function."""
        lines: list[str] = []

        if not lights:
            # Default single directional light
            lines.append("""\
/// Calculates lighting contribution from scene lights.
fn calculate_light_contribution(
    p: vec3<f32>,
    n: vec3<f32>,
    v: vec3<f32>,
    mat: Material,
    f0: vec3<f32>,
) -> vec3<f32> {
    // Default directional light
    let light_dir = normalize(vec3<f32>(1.0, 1.0, 1.0));
    let light_color = vec3<f32>(1.0, 0.98, 0.95);
    let light_intensity = 2.0;

    let l = light_dir;
    let h = normalize(v + l);
    let n_dot_l = max(dot(n, l), 0.0);

    // Cook-Torrance BRDF
    let ndf = distribution_ggx(n, h, mat.roughness);
    let g = geometry_smith(n, v, l, mat.roughness);
    let f = fresnel_schlick(max(dot(h, v), 0.0), f0);

    let ks = f;
    let kd = (vec3<f32>(1.0) - ks) * (1.0 - mat.metallic);

    let numerator = ndf * g * f;
    let denominator = 4.0 * max(dot(n, v), 0.0) * n_dot_l + 0.0001;
    let specular = numerator / denominator;

    let diffuse = kd * mat.albedo / 3.14159265359;

    return (diffuse + specular) * light_color * light_intensity * n_dot_l;
}
""")
        else:
            # Generate function with explicit lights
            lines.append("/// Calculates lighting contribution from scene lights.")
            lines.append("fn calculate_light_contribution(")
            lines.append("    p: vec3<f32>,")
            lines.append("    n: vec3<f32>,")
            lines.append("    v: vec3<f32>,")
            lines.append("    mat: Material,")
            lines.append("    f0: vec3<f32>,")
            lines.append(") -> vec3<f32> {")
            lines.append("    var result = vec3<f32>(0.0);")

            for i, light in enumerate(lights):
                lines.append(f"")
                lines.append(f"    // Light {i}: {light.light_type.value}")

                if light.light_type == LightType.DIRECTIONAL:
                    dir_vec = _fmt_vec3(light.direction)
                    lines.append(f"    let l{i} = normalize({dir_vec});")
                elif light.light_type == LightType.POINT:
                    pos_vec = _fmt_vec3(light.position)
                    lines.append(f"    let l{i}_vec = {pos_vec} - p;")
                    lines.append(f"    let l{i}_dist = length(l{i}_vec);")
                    lines.append(f"    let l{i} = l{i}_vec / l{i}_dist;")
                    lines.append(f"    let l{i}_atten = 1.0 / (1.0 + l{i}_dist * l{i}_dist);")
                else:  # AREA
                    pos_vec = _fmt_vec3(light.position)
                    lines.append(f"    let l{i}_vec = {pos_vec} - p;")
                    lines.append(f"    let l{i} = normalize(l{i}_vec);")

                color_vec = _fmt_vec3(light.color)
                intensity = _fmt_float(light.intensity.value)
                lines.append(f"    let l{i}_color = {color_vec};")
                lines.append(f"    let l{i}_intensity = {intensity};")

                lines.append(f"    let h{i} = normalize(v + l{i});")
                lines.append(f"    let n_dot_l{i} = max(dot(n, l{i}), 0.0);")

                lines.append(f"")
                lines.append(f"    let ndf{i} = distribution_ggx(n, h{i}, mat.roughness);")
                lines.append(f"    let g{i} = geometry_smith(n, v, l{i}, mat.roughness);")
                lines.append(f"    let f{i} = fresnel_schlick(max(dot(h{i}, v), 0.0), f0);")

                lines.append(f"")
                lines.append(f"    let ks{i} = f{i};")
                lines.append(f"    let kd{i} = (vec3<f32>(1.0) - ks{i}) * (1.0 - mat.metallic);")

                lines.append(f"")
                lines.append(f"    let num{i} = ndf{i} * g{i} * f{i};")
                lines.append(f"    let denom{i} = 4.0 * max(dot(n, v), 0.0) * n_dot_l{i} + 0.0001;")
                lines.append(f"    let spec{i} = num{i} / denom{i};")

                lines.append(f"")
                lines.append(f"    let diff{i} = kd{i} * mat.albedo / 3.14159265359;")

                if light.light_type == LightType.POINT:
                    lines.append(f"    result = result + (diff{i} + spec{i}) * l{i}_color * l{i}_intensity * n_dot_l{i} * l{i}_atten;")
                else:
                    lines.append(f"    result = result + (diff{i} + spec{i}) * l{i}_color * l{i}_intensity * n_dot_l{i};")

            lines.append("")
            lines.append("    return result;")
            lines.append("}")

        return "\n".join(lines)

    def _generate_main_shader(self, settings: RenderSettingsNode) -> str:
        """Generate the main compute shader entry point."""
        wg_x = settings.workgroup_size_x
        wg_y = settings.workgroup_size_y

        return f"""\
/// Main compute shader entry point.
@compute @workgroup_size({wg_x}, {wg_y}, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {{
    let dims = textureDimensions(output_texture);
    let coords = vec2<i32>(global_id.xy);

    // Skip out-of-bounds pixels
    if (coords.x >= i32(dims.x) || coords.y >= i32(dims.y)) {{
        return;
    }}

    // Convert to normalized coordinates [-1, 1]
    let uv = (vec2<f32>(f32(coords.x), f32(coords.y)) / vec2<f32>(f32(dims.x), f32(dims.y))) * 2.0 - 1.0;
    let uv_flipped = vec2<f32>(uv.x, -uv.y);  // Flip Y for standard orientation

    // Generate ray
    let ro = uniforms.camera_origin;
    let rd = generate_ray(
        uv_flipped,
        ro,
        uniforms.camera_target,
        uniforms.camera_up,
        uniforms.camera_fov,
        uniforms.camera_aspect,
    );

    // Ray march
    let hit = ray_march(
        ro,
        rd,
        uniforms.max_steps,
        uniforms.max_distance,
        uniforms.epsilon,
    );

    var color: vec3<f32>;

    if (hit.hit) {{
        // Get normal and material
        let n = estimate_normal(hit.position, uniforms.epsilon);
        let mat = scene_material(hit.material_id);
        let v = normalize(ro - hit.position);

        // Calculate lighting
        color = calculate_lighting(hit.position, n, v, mat);

        // Tone mapping and gamma correction
        color = tone_map_aces(color);
        color = linear_to_srgb(color);
    }} else {{
        // Background gradient
        let t = 0.5 * (rd.y + 1.0);
        color = mix(vec3<f32>(0.1, 0.1, 0.15), vec3<f32>(0.3, 0.4, 0.6), t);
    }}

    // Write output
    textureStore(output_texture, coords, vec4<f32>(color, 1.0));
}}
"""


# =============================================================================
# FORMAT HELPERS
# =============================================================================


def _fmt_float(val: float) -> str:
    """Format a float for WGSL output."""
    if val == int(val) and not (val == 0.0 and str(val).startswith("-")):
        return f"{int(val)}.0"
    return f"{val}"


def _fmt_vec3(v: Vec3Node) -> str:
    """Format a Vec3Node for WGSL output."""
    return (
        f"vec3<f32>("
        f"{_fmt_float(v.x)}, {_fmt_float(v.y)}, {_fmt_float(v.z)}"
        f")"
    )


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================


def generate_scene_wgsl(
    scene: FullSceneNode,
    *,
    include_uniforms: bool = True,
    include_bindings: bool = True,
) -> str:
    """Generate complete WGSL compute shader for a scene.

    Args:
        scene: FullSceneNode containing all scene components.
        include_uniforms: Whether to include uniform buffer definitions.
        include_bindings: Whether to include bind group definitions.

    Returns:
        Complete WGSL compute shader as a string.

    Example:
        >>> from engine.rendering.demoscene.ast_nodes import (
        ...     SceneGraph, SphereNode, PositionNode, FloatNode, FullSceneNode
        ... )
        >>> graph = SceneGraph(primitives=(SphereNode(PositionNode(), FloatNode(1.0)),))
        >>> scene = FullSceneNode(scene_graph=graph, name="demo")
        >>> wgsl = generate_scene_wgsl(scene)
        >>> "@compute" in wgsl
        True
    """
    gen = SceneCodegen()
    return gen.generate(
        scene,
        include_uniforms=include_uniforms,
        include_bindings=include_bindings,
    )


def generate_compute_shader(
    scene: FullSceneNode,
    *,
    include_uniforms: bool = True,
    include_bindings: bool = True,
) -> str:
    """Alias for generate_scene_wgsl for clarity.

    Args:
        scene: FullSceneNode containing all scene components.
        include_uniforms: Whether to include uniform buffer definitions.
        include_bindings: Whether to include bind group definitions.

    Returns:
        Complete WGSL compute shader as a string.
    """
    return generate_scene_wgsl(
        scene,
        include_uniforms=include_uniforms,
        include_bindings=include_bindings,
    )
