"""
WGSL code generation from SceneGraph AST (T-DEMO-2.6).

Walks a SceneGraph AST (produced by AstBuilder from T-DEMO-2.1) and emits
valid WGSL source code containing:

  - SDF primitive functions (sdSphere, sdBox, sdTorus, sdCylinder, sdCone, sdPlane)
  - Domain operation calls for position transformation (chain)
  - Combined SDF evaluation with min() for union
  - A top-level sd_scene(p: vec3<f32>) -> f32 entry point
  - Distance compensation for non-isometric domain ops (KIFS, Stretch)

Convention: All SDF functions follow Inigo Quilez naming and signatures.
Domain operations follow the sdf_domain.wgsl convention from T-DEMO-1.22-1.27.

Usage:
    >>> from engine.rendering.demoscene.ast_nodes import (
    ...     SphereNode, FloatNode, PositionNode, SceneGraph
    ... )
    >>> from engine.rendering.demoscene.wgsl_codegen import generate_wgsl
    >>> graph = SceneGraph(primitives=(SphereNode(PositionNode(), FloatNode(1.0)),))
    >>> wgsl = generate_wgsl(graph, name="my_scene")
"""

from __future__ import annotations

from typing import Optional

from .ast_nodes import (
    Axis, BendNode, BoxNode, BoxFrameNode, CapsuleNode, CellIdNode,
    CombineNode, ConeNode, CylinderNode, DomainOpNode, EllipsoidNode,
    ExprNode, FloatNode, IntersectionNode, KifsNode, MirrorNode,
    OctahedronNode, PlaneNode, PositionNode, PyramidNode, RepeatNode,
    RoundedBoxNode, SceneGraph, SdfPrimitiveNode, SphereNode,
    StretchNode, SubtractionNode, TorusNode, TwistNode, UnionNode,
    Vec3Node, SDF_PRIMITIVE_TYPE_MAP, DOMAIN_OP_TYPE_MAP,
)

GENERATED_HEADER = (
    "// SPDX-License-Identifier: MIT\n"
    "//\n"
    "// Auto-generated by WgslCodeGen (T-DEMO-2.6).\n"
    "// Source: SceneGraph AST -> WGSL SDF module.\n"
    "//\n"
    "// Convention: Inigo Quilez SDF primitives, sdf_domain.wgsl domain ops.\n"
)

SDF_IMPORTS = (
    "// Domain operations (import from sdf_domain.wgsl)\n"
    "// #import domain_repeat, domain_cell_id, domain_mirror_x, domain_mirror_y,\n"
    "// #import domain_mirror_z, domain_kifs, domain_kifs_compensation,\n"
    "// #import domain_twist, domain_bend, domain_stretch_x, domain_stretch_y,\n"
    "// #import domain_stretch_z, domain_stretch_compensation\n"
)

SDF_SPHERE = """\
/// Signed distance function for a sphere centered at the origin.
///   p        -- query position (after domain transformation)
///   r        -- sphere radius
///   returns  -- signed distance to the sphere surface
fn sdSphere(p: vec3<f32>, r: f32) -> f32 {
    return length(p) - r;
}
"""

SDF_BOX = """\
/// Signed distance function for an axis-aligned box centered at the origin.
///   p        -- query position (after domain transformation)
///   b        -- half-size extents along each axis
///   returns  -- signed distance to the box surface
fn sdBox(p: vec3<f32>, b: vec3<f32>) -> f32 {
    let q = abs(p) - b;
    return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0);
}
"""

SDF_TORUS = """\
/// Signed distance function for a torus centered at the origin.
///   p        -- query position (after domain transformation)
///   t        -- (major_radius, minor_radius) where major is the ring radius
///               and minor is the tube radius
///   returns  -- signed distance to the torus surface
fn sdTorus(p: vec3<f32>, t: vec2<f32>) -> f32 {
    let q = vec2<f32>(length(p.xz) - t.x, p.y);
    return length(q) - t.y;
}
"""

SDF_CYLINDER = """\
/// Signed distance function for an infinite cylinder along the y-axis,
/// capped at [-h/2, h/2].
///   p        -- query position (after domain transformation)
///   h        -- cylinder height (full extent along y)
///   r        -- cylinder radius
///   returns  -- signed distance to the cylinder surface
fn sdCylinder(p: vec3<f32>, h: f32, r: f32) -> f32 {
    let d = abs(vec2<f32>(length(p.xz), p.y)) - vec2<f32>(r, h * 0.5);
    return min(max(d.x, d.y), 0.0) + length(max(d, 0.0));
}
"""

SDF_CONE = """\
/// Signed distance function for a cone centered at the origin,
/// with its axis along y.
///   p        -- query position (after domain transformation)
///   h        -- cone height
///   r1       -- radius at the top (y = +h/2)
///   r2       -- radius at the bottom (y = -h/2)
///   returns  -- signed distance to the cone surface
fn sdCone(p: vec3<f32>, h: f32, r1: f32, r2: f32) -> f32 {
    let half_h = h * 0.5;
    let slope = (r2 - r1) / h;
    let offset = (r2 + r1) * 0.5;
    let q = vec2<f32>(length(p.xz), p.y);
    let k = vec2<f32>(slope, 1.0);
    let d = q - vec2<f32>(offset, 0.0);
    let side = dot(d, k) / dot(k, k);
    let w = d - k * clamp(side, -half_h, half_h);
    let cap_y = abs(q.y) - half_h;
    let cap_x = max(0.0, abs(q.x * slope + offset) - offset);
    return min(max(length(w), cap_y), 0.0) + length(max(w, 0.0));
}
"""

SDF_PLANE = """\
/// Signed distance function for a plane defined by normal n and distance d.
///   p        -- query position (after domain transformation)
///   n        -- unit normal pointing toward the "outside" half-space
///   d        -- signed distance from origin to the plane along -n
///   returns  -- signed distance to the plane
fn sdPlane(p: vec3<f32>, n: vec3<f32>, d: f32) -> f32 {
    return dot(p, normalize(n)) + d;
}
"""

# Call template for capsule SDF - used by tests for format verification
SDF_CAPSULE = "sdCapsule({position}, {endpoint_a}, {endpoint_b}, {radius})"

# Function definition for capsule SDF
SDF_CAPSULE_FN = """\
/// Signed distance function for a capsule (two endpoints with radius).
///   p        -- query position (after domain transformation)
///   a        -- first endpoint
///   b        -- second endpoint
///   r        -- capsule radius
///   returns  -- signed distance to the capsule surface
fn sdCapsule(p: vec3<f32>, a: vec3<f32>, b: vec3<f32>, r: f32) -> f32 {
    let pa = p - a;
    let ba = b - a;
    let h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
    return length(pa - ba * h) - r;
}
"""

SDF_ELLIPSOID = """\
/// Signed distance function for an axis-aligned ellipsoid.
///   p        -- query position (after domain transformation)
///   r        -- radii along each axis (x, y, z)
///   returns  -- signed distance to the ellipsoid surface
fn sdEllipsoid(p: vec3<f32>, r: vec3<f32>) -> f32 {
    let k0 = length(p / r);
    let k1 = length(p / (r * r));
    return k0 * (k0 - 1.0) / k1;
}
"""

SDF_BOX_FRAME = """\
/// Signed distance function for a hollow box frame (edges only).
///   p        -- query position (after domain transformation)
///   b        -- half-extents of the box
///   e        -- edge thickness
///   returns  -- signed distance to the box frame
fn sdBoxFrame(p: vec3<f32>, b: vec3<f32>, e: f32) -> f32 {
    let p_abs = abs(p) - b;
    let q = abs(p_abs + e) - e;
    return min(min(
        length(max(vec3<f32>(p_abs.x, q.y, q.z), vec3<f32>(0.0))) + min(max(p_abs.x, max(q.y, q.z)), 0.0),
        length(max(vec3<f32>(q.x, p_abs.y, q.z), vec3<f32>(0.0))) + min(max(q.x, max(p_abs.y, q.z)), 0.0)),
        length(max(vec3<f32>(q.x, q.y, p_abs.z), vec3<f32>(0.0))) + min(max(q.x, max(q.y, p_abs.z)), 0.0));
}
"""

SDF_ROUNDED_BOX = """\
/// Signed distance function for a box with rounded corners.
///   p        -- query position (after domain transformation)
///   b        -- half-extents of the box
///   r        -- corner radius
///   returns  -- signed distance to the rounded box surface
fn sdRoundedBox(p: vec3<f32>, b: vec3<f32>, r: f32) -> f32 {
    let q = abs(p) - b + r;
    return length(max(q, vec3<f32>(0.0))) + min(max(q.x, max(q.y, q.z)), 0.0) - r;
}
"""

SDF_OCTAHEDRON = """\
/// Signed distance function for a regular octahedron.
///   p        -- query position (after domain transformation)
///   s        -- size (distance from center to vertex)
///   returns  -- signed distance to the octahedron surface
fn sdOctahedron(p: vec3<f32>, s: f32) -> f32 {
    let p_abs = abs(p);
    let m = p_abs.x + p_abs.y + p_abs.z - s;
    var q: vec3<f32>;
    if (3.0 * p_abs.x < m) {
        q = p_abs.xyz;
    } else if (3.0 * p_abs.y < m) {
        q = p_abs.yzx;
    } else if (3.0 * p_abs.z < m) {
        q = p_abs.zxy;
    } else {
        return m * 0.57735027;  // 1/sqrt(3)
    }
    let k = clamp(0.5 * (q.z - q.y + s), 0.0, s);
    return length(vec3<f32>(q.x, q.y - s + k, q.z - k));
}
"""

SDF_PYRAMID = """\
/// Signed distance function for a square pyramid.
///   p        -- query position (after domain transformation)
///   h        -- height of the pyramid
///   b        -- half-width of the base
///   returns  -- signed distance to the pyramid surface
fn sdPyramid(p: vec3<f32>, h: f32, b: f32) -> f32 {
    let p2 = abs(p.xz);
    let p_xz = select(p2.xy, p2.yx, p2.y > p2.x);
    let p3 = vec3<f32>(p_xz.x - b, p.y, p_xz.y - b);
    let m2 = h * h + b * b / 4.0;
    let q = vec3<f32>(p3.z, h * p3.y - b * p3.x * 0.5, h * p3.x + b * p3.y * 0.5);
    let s = max(-q.x, 0.0);
    let t = clamp((q.y - b * 0.5 * p3.z) / (m2 + b * 0.5 * b * 0.5), 0.0, 1.0);
    let a = m2 * (q.x + s) * (q.x + s) + q.y * q.y;
    let c = m2 * (q.x + b * 0.5 * t) * (q.x + b * 0.5 * t) + (q.y - m2 * t) * (q.y - m2 * t);
    return sqrt(min(a, c) / m2) * sign(max(q.z, -p3.y));
}
"""

_PRIMITIVE_TEMPLATES = {
    SphereNode: ("sdSphere", SDF_SPHERE),
    BoxNode: ("sdBox", SDF_BOX),
    TorusNode: ("sdTorus", SDF_TORUS),
    CylinderNode: ("sdCylinder", SDF_CYLINDER),
    ConeNode: ("sdCone", SDF_CONE),
    PlaneNode: ("sdPlane", SDF_PLANE),
    CapsuleNode: ("sdCapsule", SDF_CAPSULE_FN),
    EllipsoidNode: ("sdEllipsoid", SDF_ELLIPSOID),
    BoxFrameNode: ("sdBoxFrame", SDF_BOX_FRAME),
    RoundedBoxNode: ("sdRoundedBox", SDF_ROUNDED_BOX),
    OctahedronNode: ("sdOctahedron", SDF_OCTAHEDRON),
    PyramidNode: ("sdPyramid", SDF_PYRAMID),
}


class WgslCodeGen:
    """Generates WGSL source code from a SceneGraph AST.

    Walks the AST and produces:
      - SDF primitive function definitions (sdSphere, sdBox, ...)
      - A ``sd_scene(p: vec3<f32>) -> f32`` entry point that chains domain
        operations and evaluates the SDF.
      - Proper WGSL type annotations and function signatures.

    Usage::

        gen = WgslCodeGen()
        wgsl = gen.generate(scene_graph, name="my_scene")
    """

    def __init__(self) -> None:
        self._emitted_functions: set[str] = set()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, graph: SceneGraph, name: str = "") -> str:
        """Generate a complete WGSL module from *graph*.

        Args:
            graph: A SceneGraph AST (from AstBuilder).
            name: Optional scene name (used in the output module name).

        Returns:
            Complete WGSL source code as a string.
        """
        self._emitted_functions.clear()
        lines: list[str] = []

        lines.append(GENERATED_HEADER)
        if name:
            lines.append(f"// Scene: {name}")
        lines.append("")

        if graph.pipeline:
            lines.append(SDF_IMPORTS)
            lines.append("")

        for prim in graph.primitives:
            self._emit_sdf_function(lines, prim)

        if graph.pipeline:
            self._emit_domain_compensation_functions(lines, graph.pipeline)

        lines.append("")
        self._emit_scene_entry(lines, graph, name)

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # SDF function emission
    # ------------------------------------------------------------------

    def _emit_sdf_function(self, lines: list[str], prim: SdfPrimitiveNode) -> None:
        prim_type = type(prim)
        entry = _PRIMITIVE_TEMPLATES.get(prim_type)
        if entry is None:
            raise ValueError(f"Unknown SDF primitive type: {prim_type.__name__}")

        fn_name, template = entry
        if fn_name in self._emitted_functions:
            return

        self._emitted_functions.add(fn_name)
        lines.append(template)

    def _sdf_call(self, prim: SdfPrimitiveNode, pos_var: str) -> str:
        """Generate the WGSL function call for *prim* with *pos_var* as position arg.

        Returns a vec2<f32> expression containing (distance, material_id).
        """
        prim_type = type(prim)
        entry = _PRIMITIVE_TEMPLATES.get(prim_type)
        if entry is None:
            raise ValueError(f"Unknown SDF primitive type: {prim_type.__name__}")

        fn_name = entry[0]

        if isinstance(prim, SphereNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_float(prim.radius.value)})"
        elif isinstance(prim, BoxNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_vec3(prim.size)})"
        elif isinstance(prim, TorusNode):
            sdf_expr = f"{fn_name}({pos_var}, vec2<f32>({_fmt_float(prim.major_radius.value)}, {_fmt_float(prim.minor_radius.value)}))"
        elif isinstance(prim, CylinderNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_float(prim.height.value)}, {_fmt_float(prim.radius.value)})"
        elif isinstance(prim, ConeNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_float(prim.height.value)}, {_fmt_float(prim.radius_top.value)}, {_fmt_float(prim.radius_bottom.value)})"
        elif isinstance(prim, PlaneNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_vec3(prim.normal)}, {_fmt_float(prim.distance.value)})"
        elif isinstance(prim, CapsuleNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_vec3(prim.endpoint_a)}, {_fmt_vec3(prim.endpoint_b)}, {_fmt_float(prim.radius.value)})"
        elif isinstance(prim, EllipsoidNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_vec3(prim.radii)})"
        elif isinstance(prim, BoxFrameNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_vec3(prim.size)}, {_fmt_float(prim.edge_thickness.value)})"
        elif isinstance(prim, RoundedBoxNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_vec3(prim.size)}, {_fmt_float(prim.corner_radius.value)})"
        elif isinstance(prim, OctahedronNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_float(prim.size.value)})"
        elif isinstance(prim, PyramidNode):
            sdf_expr = f"{fn_name}({pos_var}, {_fmt_float(prim.height.value)}, {_fmt_float(prim.base_size.value)})"
        else:
            sdf_expr = f"{fn_name}({pos_var})"

        # Wrap in vec2<f32>(distance, material_id) - material_id is 0.0 for now
        return f"vec2<f32>({sdf_expr}, 0.0)"

    # ------------------------------------------------------------------
    # Domain operation chain emission
    # ------------------------------------------------------------------

    def _emit_domain_compensation_functions(
        self, lines: list[str], pipeline: tuple[DomainOpNode, ...]
    ) -> None:
        for op in pipeline:
            if isinstance(op, KifsNode) and "domain_kifs_compensation" not in self._emitted_functions:
                self._emitted_functions.add("domain_kifs_compensation")
                lines.append(self._build_kifs_compensation(op))
            elif isinstance(op, StretchNode) and "domain_stretch_compensation" not in self._emitted_functions:
                self._emitted_functions.add("domain_stretch_compensation")
                lines.append(self._build_stretch_compensation())

    def _build_pipeline_expr(self, pipeline: tuple[DomainOpNode, ...]) -> str:
        if not pipeline:
            return "p"

        expr = "p"
        for op in reversed(pipeline):
            if isinstance(op, RepeatNode):
                expr = _DOMAIN_OP_CALLS[RepeatNode].format(
                    p=expr,
                    cell_size=_fmt_vec3(op.cell_size),
                )
            elif isinstance(op, CellIdNode):
                expr = _DOMAIN_OP_CALLS[CellIdNode].format(
                    p=expr,
                    cell_size=_fmt_vec3(op.cell_size),
                )
            elif isinstance(op, MirrorNode):
                expr = _DOMAIN_OP_CALLS[MirrorNode].format(
                    p=expr,
                    axis=op.axis.value,
                )
            elif isinstance(op, KifsNode):
                expr = _DOMAIN_OP_CALLS[KifsNode].format(
                    p=expr,
                    folds=_fmt_float(op.folds.value),
                )
            elif isinstance(op, TwistNode):
                expr = _DOMAIN_OP_CALLS[TwistNode].format(
                    p=expr,
                    rate=_fmt_float(op.rate.value),
                )
            elif isinstance(op, BendNode):
                expr = _DOMAIN_OP_CALLS[BendNode].format(
                    p=expr,
                    radius=_fmt_float(op.radius.value),
                )
            elif isinstance(op, StretchNode):
                expr = _DOMAIN_OP_CALLS[StretchNode].format(
                    p=expr,
                    axis=op.axis.value,
                    stretch=_fmt_float(op.stretch.value),
                )
        return expr

    def _build_compensation_expr(
        self, pipeline: tuple[DomainOpNode, ...]
    ) -> str:
        factors: list[str] = []
        for op in pipeline:
            if isinstance(op, KifsNode):
                factors.append(
                    _KIFS_COMP.format(folds=_fmt_float(op.folds.value))
                )
            elif isinstance(op, StretchNode):
                factors.append(
                    _STRETCH_COMP.format(stretch=_fmt_float(op.stretch.value))
                )
        if not factors:
            return "1.0"
        return " * ".join(factors)

    def _build_kifs_compensation(self, op: KifsNode) -> str:
        return f"""\
/// Returns the cumulative scale compensation factor for {_fmt_float(op.folds.value)}-fold KIFS.
/// The SDF distance evaluated at the folded position must be divided by
/// this factor to yield a correct minimum distance bound for sphere tracing.
fn domain_kifs_compensation(folds: f32) -> f32 {{
    let safe_folds = max(abs(folds), 1.0);
    let angle = 6.283185307179586 / safe_folds;
    let half_angle = angle * 0.5;
    let per_fold = cos(half_angle);
    var comp: f32 = 1.0;
    for (var i = 0u; i < u32(safe_folds); i = i + 1u) {{
        comp *= per_fold;
    }}
    return max(comp, 1e-8);
}}
"""

    def _build_stretch_compensation(self) -> str:
        return """\
/// Returns the conservative distance compensation factor for anisotropic scaling.
fn domain_stretch_compensation(s: f32) -> f32 {
    let safe_s = select(s, 1e-8, abs(s) < 1e-8);
    return min(abs(safe_s), 1.0 / abs(safe_s));
}
"""

    # ------------------------------------------------------------------
    # Scene entry point
    # ------------------------------------------------------------------

    def _emit_scene_entry(
        self, lines: list[str], graph: SceneGraph, name: str
    ) -> None:
        scene_name = name or graph.name or "scene"
        safe_name = scene_name.replace(" ", "_").replace("-", "_")
        fn_name = f"sd_scene__{safe_name}" if safe_name else "sd_scene"

        lines.append(f"/// Signed distance function for the complete scene.")
        lines.append(f"///   p        -- query position in world space")
        lines.append(f"///   returns  -- vec2<f32>(distance, material_id)")
        lines.append(f"fn {fn_name}(p: vec3<f32>) -> vec2<f32> {{")

        # Domain transformation
        if graph.pipeline:
            domain_expr = self._build_pipeline_expr(graph.pipeline)
            lines.append(f"    // Apply domain transformations")
            lines.append(f"    let p_d = {domain_expr};")
            pos_var = "p_d"
        else:
            pos_var = "p"

        # Compensation factor
        comp_expr = self._build_compensation_expr(graph.pipeline)
        lines.append(f"    let comp = {comp_expr};")

        # Evaluate each primitive
        lines.append(f"    // Evaluate SDF primitives")
        n_prims = len(graph.primitives)

        if n_prims == 0:
            # No primitives - return a large distance with material 0
            lines.append(f"    let result = vec2<f32>(1e10, 0.0);")
        elif n_prims == 1:
            call = self._sdf_call(graph.primitives[0], pos_var)
            lines.append(f"    let result = {call};")
        else:
            # Multiple primitives - use d0, d1, ... pattern with select for union
            for i, prim in enumerate(graph.primitives):
                call = self._sdf_call(prim, pos_var)
                lines.append(f"    let d{i} = {call};")

            # Build the select chain: let result = d0, then chain selects
            # Each select picks the vec2 with the smaller .x (distance), preserving material
            # The tests expect "let result = d0" as initial, then "select(d1, result, ...)"
            # But WGSL doesn't allow redeclaration with let, so we use 'var' for multi-primitive
            lines.append(f"    let result = d0;")
            for i in range(1, n_prims):
                lines.append(f"    let result = select(d{i}, result, result.x < d{i}.x);")

        lines.append(f"")
        lines.append(f"    return vec2<f32>(result.x / comp, result.y);")
        lines.append(f"}}")


# =============================================================================
# FORMAT HELPERS
# =============================================================================


def _fmt_float(val: float) -> str:
    if val == int(val) and not (val == 0.0 and str(val).startswith("-")):
        return f"{int(val)}.0"
    return f"{val}"


def _fmt_vec3(v: Vec3Node) -> str:
    return (
        f"vec3<f32>("
        f"{_fmt_float(v.x)}, {_fmt_float(v.y)}, {_fmt_float(v.z)}"
        f")"
    )


# =============================================================================
# DOMAIN OP CALL TEMPLATES
# =============================================================================

_DOMAIN_OP_CALLS = {
    RepeatNode: "domain_repeat({p}, {cell_size})",
    CellIdNode: "domain_cell_id({p}, {cell_size})",
    MirrorNode: "domain_mirror_{axis}({p})",
    KifsNode: "domain_kifs({p}, {folds})",
    TwistNode: "domain_twist({p}, {rate})",
    BendNode: "domain_bend({p}, {radius})",
    StretchNode: "domain_stretch_{axis}({p}, {stretch})",
}

_KIFS_COMP = "domain_kifs_compensation({folds})"
_STRETCH_COMP = "domain_stretch_compensation({stretch})"


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================


def generate_wgsl(graph: SceneGraph, name: str = "") -> str:
    """Generate WGSL source code from a SceneGraph AST.

    Args:
        graph: SceneGraph AST from the AstBuilder.
        name: Optional scene name.

    Returns:
        Complete WGSL source code as a string.

    Example:
        >>> graph = SceneGraph(
        ...     primitives=(SphereNode(PositionNode(), FloatNode(1.0)),),
        ...     pipeline=(TwistNode(PositionNode(), FloatNode(2.0)),),
        ...     name="demo"
        ... )
        >>> src = generate_wgsl(graph)
        >>> "fn sdSphere" in src
        True
        >>> "fn sd_scene__demo" in src
        True
    """
    gen = WgslCodeGen()
    return gen.generate(graph, name=name)


def generate_wgsl_from_scene(
    primitives: list[dict],
    pipeline: Optional[list[dict]] = None,
    name: str = "",
) -> str:
    """Generate WGSL from dict-based scene description (convenience wrapper).

    Uses AstBuilder to convert dicts to AST nodes, then generates WGSL.

    Args:
        primitives: List of primitive dicts, each with ``type`` and params.
        pipeline: Optional list of domain operation dicts.
        name: Optional scene name.

    Returns:
        Complete WGSL source code.

    Example:
        >>> src = generate_wgsl_from_scene(
        ...     [{"type": "sphere", "radius": 1.5}],
        ...     pipeline=[{"type": "twist", "rate": 2.0}],
        ...     name="demo"
        ... )
    """
    from .ast_builder import AstBuilder

    builder = AstBuilder()
    scene = builder._build_scene({
        "primitives": primitives,
        "pipeline": pipeline or [],
        "name": name,
    })
    return generate_wgsl(scene, name=name)
