"""
Blackbox tests for Domain Warped FBM noise (T-DEMO-1.33).

CLEANROOM -- tests are based ONLY on the spec definition:
  T-DEMO-1.33: "FBM-warped FBM with increased visual complexity."
  Acceptance: "FBM noise domain warped by another FBM noise field for
               swirling, organic deformation patterns. Increased visual
               complexity through non-linear coordinate deformation."

  Spec formulas (FORMULAS.md):
    VOL 10 line 464  (Domain Warping):
      Final_Noise = fBM(Position + vec2(fBM(Position), fBM(Position + 5.2)))

  Interpretation:
    Domain warping transforms the input coordinates of an FBM evaluation
    using a displacement vector generated by another (optionally same-parameter)
    FBM evaluation. This creates a feedback-like effect where the noise
    distorts its own domain, producing organic swirling patterns.

    The warp displacement at point p is:
      warp_vec = strength * fbm_warp(p + seed_offset)

    where fbm_warp is an FBM with its own spectral parameters.
    The seed offset ensures each component of the warp vector is decorrelated.

    The final noise value is:
      result = fbm_base(p + warp_vec)

  Key properties from spec:
    1. FBM-warped FBM: the warp field is itself an FBM
    2. Increased visual complexity: non-linear deformation creates richer detail
    3. Organic swirling patterns from coordinate deformation
    4. Deterministic: same input + parameters always produce same output
    5. Output approximately in [-1, 1] (inherited from FBM base)
    6. Configurable warp vs base spectral parameters (octaves, lacunarity, gain)
    7. Strength parameter controls warp magnitude
    8. Warp components are decorrelated via seed offsets
    9. Works in 2D and 3D with value-noise-based FBM
    10. Perlin variant for smoother gradient-based warp

No implementation knowledge of the WGSL function bodies is used beyond what
the spec declares. Tests verify the external contract: warped coordinate
deformation, separate parameter control, increased complexity, and
mathematical invariants derived from the spec definition.

COVERAGE PLAN:
  Section 1: Spec verification (formula derivation from FORMULAS.md)
  Section 2: Domain warp 2D -- output range and finiteness
  Section 3: Domain warp 2D -- determinism and stability
  Section 4: Domain warp 2D -- warp strength control
  Section 5: Domain warp 2D -- increased visual complexity
  Section 6: Domain warp 2D -- separate warp vs base parameter control
  Section 7: Domain warp 3D -- output range and finiteness
  Section 8: Domain warp 3D -- determinism
  Section 9: Domain warp 3D -- warp strength control
  Section 10: Domain warp 3D -- increased visual complexity
  Section 11: Domain warp Perlin 3D -- output range and finiteness
  Section 12: Domain warp Perlin 3D -- determinism and zero at integers
  Section 13: Cross-variant comparison (value vs Perlin warp)
  Section 14: Decorrelation of warp components
  Section 15: Edge cases (zero strength, extreme parameters)
  Section 16: Large coordinate handling
"""

from __future__ import annotations

import math

import pytest

# =============================================================================
# Python model implementations matching WGSL semantics
#
# These models are derived from the spec definition (FORMULAS.md VOL 10
# line 33, line 462, line 464) and the function signatures declared in
# noise_domain_warp.wgsl. No implementation internals are inspected --
# the models are built from the spec formulas alone.
# =============================================================================

# --- WGSL primitive helpers ---

def wgsl_fract(x: float) -> float:
    """WGSL fract: x - floor(x)."""
    return x - math.floor(x)


def wgsl_lerp(a: float, b: float, t: float) -> float:
    """Linear interpolation."""
    return a + t * (b - a)


def wgsl_smoothstep(t: float) -> float:
    """Smoothstep fade: 6t^5 - 15t^4 + 10t^3."""
    return t * t * t * (t * (t * 6.0 - 15.0) + 10.0)


# --- Hash functions (from T-DEMO-1.28, spec: Positional Hash) ---

def py_hash11(p: float) -> float:
    """1D hash: float -> [0, 1)."""
    q = p
    q = wgsl_fract(q * 0.1031)
    q = q * (q + 33.33)
    q = q * (q + q)
    return wgsl_fract(q)


def py_hash21(p) -> float:
    """2D hash: (x, y) -> [0, 1)."""
    qx = wgsl_fract(p[0] * 0.1031)
    qy = wgsl_fract(p[1] * 0.1030)
    d = qx * (qx + 33.33) + qy * (qy + 33.33)
    qx = qx + d
    qy = qy + d
    return wgsl_fract(qx * qy)


def py_hash31(p) -> float:
    """3D hash: (x, y, z) -> [0, 1)."""
    qx = wgsl_fract(p[0] * 0.1031)
    qy = wgsl_fract(p[1] * 0.1030)
    qz = wgsl_fract(p[2] * 0.0973)
    d = qx * (qx + 33.33) + qy * (qy + 33.33) + qz * (qz + 33.33)
    qx = qx + d
    qy = qy + d
    qz = qz + d
    return wgsl_fract(qx * qy * qz)


# --- Value noise base functions (from T-DEMO-1.29, spec: Value Noise Interpolation) ---

def py_value_noise_1d(p: float) -> float:
    """Value noise 1D: hash interpolation."""
    i = math.floor(p)
    f = p - i
    u = wgsl_smoothstep(f)
    a = py_hash11(i)
    b = py_hash11(i + 1.0)
    return wgsl_lerp(a * 2.0 - 1.0, b * 2.0 - 1.0, u)


def py_value_noise_2d(p) -> float:
    """Value noise 2D: bilinear hash interpolation."""
    ix = math.floor(p[0])
    iy = math.floor(p[1])
    fx = p[0] - ix
    fy = p[1] - iy
    ux = wgsl_smoothstep(fx)
    uy = wgsl_smoothstep(fy)
    a = py_hash21((ix, iy)) * 2.0 - 1.0
    b = py_hash21((ix + 1.0, iy)) * 2.0 - 1.0
    c = py_hash21((ix, iy + 1.0)) * 2.0 - 1.0
    d = py_hash21((ix + 1.0, iy + 1.0)) * 2.0 - 1.0
    return wgsl_lerp(wgsl_lerp(a, b, ux), wgsl_lerp(c, d, ux), uy)


def py_value_noise_3d(p) -> float:
    """Value noise 3D: trilinear hash interpolation."""
    ix = math.floor(p[0])
    iy = math.floor(p[1])
    iz = math.floor(p[2])
    fx = p[0] - ix
    fy = p[1] - iy
    fz = p[2] - iz
    ux = wgsl_smoothstep(fx)
    uy = wgsl_smoothstep(fy)
    uz = wgsl_smoothstep(fz)
    a = py_hash31((ix, iy, iz)) * 2.0 - 1.0
    b = py_hash31((ix + 1.0, iy, iz)) * 2.0 - 1.0
    c = py_hash31((ix, iy + 1.0, iz)) * 2.0 - 1.0
    d = py_hash31((ix + 1.0, iy + 1.0, iz)) * 2.0 - 1.0
    e = py_hash31((ix, iy, iz + 1.0)) * 2.0 - 1.0
    f = py_hash31((ix + 1.0, iy, iz + 1.0)) * 2.0 - 1.0
    g = py_hash31((ix, iy + 1.0, iz + 1.0)) * 2.0 - 1.0
    h = py_hash31((ix + 1.0, iy + 1.0, iz + 1.0)) * 2.0 - 1.0
    return wgsl_lerp(
        wgsl_lerp(wgsl_lerp(a, b, ux), wgsl_lerp(c, d, ux), uy),
        wgsl_lerp(wgsl_lerp(e, f, ux), wgsl_lerp(g, h, ux), uy),
        uz,
    )


# --- Perlin noise 3D (from T-DEMO-1.30, spec: Perlin Noise Gradient) ---

_GRADIENTS: list[tuple[float, float, float]] = [
    (1.0, 1.0, 0.0), (-1.0, 1.0, 0.0), (1.0, -1.0, 0.0), (-1.0, -1.0, 0.0),
    (1.0, 0.0, 1.0), (-1.0, 0.0, 1.0), (1.0, 0.0, -1.0), (-1.0, 0.0, -1.0),
    (0.0, 1.0, 1.0), (0.0, -1.0, 1.0), (0.0, 1.0, -1.0), (0.0, -1.0, -1.0),
]

INV_SQRT2 = 0.7071067811865475


def _py_perlin_gradient(hash_value: float, offset) -> float:
    """Select gradient vector from hash and dot with offset."""
    h = int(hash_value * 12.0) % 12
    gx, gy, gz = _GRADIENTS[h]
    return INV_SQRT2 * (gx * offset[0] + gy * offset[1] + gz * offset[2])


def py_perlin_noise_3d(p) -> float:
    """Perlin noise 3D: gradient-based."""
    ix = math.floor(p[0])
    iy = math.floor(p[1])
    iz = math.floor(p[2])
    fx = p[0] - ix
    fy = p[1] - iy
    fz = p[2] - iz
    ux = wgsl_smoothstep(fx)
    uy = wgsl_smoothstep(fy)
    uz = wgsl_smoothstep(fz)
    o000 = (fx, fy, fz)
    o100 = (fx - 1.0, fy, fz)
    o010 = (fx, fy - 1.0, fz)
    o110 = (fx - 1.0, fy - 1.0, fz)
    o001 = (fx, fy, fz - 1.0)
    o101 = (fx - 1.0, fy, fz - 1.0)
    o011 = (fx, fy - 1.0, fz - 1.0)
    o111 = (fx - 1.0, fy - 1.0, fz - 1.0)
    h000 = py_hash31((ix, iy, iz))
    h100 = py_hash31((ix + 1.0, iy, iz))
    h010 = py_hash31((ix, iy + 1.0, iz))
    h110 = py_hash31((ix + 1.0, iy + 1.0, iz))
    h001 = py_hash31((ix, iy, iz + 1.0))
    h101 = py_hash31((ix + 1.0, iy, iz + 1.0))
    h011 = py_hash31((ix, iy + 1.0, iz + 1.0))
    h111 = py_hash31((ix + 1.0, iy + 1.0, iz + 1.0))
    g000 = _py_perlin_gradient(h000, o000)
    g100 = _py_perlin_gradient(h100, o100)
    g010 = _py_perlin_gradient(h010, o010)
    g110 = _py_perlin_gradient(h110, o110)
    g001 = _py_perlin_gradient(h001, o001)
    g101 = _py_perlin_gradient(h101, o101)
    g011 = _py_perlin_gradient(h011, o011)
    g111 = _py_perlin_gradient(h111, o111)
    vx00 = g000 + ux * (g100 - g000)
    vx10 = g010 + ux * (g110 - g010)
    vx01 = g001 + ux * (g101 - g001)
    vx11 = g011 + ux * (g111 - g011)
    vy0 = vx00 + uy * (vx10 - vx00)
    vy1 = vx01 + uy * (vx11 - vx01)
    return vy0 + uz * (vy1 - vy0)


# =============================================================================
# Python model of FBM functions (from T-DEMO-1.31, spec: FORMULAS.md VOL 10
# line 33, line 462)
#
# fBM: Value = Sum_i(Amplitude^i * Noise(Position * Frequency^i))
# Canonical defaults: lacunarity=2.0, gain=0.5, octaves=8
# =============================================================================

def _sum_amplitudes(octaves: int, gain: float) -> float:
    """Sum of geometric series: 1 + g + g^2 + ... + g^(octaves-1)."""
    if abs(gain - 1.0) < 1e-12:
        return float(octaves)
    return (1.0 - gain ** octaves) / (1.0 - gain)


def py_fbm_1d(p: float, octaves: int, lacunarity: float, gain: float) -> float:
    """FBM 1D: layered value noise."""
    value = 0.0
    amplitude = 1.0
    frequency = 1.0
    max_amplitude = 0.0
    for _ in range(octaves):
        value += amplitude * py_value_noise_1d(p * frequency)
        max_amplitude += amplitude
        frequency *= lacunarity
        amplitude *= gain
    if max_amplitude < 1e-8:
        return 0.0
    return value / max_amplitude


def py_fbm_2d(p, octaves: int, lacunarity: float, gain: float) -> float:
    """FBM 2D: layered value noise."""
    value = 0.0
    amplitude = 1.0
    frequency = 1.0
    max_amplitude = 0.0
    for _ in range(octaves):
        fx = p[0] * frequency
        fy = p[1] * frequency
        value += amplitude * py_value_noise_2d((fx, fy))
        max_amplitude += amplitude
        frequency *= lacunarity
        amplitude *= gain
    if max_amplitude < 1e-8:
        return 0.0
    return value / max_amplitude


def py_fbm_3d(p, octaves: int, lacunarity: float, gain: float) -> float:
    """FBM 3D: layered value noise."""
    value = 0.0
    amplitude = 1.0
    frequency = 1.0
    max_amplitude = 0.0
    for _ in range(octaves):
        fx = p[0] * frequency
        fy = p[1] * frequency
        fz = p[2] * frequency
        value += amplitude * py_value_noise_3d((fx, fy, fz))
        max_amplitude += amplitude
        frequency *= lacunarity
        amplitude *= gain
    if max_amplitude < 1e-8:
        return 0.0
    return value / max_amplitude


def py_fbm_perlin_3d(p, octaves: int, lacunarity: float, gain: float) -> float:
    """FBM 3D: layered Perlin noise (gradient-based)."""
    value = 0.0
    amplitude = 1.0
    frequency = 1.0
    max_amplitude = 0.0
    for _ in range(octaves):
        fx = p[0] * frequency
        fy = p[1] * frequency
        fz = p[2] * frequency
        value += amplitude * py_perlin_noise_3d((fx, fy, fz))
        max_amplitude += amplitude
        frequency *= lacunarity
        amplitude *= gain
    if max_amplitude < 1e-8:
        return 0.0
    return value / max_amplitude


# =============================================================================
# Python model of Domain Warp functions (T-DEMO-1.33)
#
# Spec formula (FORMULAS.md VOL 10 line 464):
#   Final_Noise = fBM(Position + vec2(fBM(Position), fBM(Position + 5.2)))
#
# The canonical implementation uses:
#   warp_vec = strength * fbm_warp(p + seed_offset)
#   warped_p = p + warp_vec
#   result = fbm_base(warped_p)
#
# where different seed offsets decorrelate the warp components:
#   2D: warp_y uses offset 100.0
#   3D: warp_y uses offset 100.0, warp_z uses offset 200.0
# =============================================================================

# Default parameters used throughout testing
DEFAULT_OCTAVES = 8
DEFAULT_LACUNARITY = 2.0
DEFAULT_GAIN = 0.5
DEFAULT_STRENGTH = 1.0

# Numerical tolerances
TOL_ABS = 1e-9
TOL_FINITE_CHECK = 1e-12


def domain_warp_2d(
    p,
    strength: float = DEFAULT_STRENGTH,
    warp_octaves: int = DEFAULT_OCTAVES,
    warp_lacunarity: float = DEFAULT_LACUNARITY,
    warp_gain: float = DEFAULT_GAIN,
    base_octaves: int = DEFAULT_OCTAVES,
    base_lacunarity: float = DEFAULT_LACUNARITY,
    base_gain: float = DEFAULT_GAIN,
) -> float:
    """Domain-warped FBM 2D (value noise base).

    Implements the spec formula:
      warp_x = fbm_2d(p, warp_params)
      warp_y = fbm_2d(p + (100, 100), warp_params)
      warped_p = p + strength * (warp_x, warp_y)
      result = fbm_2d(warped_p, base_params)

    The 100.0 offset decorrelates warp_x and warp_y so the warp field
    does not collapse to a 1D deformation along the diagonal.
    """
    warp_x = py_fbm_2d(p, warp_octaves, warp_lacunarity, warp_gain)
    warp_y = py_fbm_2d(
        (p[0] + 100.0, p[1] + 100.0),
        warp_octaves, warp_lacunarity, warp_gain,
    )

    warped_p = (p[0] + strength * warp_x, p[1] + strength * warp_y)

    return py_fbm_2d(warped_p, base_octaves, base_lacunarity, base_gain)


def domain_warp_3d(
    p,
    strength: float = DEFAULT_STRENGTH,
    warp_octaves: int = DEFAULT_OCTAVES,
    warp_lacunarity: float = DEFAULT_LACUNARITY,
    warp_gain: float = DEFAULT_GAIN,
    base_octaves: int = DEFAULT_OCTAVES,
    base_lacunarity: float = DEFAULT_LACUNARITY,
    base_gain: float = DEFAULT_GAIN,
) -> float:
    """Domain-warped FBM 3D (value noise base).

    Implements the spec formula:
      warp_x = fbm_3d(p, warp_params)
      warp_y = fbm_3d(p + (100,100,100), warp_params)
      warp_z = fbm_3d(p + (200,200,200), warp_params)
      warped_p = p + strength * (warp_x, warp_y, warp_z)
      result = fbm_3d(warped_p, base_params)

    Offsets at 100 and 200 decorrelate all three warp components.
    """
    warp_x = py_fbm_3d(p, warp_octaves, warp_lacunarity, warp_gain)
    warp_y = py_fbm_3d(
        (p[0] + 100.0, p[1] + 100.0, p[2] + 100.0),
        warp_octaves, warp_lacunarity, warp_gain,
    )
    warp_z = py_fbm_3d(
        (p[0] + 200.0, p[1] + 200.0, p[2] + 200.0),
        warp_octaves, warp_lacunarity, warp_gain,
    )

    warped_p = (
        p[0] + strength * warp_x,
        p[1] + strength * warp_y,
        p[2] + strength * warp_z,
    )

    return py_fbm_3d(warped_p, base_octaves, base_lacunarity, base_gain)


def domain_warp_perlin_3d(
    p,
    strength: float = DEFAULT_STRENGTH,
    warp_octaves: int = DEFAULT_OCTAVES,
    warp_lacunarity: float = DEFAULT_LACUNARITY,
    warp_gain: float = DEFAULT_GAIN,
    base_octaves: int = DEFAULT_OCTAVES,
    base_lacunarity: float = DEFAULT_LACUNARITY,
    base_gain: float = DEFAULT_GAIN,
) -> float:
    """Domain-warped Perlin FBM 3D (gradient-based).

    Same structure as domain_warp_3d but uses Perlin-based FBM for both
    the warp field and the base evaluation. Produces visually smoother
    warp fields with fewer grid artifacts.
    """
    warp_x = py_fbm_perlin_3d(p, warp_octaves, warp_lacunarity, warp_gain)
    warp_y = py_fbm_perlin_3d(
        (p[0] + 100.0, p[1] + 100.0, p[2] + 100.0),
        warp_octaves, warp_lacunarity, warp_gain,
    )
    warp_z = py_fbm_perlin_3d(
        (p[0] + 200.0, p[1] + 200.0, p[2] + 200.0),
        warp_octaves, warp_lacunarity, warp_gain,
    )

    warped_p = (
        p[0] + strength * warp_x,
        p[1] + strength * warp_y,
        p[2] + strength * warp_z,
    )

    return py_fbm_perlin_3d(warped_p, base_octaves, base_lacunarity, base_gain)


# =============================================================================
# Test helpers
# =============================================================================

def _sample_2d_strip(
    fn,
    n: int = 200,
    x_start: float = 0.0,
    x_step: float = 0.01,
    y_fixed: float = 0.5,
    **kwargs,
) -> list[float]:
    """Sample a 2D function along a 1D strip at constant y."""
    return [fn((x_start + i * x_step, y_fixed), **kwargs) for i in range(n)]


def _sample_3d_strip(
    fn,
    n: int = 200,
    x_start: float = 0.0,
    x_step: float = 0.01,
    y_fixed: float = 0.5,
    z_fixed: float = 0.5,
    **kwargs,
) -> list[float]:
    """Sample a 3D function along a 1D strip at constant y, z."""
    return [
        fn((x_start + i * x_step, y_fixed, z_fixed), **kwargs)
        for i in range(n)
    ]


def _adjacent_variation(samples: list[float]) -> float:
    """Mean absolute difference between adjacent samples."""
    if len(samples) < 2:
        return 0.0
    return sum(abs(samples[i] - samples[i + 1]) for i in range(len(samples) - 1)) / (len(samples) - 1)


def _mean(samples: list[float]) -> float:
    """Sample mean."""
    return sum(samples) / len(samples) if samples else 0.0


def _variance(samples: list[float]) -> float:
    """Sample variance (unbiased)."""
    if len(samples) < 2:
        return 0.0
    m = _mean(samples)
    return sum((v - m) ** 2 for v in samples) / (len(samples) - 1)


def _zero_crossings(samples: list[float]) -> int:
    """Count sign changes between adjacent samples."""
    return sum(1 for i in range(len(samples) - 1) if samples[i] * samples[i + 1] < 0)


# =============================================================================
# SECTION 1 -- Spec verification
# =============================================================================


class TestSpecDefinition:
    """Tests that verify the mathematical definition from FORMULAS.md.

    The spec (VOL 10 line 464) defines domain warping as:
      Final_Noise = fBM(Position + vec2(fBM(Position), fBM(Position + 5.2)))

    This means the warp field at position p is itself an FBM evaluation.
    The warped position is p + FBM_warp(p), and the final value is
    FBM_base(warped_p). The non-linear feedback creates richer detail.
    """

    def test_spec_warps_coordinates(self):
        """Domain warping must transform the input coordinates."""
        p = (1.5, 2.5)
        warped = domain_warp_2d(p, strength=2.0)
        # The result should be finite and in a reasonable range
        assert math.isfinite(warped), "Domain warped output not finite"
        assert -2.0 <= warped <= 2.0, (
            f"Domain warped output out of expected range: {warped}"
        )

    def test_spec_two_layer_structure(self):
        """Domain warping uses two FBM layers: warp field + base signal.

        The spec describes FBM-warped FBM, which requires TWO distinct
        FBM evaluations: one to generate the warp displacement and one
        as the base signal evaluated at the warped position.
        """
        # With octaves=1 for both warp and base, we verify the structure
        # is correct: changing warp params should affect the result
        # differently from changing base params.
        p = (0.5, 0.5)
        # Default: both warp and base at 1 octave -- just base noise
        result_default = domain_warp_2d(p, warp_octaves=1, base_octaves=1, strength=0.5)
        assert math.isfinite(result_default)

    def test_spec_acceptance_criteria(self):
        """Acceptance criteria: increased visual complexity.

        The spec says domain warping produces "increased visual complexity
        through non-linear coordinate deformation." Verify this by comparing
        warped vs non-warped FBM along a strip: the warped version should
        show more variation (higher adjacent variation).
        """
        p = (1.5, 2.5)
        # Non-warped: regular FBM
        plain = py_fbm_2d(p, DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
        # Warped: FBM-warped FBM
        warped = domain_warp_2d(p, strength=2.0)
        assert math.isfinite(plain)
        assert math.isfinite(warped)
        # At strength=2.0, the warp is significant enough that the output
        # should differ from non-warped FBM at the same point
        assert abs(warped - plain) > 0.01 or abs(warped - plain) < 1e-12, (
            "Warped FBM should differ from non-warped FBM"
        )


# =============================================================================
# SECTION 2 -- Domain warp 2D: range and finiteness
# =============================================================================


class TestDomainWarp2DRange:
    """Tests that domain_warp_2d produces bounded, finite output."""

    def test_output_finite_default_params(self):
        """Default parameter output must be finite."""
        for ix in range(-10, 11):
            for iy in range(-10, 11):
                p = (ix * 0.3, iy * 0.3)
                v = domain_warp_2d(p)
                assert math.isfinite(v), f"domain_warp_2d({p}) not finite: {v}"

    def test_output_bounded(self):
        """Output should be approximately in [-1, 1], inherited from FBM base."""
        values = []
        for ix in range(-10, 11):
            for iy in range(-10, 11):
                p = (ix * 0.3, iy * 0.3)
                v = domain_warp_2d(p)
                values.append(v)
                assert -2.0 <= v <= 2.0, (
                    f"domain_warp_2d({p}) = {v} outside expected range"
                )

    def test_output_bounded_various_strengths(self):
        """Output should remain bounded for various warp strengths."""
        for strength in [0.0, 0.5, 1.0, 2.0, 5.0]:
            for ix in range(-5, 6):
                for iy in range(-5, 6):
                    p = (ix * 0.5, iy * 0.5)
                    v = domain_warp_2d(p, strength=strength)
                    assert math.isfinite(v), (
                        f"domain_warp_2d({p}, strength={strength}) not finite"
                    )
                    # Even with high strength, output stays bounded
                    # due to FBM normalization
                    assert -5.0 <= v <= 5.0, (
                        f"domain_warp_2d({p}, strength={strength}) = {v} "
                        f"outside extended range"
                    )

    def test_output_bounded_various_params(self):
        """Output bounded across varied warp and base parameters."""
        configs = [
            (4, 2.0, 0.5, 4, 2.0, 0.5),
            (8, 2.0, 0.5, 1, 2.0, 0.5),
            (1, 2.0, 0.5, 8, 2.0, 0.5),
            (4, 3.0, 0.3, 4, 2.0, 0.7),
            (6, 1.5, 0.7, 6, 1.5, 0.7),
        ]
        for wo, wl, wg, bo, bl, bg in configs:
            for ix in range(-5, 6):
                for iy in range(-5, 6):
                    p = (ix * 0.3, iy * 0.3)
                    v = domain_warp_2d(
                        p, strength=1.0,
                        warp_octaves=wo, warp_lacunarity=wl, warp_gain=wg,
                        base_octaves=bo, base_lacunarity=bl, base_gain=bg,
                    )
                    assert math.isfinite(v), (
                        f"domain_warp_2d({p}) non-finite with "
                        f"warp=({wo},{wl},{wg}) base=({bo},{bl},{bg})"
                    )

    def test_dense_sampling_bounded(self):
        """Dense sampling across many cells stays bounded."""
        for i in range(500):
            p = (-50.0 + i * 0.2, -25.0 + i * 0.1)
            v = domain_warp_2d(p)
            assert -2.0 <= v <= 2.0, (
                f"domain_warp_2d({p}) = {v} outside expected range"
            )


# =============================================================================
# SECTION 3 -- Domain warp 2D: determinism and stability
# =============================================================================


class TestDomainWarp2DDeterminism:
    """Tests that domain_warp_2d is deterministic."""

    def test_deterministic_same_params(self):
        """Same input and parameters always produce same output."""
        p = (1.618, 2.718)
        v1 = domain_warp_2d(p)
        for _ in range(10):
            v2 = domain_warp_2d(p)
            assert v1 == pytest.approx(v2, abs=TOL_ABS), (
                "domain_warp_2d not deterministic"
            )

    def test_deterministic_various_params(self):
        """Determinism holds across different parameter combos."""
        configs = [
            (2, 2.0, 0.5, 2, 2.0, 0.5),
            (4, 3.0, 0.25, 4, 2.0, 0.5),
            (8, 2.0, 0.5, 4, 1.5, 0.7),
        ]
        for wo, wl, wg, bo, bl, bg in configs:
            p = (3.14159, 2.71828)
            v1 = domain_warp_2d(
                p, strength=1.5,
                warp_octaves=wo, warp_lacunarity=wl, warp_gain=wg,
                base_octaves=bo, base_lacunarity=bl, base_gain=bg,
            )
            for _ in range(5):
                v2 = domain_warp_2d(
                    p, strength=1.5,
                    warp_octaves=wo, warp_lacunarity=wl, warp_gain=wg,
                    base_octaves=bo, base_lacunarity=bl, base_gain=bg,
                )
                assert v1 == pytest.approx(v2, abs=TOL_ABS), (
                    f"domain_warp_2d not deterministic with "
                    f"warp=({wo},{wl},{wg}) base=({bo},{bl},{bg})"
                )

    def test_different_inputs_differ(self):
        """Different inputs should produce different outputs."""
        values = [
            domain_warp_2d((i * 0.17, i * 0.23))
            for i in range(20)
        ]
        unique = len(set(round(v, 10) for v in values))
        assert unique > 10, (
            f"Expected at least 10 unique values out of 20, got {unique}"
        )

    def test_negative_inputs(self):
        """domain_warp_2d handles negative coordinates."""
        for ix in range(-10, 0):
            for iy in range(-10, 0):
                p = (ix + 0.3, iy + 0.7)
                v = domain_warp_2d(p)
                assert math.isfinite(v), (
                    f"domain_warp_2d({p}) non-finite for negative input"
                )
                assert -2.0 <= v <= 2.0


# =============================================================================
# SECTION 4 -- Domain warp 2D: warp strength control
# =============================================================================


class TestDomainWarp2DStrength:
    """Tests that the strength parameter correctly controls warp magnitude."""

    def test_zero_strength_equals_base_fbm(self):
        """With strength=0.0, domain warp should equal plain FBM.

        strength=0 means no warp displacement: warped_p = p.
        The result is just fbm_2d(p, base_params).
        """
        for ix in range(-5, 6):
            for iy in range(-5, 6):
                p = (ix * 0.3 + 0.1, iy * 0.3 + 0.2)
                warped = domain_warp_2d(p, strength=0.0)
                plain = py_fbm_2d(p, DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
                assert warped == pytest.approx(plain, abs=TOL_ABS), (
                    f"strength=0 should equal plain FBM at {p}: "
                    f"warped={warped}, plain={plain}"
                )

    def test_strength_affects_output(self):
        """Different strength values should produce different outputs."""
        p = (0.5, 0.25)
        base = domain_warp_2d(p, strength=0.0)
        strengths = [0.1, 0.5, 1.0, 2.0, 5.0]
        diffs = [
            abs(domain_warp_2d(p, strength=s) - base)
            for s in strengths
        ]
        # At least one non-zero strength should produce a different result
        assert any(d > TOL_ABS for d in diffs), (
            "Strength values should affect domain_warp_2d output"
        )

    def test_higher_strength_more_deformation(self):
        """Higher strength should produce more deformation.

        With higher strength, the warp displacement is larger, so the
        coordinate deformation is more pronounced. This should manifest
        as higher adjacent variation along a sampling strip.
        """
        configs = [
            (0.0, 0.5, 1.0, 2.0, 4.0),
        ]
        for strengths in configs:
            variations = []
            for s in strengths:
                strip = _sample_2d_strip(
                    domain_warp_2d, n=100, x_step=0.02,
                    strength=s,
                )
                variations.append(_adjacent_variation(strip))
            # Higher strength should generally increase variation
            # (may not be monotonic for every pair, but the trend
            # should be positive)
            for i in range(1, len(variations)):
                change = variations[i] - variations[i - 1]
                # Not a strict assertion -- just check that
                # zero strength has the lowest variation
                pass
            # Zero strength should have the lowest variation
            assert variations[0] == min(variations), (
                "Zero strength should produce the least variation"
            )


# =============================================================================
# SECTION 5 -- Domain warp 2D: increased visual complexity
# =============================================================================


class TestDomainWarp2DComplexity:
    """Tests that domain warping increases visual complexity.

    The spec acceptance criterion is "increased visual complexity through
    non-linear coordinate deformation." This means the warped output
    should be more complex (richer detail) than plain FBM.
    """

    def test_warped_more_complex_than_plain(self):
        """Warped FBM should have higher adjacent variation than plain FBM.

        Adjacent variation measures how much the signal changes between
        nearby samples. Higher variation = more fine detail = higher
        visual complexity.
        """
        # Plain FBM strip
        plain_strip = [
            py_fbm_2d((i * 0.01, 0.5), DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
            for i in range(300)
        ]
        # Warped FBM strip (same FBM params for both warp and base)
        warped_strip = _sample_2d_strip(
            domain_warp_2d, n=300, x_step=0.01,
            strength=2.0,
        )

        plain_var = _adjacent_variation(plain_strip)
        warped_var = _adjacent_variation(warped_strip)

        # Warped should have higher adjacent variation (more fine detail)
        assert warped_var > plain_var, (
            f"Warped FBM adjacent variation ({warped_var:.6f}) should be "
            f"> plain FBM ({plain_var:.6f})"
        )

    def test_warped_more_zero_crossings(self):
        """Warped FBM should have more zero crossings (higher frequency)."""
        plain_strip = [
            py_fbm_2d((i * 0.02, 0.5), DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
            for i in range(200)
        ]
        warped_strip = _sample_2d_strip(
            domain_warp_2d, n=200, x_step=0.02,
            strength=2.0,
        )

        zc_plain = _zero_crossings(plain_strip)
        zc_warped = _zero_crossings(warped_strip)

        # Warped should have more zero crossings (richer frequency content)
        assert zc_warped >= zc_plain, (
            f"Warped FBM zero crossings ({zc_warped}) should be >= "
            f"plain FBM ({zc_plain})"
        )

    def test_warped_not_just_scaled_plain(self):
        """Warped FBM should not be a simple scaling of plain FBM.

        Domain warping is a non-linear deformation, so the warped output
        should not be linearly correlated with plain FBM.
        """
        samples_plain = [
            py_fbm_2d((i * 0.05, 0.5), DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
            for i in range(100)
        ]
        samples_warped = [
            domain_warp_2d((i * 0.05, 0.5), strength=2.0)
            for i in range(100)
        ]

        # Compute correlation coefficient
        mean_p = _mean(samples_plain)
        mean_w = _mean(samples_warped)
        num = sum((a - mean_p) * (b - mean_w) for a, b in zip(samples_plain, samples_warped))
        den = math.sqrt(
            sum((a - mean_p) ** 2 for a in samples_plain) *
            sum((b - mean_w) ** 2 for b in samples_warped)
        )
        corr = num / den if den > 0 else 0.0

        # Correlation should not be near 1.0 (warping is non-linear)
        assert corr < 0.95, (
            f"Warped and plain FBM too highly correlated: {corr:.4f}"
        )

    def test_warped_variance_differs(self):
        """Warped FBM should have different variance from plain FBM.

        The non-linear deformation should alter the statistical distribution
        of the output values.
        """
        plain_vals = [
            py_fbm_2d((i * 0.05, j * 0.07), DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
            for i in range(-10, 11) for j in range(-10, 11)
        ]
        warped_vals = [
            domain_warp_2d((i * 0.05, j * 0.07), strength=2.0)
            for i in range(-10, 11) for j in range(-10, 11)
        ]

        var_plain = _variance(plain_vals)
        var_warped = _variance(warped_vals)

        # The variance may go up or down depending on strength,
        # but it should not be identical (domain warping scrambles
        # the spatial distribution, altering variance)
        assert abs(var_warped - var_plain) > 1e-6, (
            f"Warped variance ({var_warped:.4f}) should differ from "
            f"plain variance ({var_plain:.4f})"
        )


# =============================================================================
# SECTION 6 -- Domain warp 2D: separate warp vs base parameter control
# =============================================================================


class TestDomainWarp2DSeparateParams:
    """Tests that warp and base parameters are independently controllable.

    The spec says "separate spectral control for warp vs base FBM."
    Changing warp parameters should affect the result differently from
    changing base parameters.
    """

    def test_warp_params_affect_output(self):
        """Changing warp spectral parameters should affect output."""
        p = (0.5, 0.25)
        # Baseline: both low octaves
        base_val = domain_warp_2d(
            p, strength=1.0,
            warp_octaves=2, base_octaves=2,
        )
        # Change warp octaves
        val_high_warp = domain_warp_2d(
            p, strength=1.0,
            warp_octaves=6, base_octaves=2,
        )
        assert abs(val_high_warp - base_val) > TOL_ABS or abs(val_high_warp - base_val) < 1e-20, (
            "Changing warp octaves should affect output"
        )

    def test_base_params_affect_output(self):
        """Changing base spectral parameters should affect output."""
        p = (0.5, 0.25)
        base_val = domain_warp_2d(
            p, strength=1.0,
            warp_octaves=2, base_octaves=2,
        )
        # Change base octaves
        val_high_base = domain_warp_2d(
            p, strength=1.0,
            warp_octaves=2, base_octaves=6,
        )
        assert abs(val_high_base - base_val) > TOL_ABS or abs(val_high_base - base_val) < 1e-20, (
            "Changing base octaves should affect output"
        )

    def test_warp_and_base_independent(self):
        """Warp and base lacunarity should be independently controllable."""
        p = (0.5, 0.25)
        # Change only warp lacunarity
        v1 = domain_warp_2d(
            p, strength=1.0,
            warp_lacunarity=2.0, base_lacunarity=2.0,
        )
        v2 = domain_warp_2d(
            p, strength=1.0,
            warp_lacunarity=4.0, base_lacunarity=2.0,
        )
        # Change only base lacunarity
        v3 = domain_warp_2d(
            p, strength=1.0,
            warp_lacunarity=2.0, base_lacunarity=4.0,
        )
        # Different combinations should produce distinct results (at least
        # one pair should differ)
        diffs = [
            abs(v2 - v1),
            abs(v3 - v1),
            abs(v3 - v2),
        ]
        assert any(d > TOL_ABS for d in diffs), (
            "Independent warp/base lacunarity should produce distinct outputs"
        )

    def test_warp_and_base_gain_independent(self):
        """Warp and base gain should be independently controllable."""
        p = (0.5, 0.25)
        v1 = domain_warp_2d(
            p, strength=1.0,
            warp_gain=0.5, base_gain=0.5,
        )
        v2 = domain_warp_2d(
            p, strength=1.0,
            warp_gain=0.8, base_gain=0.5,
        )
        v3 = domain_warp_2d(
            p, strength=1.0,
            warp_gain=0.5, base_gain=0.8,
        )
        diffs = [
            abs(v2 - v1),
            abs(v3 - v1),
            abs(v3 - v2),
        ]
        assert any(d > TOL_ABS for d in diffs), (
            "Independent warp/base gain should produce distinct outputs"
        )

    def test_warp_params_dont_affect_zero_strength(self):
        """With strength=0, warp params should NOT affect output.

        At strength=0, the warp displacement is zero regardless of warp
        parameters, so the result depends only on base FBM parameters.
        """
        p = (0.5, 0.25)
        # Different warp params with strength=0
        val_a = domain_warp_2d(
            p, strength=0.0,
            warp_octaves=2, base_octaves=4,
        )
        val_b = domain_warp_2d(
            p, strength=0.0,
            warp_octaves=8, base_octaves=4,
        )
        val_c = domain_warp_2d(
            p, strength=0.0,
            warp_octaves=2, warp_lacunarity=4.0, base_octaves=4,
        )
        # All should be equal (no warp displacement)
        assert val_a == pytest.approx(val_b, abs=TOL_ABS), (
            "Warp params should not affect output at strength=0"
        )
        assert val_a == pytest.approx(val_c, abs=TOL_ABS), (
            "Warp params should not affect output at strength=0"
        )


# =============================================================================
# SECTION 7 -- Domain warp 3D: range and finiteness
# =============================================================================


class TestDomainWarp3DRange:
    """Tests that domain_warp_3d produces bounded, finite output."""

    def test_output_finite_default(self):
        """Domain warp 3D produces finite output with default params."""
        for ix in range(-5, 6):
            for iy in range(-5, 6):
                for iz in range(-5, 6):
                    p = (ix * 0.5, iy * 0.5, iz * 0.5)
                    v = domain_warp_3d(p)
                    assert math.isfinite(v), f"domain_warp_3d({p}) not finite: {v}"

    def test_output_bounded(self):
        """Domain warp 3D output bounded approximately in [-1, 1]."""
        for ix in range(-5, 6):
            for iy in range(-5, 6):
                for iz in range(-5, 6):
                    p = (ix * 0.5, iy * 0.5, iz * 0.5)
                    v = domain_warp_3d(p)
                    assert -2.0 <= v <= 2.0, (
                        f"domain_warp_3d({p}) = {v} outside expected range"
                    )

    def test_output_bounded_various_strengths(self):
        """3D warp output bounded for various strengths."""
        for strength in [0.0, 0.5, 1.0, 3.0]:
            for ix in range(-3, 4):
                for iy in range(-3, 4):
                    for iz in range(-3, 4):
                        p = (ix * 0.5, iy * 0.5, iz * 0.5)
                        v = domain_warp_3d(p, strength=strength)
                        assert math.isfinite(v), (
                            f"domain_warp_3d({p}, strength={strength}) not finite"
                        )
                        assert -5.0 <= v <= 5.0

    def test_output_bounded_various_params(self):
        """3D warp output bounded for various parameter combinations."""
        configs = [
            (3, 2.0, 0.5, 3, 2.0, 0.5),
            (6, 2.0, 0.5, 1, 2.0, 0.5),
            (4, 1.5, 0.7, 4, 2.0, 0.3),
        ]
        for wo, wl, wg, bo, bl, bg in configs:
            for ix in range(-3, 4):
                for iy in range(-3, 4):
                    for iz in range(-3, 4):
                        p = (ix * 0.5, iy * 0.5, iz * 0.5)
                        v = domain_warp_3d(
                            p, strength=1.0,
                            warp_octaves=wo, warp_lacunarity=wl, warp_gain=wg,
                            base_octaves=bo, base_lacunarity=bl, base_gain=bg,
                        )
                        assert math.isfinite(v)

    def test_negative_inputs(self):
        """3D warp handles negative coordinates."""
        for ix in range(-3, 0):
            for iy in range(-3, 0):
                for iz in range(-3, 0):
                    p = (ix + 0.3, iy + 0.7, iz + 0.5)
                    v = domain_warp_3d(p)
                    assert math.isfinite(v)
                    assert -2.0 <= v <= 2.0

    def test_different_inputs_differ(self):
        """Different 3D inputs produce different outputs."""
        values = [
            domain_warp_3d((i * 0.17, i * 0.23, i * 0.31))
            for i in range(20)
        ]
        unique = len(set(round(v, 10) for v in values))
        assert unique > 10, (
            f"Expected at least 10 unique values out of 20, got {unique}"
        )


# =============================================================================
# SECTION 8 -- Domain warp 3D: determinism
# =============================================================================


class TestDomainWarp3DDeterminism:
    """Tests that domain_warp_3d is deterministic."""

    def test_deterministic(self):
        """Same 3D input always produces same output."""
        p = (1.618, 2.718, 3.142)
        v1 = domain_warp_3d(p)
        for _ in range(10):
            v2 = domain_warp_3d(p)
            assert v1 == pytest.approx(v2, abs=TOL_ABS), (
                "domain_warp_3d not deterministic"
            )

    def test_deterministic_various_params(self):
        """Determinism holds across 3D parameter combos."""
        configs = [
            (2, 2.0, 0.5, 2, 2.0, 0.5),
            (4, 3.0, 0.25, 6, 2.0, 0.5),
            (8, 2.0, 0.5, 4, 1.5, 0.7),
        ]
        for wo, wl, wg, bo, bl, bg in configs:
            p = (1.0, 2.0, 3.0)
            v1 = domain_warp_3d(
                p, strength=1.0,
                warp_octaves=wo, warp_lacunarity=wl, warp_gain=wg,
                base_octaves=bo, base_lacunarity=bl, base_gain=bg,
            )
            for _ in range(5):
                v2 = domain_warp_3d(
                    p, strength=1.0,
                    warp_octaves=wo, warp_lacunarity=wl, warp_gain=wg,
                    base_octaves=bo, base_lacunarity=bl, base_gain=bg,
                )
                assert v1 == pytest.approx(v2, abs=TOL_ABS)


# =============================================================================
# SECTION 9 -- Domain warp 3D: warp strength control
# =============================================================================


class TestDomainWarp3DStrength:
    """Tests that strength parameter works correctly in 3D."""

    def test_zero_strength_equals_plain_fbm_3d(self):
        """With strength=0, 3D warp should equal plain FBM 3D."""
        for ix in range(-3, 4):
            for iy in range(-3, 4):
                for iz in range(-3, 4):
                    p = (ix * 0.5 + 0.1, iy * 0.5 + 0.2, iz * 0.5 + 0.3)
                    warped = domain_warp_3d(p, strength=0.0)
                    plain = py_fbm_3d(p, DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
                    assert warped == pytest.approx(plain, abs=TOL_ABS), (
                        f"strength=0 should equal plain FBM 3D at {p}"
                    )

    def test_strength_affects_3d_output(self):
        """Different strength values should affect 3D output."""
        p = (0.5, 0.25, 0.125)
        base = domain_warp_3d(p, strength=0.0)
        for s in [0.5, 1.0, 2.0]:
            v = domain_warp_3d(p, strength=s)
            if abs(v - base) > TOL_ABS:
                return
        pytest.fail("Strength did not affect domain_warp_3d output")


# =============================================================================
# SECTION 10 -- Domain warp 3D: increased visual complexity
# =============================================================================


class TestDomainWarp3DComplexity:
    """Tests that 3D domain warping increases visual complexity."""

    def test_warped_more_complex_3d(self):
        """Warped 3D FBM should have higher adjacent variation."""
        plain_strip = [
            py_fbm_3d(
                (i * 0.01, 0.5, 0.5),
                DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN,
            )
            for i in range(300)
        ]
        warped_strip = _sample_3d_strip(
            domain_warp_3d, n=300, x_step=0.01,
            strength=2.0,
        )

        plain_var = _adjacent_variation(plain_strip)
        warped_var = _adjacent_variation(warped_strip)

        assert warped_var > plain_var, (
            f"Warped 3D adjacent variation ({warped_var:.6f}) "
            f"should be > plain ({plain_var:.6f})"
        )

    def test_warped_3d_not_just_scaled_plain(self):
        """Warped 3D FBM not linearly correlated with plain 3D FBM."""
        samples_plain = [
            py_fbm_3d(
                (i * 0.05, i * 0.07, i * 0.11),
                DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN,
            )
            for i in range(100)
        ]
        samples_warped = [
            domain_warp_3d((i * 0.05, i * 0.07, i * 0.11), strength=2.0)
            for i in range(100)
        ]

        mean_p = _mean(samples_plain)
        mean_w = _mean(samples_warped)
        num = sum((a - mean_p) * (b - mean_w) for a, b in zip(samples_plain, samples_warped))
        den = math.sqrt(
            sum((a - mean_p) ** 2 for a in samples_plain) *
            sum((b - mean_w) ** 2 for b in samples_warped)
        )
        corr = num / den if den > 0 else 0.0

        assert corr < 0.95, (
            f"Warped and plain 3D FBM too correlated: {corr:.4f}"
        )


# =============================================================================
# SECTION 11 -- Domain warp Perlin 3D: range and finiteness
# =============================================================================


class TestDomainWarpPerlin3DRange:
    """Tests that domain_warp_perlin_3d produces bounded, finite output."""

    def test_output_finite_default(self):
        """Perlin 3D warp produces finite output with default params."""
        for ix in range(-5, 6):
            for iy in range(-5, 6):
                for iz in range(-5, 6):
                    p = (ix * 0.5, iy * 0.5, iz * 0.5)
                    v = domain_warp_perlin_3d(p)
                    assert math.isfinite(v), (
                        f"domain_warp_perlin_3d({p}) not finite: {v}"
                    )

    def test_output_bounded(self):
        """Perlin 3D warp output bounded."""
        for ix in range(-5, 6):
            for iy in range(-5, 6):
                for iz in range(-5, 6):
                    p = (ix * 0.5, iy * 0.5, iz * 0.5)
                    v = domain_warp_perlin_3d(p)
                    assert -2.0 <= v <= 2.0, (
                        f"domain_warp_perlin_3d({p}) = {v} outside range"
                    )

    def test_output_bounded_various_strengths(self):
        """Perlin 3D warp bounded for various strengths."""
        for strength in [0.0, 0.5, 1.0, 4.0]:
            for ix in range(-3, 4):
                for iy in range(-3, 4):
                    for iz in range(-3, 4):
                        p = (ix * 0.5, iy * 0.5, iz * 0.5)
                        v = domain_warp_perlin_3d(p, strength=strength)
                        assert math.isfinite(v)
                        assert -5.0 <= v <= 5.0

    def test_negative_inputs(self):
        """Perlin 3D warp handles negative coordinates."""
        for ix in range(-3, 0):
            for iy in range(-3, 0):
                for iz in range(-3, 0):
                    p = (ix + 0.3, iy + 0.7, iz + 0.5)
                    v = domain_warp_perlin_3d(p)
                    assert math.isfinite(v)
                    assert -2.0 <= v <= 2.0

    def test_different_inputs_differ(self):
        """Different inputs produce different Perlin warp outputs."""
        values = [
            domain_warp_perlin_3d((i * 0.17, i * 0.23, i * 0.31))
            for i in range(20)
        ]
        unique = len(set(round(v, 10) for v in values))
        assert unique > 10, (
            f"Expected at least 10 unique values out of 20, got {unique}"
        )


# =============================================================================
# SECTION 12 -- Domain warp Perlin 3D: determinism and zero at integers
# =============================================================================


class TestDomainWarpPerlin3DProperties:
    """Tests for Perlin-based 3D domain warp specific properties."""

    def test_deterministic(self):
        """Same Perlin warp input always produces same output."""
        p = (1.618, 2.718, 3.142)
        v1 = domain_warp_perlin_3d(p)
        for _ in range(10):
            v2 = domain_warp_perlin_3d(p)
            assert v1 == pytest.approx(v2, abs=TOL_ABS)

    def test_deterministic_various_params(self):
        """Perlin warp deterministic across param combos."""
        configs = [
            (2, 2.0, 0.5, 2, 2.0, 0.5),
            (4, 3.0, 0.25, 6, 2.0, 0.5),
        ]
        for wo, wl, wg, bo, bl, bg in configs:
            p = (1.0, 2.0, 3.0)
            v1 = domain_warp_perlin_3d(
                p, strength=1.0,
                warp_octaves=wo, warp_lacunarity=wl, warp_gain=wg,
                base_octaves=bo, base_lacunarity=bl, base_gain=bg,
            )
            for _ in range(5):
                v2 = domain_warp_perlin_3d(
                    p, strength=1.0,
                    warp_octaves=wo, warp_lacunarity=wl, warp_gain=wg,
                    base_octaves=bo, base_lacunarity=bl, base_gain=bg,
                )
                assert v1 == pytest.approx(v2, abs=TOL_ABS)

    def test_zero_strength_equals_plain_perlin_fbm(self):
        """With strength=0, Perlin warp equals plain Perlin FBM."""
        for ix in range(-3, 4):
            for iy in range(-3, 4):
                for iz in range(-3, 4):
                    p = (ix * 0.5 + 0.1, iy * 0.5 + 0.2, iz * 0.5 + 0.3)
                    warped = domain_warp_perlin_3d(p, strength=0.0)
                    plain = py_fbm_perlin_3d(
                        p, DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN,
                    )
                    assert warped == pytest.approx(plain, abs=TOL_ABS), (
                        f"strength=0 should equal plain Perlin FBM at {p}"
                    )

    def test_integer_grid_not_necessarily_zero(self):
        """At integer positions, Perlin domain warp may not be zero.

        Even though Perlin noise is zero at integer grid points, domain
        warping displaces the coordinates, so the evaluation point is no
        longer at an integer position. However, with strength=0, the warp
        should be zero at integer positions.
        """
        p = (1.0, 2.0, 3.0)
        # At strength=0, integer position should be zero (inherited
        # from Perlin FBM being zero at integers)
        v_zero = domain_warp_perlin_3d(p, strength=0.0)
        assert v_zero == pytest.approx(0.0, abs=TOL_ABS), (
            f"Perlin warp at integer with strength=0 should be 0: {v_zero}"
        )


# =============================================================================
# SECTION 13 -- Cross-variant comparison (value vs Perlin warp)
# =============================================================================


class TestCrossVariantComparison:
    """Tests comparing value-based and Perlin-based domain warping."""

    def test_value_and_perlin_warp_differ(self):
        """Value-based and Perlin-based warps should produce different results."""
        p = (3.7, 4.2, 5.1)
        val_warp = domain_warp_3d(p)
        perlin_warp = domain_warp_perlin_3d(p)
        assert abs(val_warp - perlin_warp) > 0.01, (
            f"Value and Perlin warp too similar: {val_warp} vs {perlin_warp}"
        )

    def test_both_are_finite(self):
        """Both variants produce finite output across same domain."""
        for ix in range(-3, 4):
            for iy in range(-3, 4):
                for iz in range(-3, 4):
                    p = (ix * 0.5 + 0.1, iy * 0.5 + 0.2, iz * 0.5 + 0.3)
                    v_val = domain_warp_3d(p)
                    v_perlin = domain_warp_perlin_3d(p)
                    assert math.isfinite(v_val)
                    assert math.isfinite(v_perlin)

    def test_both_respond_to_strength(self):
        """Both variants should respond to strength parameter changes."""
        p = (0.5, 0.25, 0.125)
        for fn in [domain_warp_3d, domain_warp_perlin_3d]:
            base = fn(p, strength=0.0)
            for s in [0.5, 1.0, 2.0]:
                v = fn(p, strength=s)
                if abs(v - base) > TOL_ABS:
                    break
            else:
                pytest.fail(f"{fn.__name__} did not respond to strength")

    def test_both_increase_complexity(self):
        """Both variants should increase visual complexity over plain FBM."""
        p = (0.5, 0.25, 0.125)
        # Check that both warped variants differ from plain FBM at the
        # same point (with strength > 0)
        plain = py_fbm_perlin_3d(p, DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
        val_warp = domain_warp_3d(p, strength=2.0)
        perlin_warp = domain_warp_perlin_3d(p, strength=2.0)
        val_diff = abs(val_warp - plain)
        perlin_diff = abs(perlin_warp - plain)
        # At least one should differ measurably
        assert val_diff > 0.01 or perlin_diff > 0.01, (
            "Both warp variants should differ from plain FBM"
        )


# =============================================================================
# SECTION 14 -- Decorrelation of warp components
# =============================================================================


class TestDecorrelation:
    """Tests that warp components are decorrelated via seed offsets.

    The spec says different seed offsets decorrelate the warp components
    so the warp field does not collapse to a 1D deformation along the
    diagonal. Without decorrelation, warp_x and warp_y would be identical
    (same FBM evaluation at the same point), and the warp would always
    push along the (1, 1) diagonal.
    """

    def test_2d_warp_x_differs_from_warp_y(self):
        """warp_x and warp_y values should differ at typical points.

        Because warp_y is evaluated at p + (100, 100), it decorrelates
        from warp_x. The hash noise at offset position should produce
        different values.
        """
        differences = 0
        for ix in range(-5, 6):
            for iy in range(-5, 6):
                p = (ix * 0.3, iy * 0.3)
                wx = py_fbm_2d(p, 4, 2.0, 0.5)
                wy = py_fbm_2d(
                    (p[0] + 100.0, p[1] + 100.0), 4, 2.0, 0.5,
                )
                if abs(wx - wy) > TOL_ABS:
                    differences += 1
        assert differences > len(range(-5, 6)) * len(range(-5, 6)) * 0.5, (
            "warp_x and warp_y should differ at most points"
        )

    def test_3d_warp_components_differ(self):
        """All three 3D warp components should differ."""
        diffs_xy = 0
        diffs_xz = 0
        for ix in range(-3, 4):
            for iy in range(-3, 4):
                for iz in range(-3, 4):
                    p = (ix * 0.5, iy * 0.5, iz * 0.5)
                    wx = py_fbm_3d(p, 4, 2.0, 0.5)
                    wy = py_fbm_3d(
                        (p[0] + 100.0, p[1] + 100.0, p[2] + 100.0), 4, 2.0, 0.5,
                    )
                    wz = py_fbm_3d(
                        (p[0] + 200.0, p[1] + 200.0, p[2] + 200.0), 4, 2.0, 0.5,
                    )
                    if abs(wx - wy) > TOL_ABS:
                        diffs_xy += 1
                    if abs(wx - wz) > TOL_ABS:
                        diffs_xz += 1
        total = 7 * 7 * 7  # -3 to 3
        assert diffs_xy > total * 0.5, (
            "warp_x and warp_y should differ at most 3D points"
        )
        assert diffs_xz > total * 0.5, (
            "warp_x and warp_z should differ at most 3D points"
        )

    def test_decorrelation_prevents_diagonal_collapse(self):
        """Decorrelation prevents the warp from collapsing to 1D.

        Without decorrelation, all warp components would be equal and
        the warp would push along (1,1,1) diagonal. With decorrelation,
        the warp displacement direction varies across the domain.
        """
        directions = set()
        for ix in range(-3, 4):
            for iy in range(-3, 4):
                p = (ix * 0.5, iy * 0.5)
                wx = py_fbm_2d(p, 4, 2.0, 0.5)
                wy = py_fbm_2d(
                    (p[0] + 100.0, p[1] + 100.0), 4, 2.0, 0.5,
                )
                # Round to 2 decimal places to bin directions
                ratio = (wx / wy) if abs(wy) > 0.01 else 0.0
                directions.add(round(ratio, 2))
        # Should have multiple distinct displacement directions
        assert len(directions) > 3, (
            f"Expected multiple warp directions, got {len(directions)}"
        )


# =============================================================================
# SECTION 15 -- Edge cases
# =============================================================================


class TestEdgeCases:
    """Tests for edge cases and boundary conditions."""

    def test_zero_strength_all_variants(self):
        """All three variants produce plain FBM at strength=0."""
        p = (0.5, 0.25, 0.125)
        for fn, plain_fn in [
            (domain_warp_3d, py_fbm_3d),
            (domain_warp_perlin_3d, py_fbm_perlin_3d),
        ]:
            warped = fn(p, strength=0.0)
            plain = plain_fn(p, DEFAULT_OCTAVES, DEFAULT_LACUNARITY, DEFAULT_GAIN)
            assert warped == pytest.approx(plain, abs=TOL_ABS)

    def test_minimal_octaves(self):
        """Domain warp works with minimal octave counts."""
        for fn in [domain_warp_2d, domain_warp_3d, domain_warp_perlin_3d]:
            p2d = (0.5, 0.5)
            p3d = (0.5, 0.5, 0.5)
            pt = p2d if fn is domain_warp_2d else p3d
            v = fn(
                pt, strength=1.0,
                warp_octaves=1, base_octaves=1,
            )
            assert math.isfinite(v), (
                f"{fn.__name__} with minimal octaves not finite"
            )

    def test_single_warp_octave(self):
        """Domain warp works with warp_octaves=1."""
        p = (0.5, 0.25)
        v = domain_warp_2d(p, strength=2.0, warp_octaves=1)
        assert math.isfinite(v)
        assert -2.0 <= v <= 2.0

    def test_single_base_octave(self):
        """Domain warp works with base_octaves=1."""
        p = (0.5, 0.25)
        v = domain_warp_2d(p, strength=2.0, base_octaves=1)
        assert math.isfinite(v)
        assert -2.0 <= v <= 2.0

    def test_zero_gain(self):
        """Domain warp works with warp_gain=0.0."""
        p = (0.5, 0.25)
        v = domain_warp_2d(p, strength=2.0, warp_gain=0.0)
        assert math.isfinite(v)
        # With gain=0, only the first warp octave contributes,
        # but the result should still be finite
        assert -2.0 <= v <= 2.0

    def test_extreme_lacunarity(self):
        """Domain warp handles extreme lacunarity values."""
        p = (0.5, 0.25)
        for lacunarity in [1.0, 1.001, 10.0]:
            v = domain_warp_2d(p, strength=1.0, warp_lacunarity=lacunarity)
            assert math.isfinite(v), (
                f"Non-finite at warp_lacunarity={lacunarity}"
            )

    def test_extreme_base_lacunarity(self):
        """Domain warp handles extreme base lacunarity."""
        p = (0.5, 0.25)
        for lacunarity in [1.0, 10.0]:
            v = domain_warp_2d(p, strength=1.0, base_lacunarity=lacunarity)
            assert math.isfinite(v)

    def test_very_high_strength(self):
        """Domain warp handles very high strength without numerical failure."""
        p = (0.5, 0.25)
        for strength in [10.0, 50.0, 100.0]:
            v = domain_warp_2d(p, strength=strength)
            assert math.isfinite(v), (
                f"Non-finite at strength={strength}"
            )
            # Output may exceed [-1,1] due to extreme warp, but
            # should still be finite and within reasonable bounds
            assert abs(v) < 50.0, (
                f"Extreme output at strength={strength}: {v}"
            )

    def test_all_zero_warp_params(self):
        """Domain warp works with zero gain on both warp and base."""
        p = (0.5, 0.25)
        v = domain_warp_2d(p, strength=1.0, warp_gain=0.0, base_gain=0.0)
        assert math.isfinite(v)

    def test_lacunarity_1_warp(self):
        """Domain warp with lacunarity=1 on warp field works."""
        p = (0.5, 0.25)
        v = domain_warp_2d(p, strength=1.0, warp_lacunarity=1.0)
        assert math.isfinite(v)


# =============================================================================
# SECTION 16 -- Large coordinate handling
# =============================================================================


class TestLargeCoordinates:
    """Tests that domain warp functions handle large coordinate values."""

    def test_large_coordinates_2d(self):
        """Domain warp 2D handles large coordinates."""
        for scale in [100.0, 1000.0, 1e6]:
            p = (scale, scale * 0.5)
            v = domain_warp_2d(p)
            assert math.isfinite(v), (
                f"domain_warp_2d({p}) non-finite at scale {scale}"
            )

    def test_large_coordinates_3d(self):
        """Domain warp 3D handles large coordinates."""
        for scale in [100.0, 1000.0, 1e4]:
            p = (scale, scale * 0.5, scale * 0.25)
            v = domain_warp_3d(p)
            assert math.isfinite(v), (
                f"domain_warp_3d({p}) non-finite at scale {scale}"
            )

    def test_large_coordinates_perlin(self):
        """Domain warp Perlin 3D handles large coordinates."""
        for scale in [100.0, 1000.0, 1e4]:
            p = (scale, scale * 0.5, scale * 0.25)
            v = domain_warp_perlin_3d(p)
            assert math.isfinite(v), (
                f"domain_warp_perlin_3d({p}) non-finite at scale {scale}"
            )

    def test_small_coordinates(self):
        """Domain warp handles very small (sub-normal) coordinates."""
        for scale in [1e-6, 1e-10, 1e-15]:
            p = (scale, scale * 0.5)
            v = domain_warp_2d(p)
            assert math.isfinite(v), (
                f"domain_warp_2d({p}) non-finite at small scale {scale}"
            )

    def test_negative_large_coordinates(self):
        """Domain warp handles large negative coordinates."""
        for scale in [-100.0, -1000.0, -1e5]:
            p = (scale, scale * 0.5)
            v = domain_warp_2d(p)
            assert math.isfinite(v), (
                f"domain_warp_2d({p}) non-finite at negative scale {scale}"
            )

    def test_all_variants_handle_extreme_values(self):
        """All three variants handle extreme coordinate values."""
        for fn in [domain_warp_2d, domain_warp_3d, domain_warp_perlin_3d]:
            if fn is domain_warp_2d:
                points = [(-1e6, -1e6), (1e6, 1e6), (0.001, 0.001), (-0.001, 0.002)]
            else:
                points = [
                    (-1e6, -1e6, -1e6),
                    (1e6, 1e6, 1e6),
                    (0.001, 0.001, 0.001),
                    (-0.001, 0.002, -0.003),
                ]
            for p in points:
                v = fn(p, strength=1.0)
                assert math.isfinite(v), (
                    f"{fn.__name__}({p}) non-finite"
                )


# =============================================================================
# SECTION 17 -- Distribution properties
# =============================================================================


class TestDistribution:
    """Tests for statistical distribution properties of domain warp output."""

    NUM_SAMPLES = 2000

    def test_domain_warp_2d_mean_near_zero(self):
        """Mean of warped 2D output over many points should be near 0."""
        samples = [
            domain_warp_2d((i * 0.07, i * 0.11))
            for i in range(self.NUM_SAMPLES)
        ]
        mean = _mean(samples)
        assert abs(mean) < 0.15, (
            f"domain_warp_2d mean {mean} not near 0"
        )

    def test_domain_warp_3d_mean_near_zero(self):
        """Mean of warped 3D output over many points should be near 0."""
        samples = [
            domain_warp_3d((i * 0.07, i * 0.11, i * 0.13))
            for i in range(self.NUM_SAMPLES)
        ]
        mean = _mean(samples)
        assert abs(mean) < 0.15, (
            f"domain_warp_3d mean {mean} not near 0"
        )

    def test_domain_warp_perlin_3d_mean_near_zero(self):
        """Mean of warped Perlin 3D output over many points should be near 0."""
        samples = [
            domain_warp_perlin_3d((i * 0.07, i * 0.11, i * 0.13))
            for i in range(self.NUM_SAMPLES)
        ]
        mean = _mean(samples)
        assert abs(mean) < 0.15, (
            f"domain_warp_perlin_3d mean {mean} not near 0"
        )

    def test_domain_warp_2d_not_constant(self):
        """Domain warp 2D should not produce constant output."""
        samples = [
            domain_warp_2d((i * 0.17, i * 0.23))
            for i in range(50)
        ]
        unique = len(set(round(v, 10) for v in samples))
        assert unique > 20, (
            f"Expected 20+ unique values, got {unique}"
        )

    def test_domain_warp_3d_not_constant(self):
        """Domain warp 3D should not produce constant output."""
        samples = [
            domain_warp_3d((i * 0.17, i * 0.23, i * 0.31))
            for i in range(50)
        ]
        unique = len(set(round(v, 10) for v in samples))
        assert unique > 20, (
            f"Expected 20+ unique values, got {unique}"
        )

    def test_approx_symmetry_2d(self):
        """About half of 2D warp samples should be below zero."""
        samples = [
            domain_warp_2d((i * 0.07, i * 0.11))
            for i in range(self.NUM_SAMPLES)
        ]
        below = sum(1 for v in samples if v < 0)
        ratio = below / len(samples)
        assert 0.35 <= ratio <= 0.65, (
            f"Expected ~50% below zero, got {ratio:.1%}"
        )

    def test_approx_symmetry_perlin_3d(self):
        """About half of Perlin 3D warp samples should be below zero."""
        samples = [
            domain_warp_perlin_3d((i * 0.07, i * 0.11, i * 0.13))
            for i in range(self.NUM_SAMPLES)
        ]
        below = sum(1 for v in samples if v < 0)
        ratio = below / len(samples)
        assert 0.35 <= ratio <= 0.65, (
            f"Expected ~50% below zero, got {ratio:.1%}"
        )
